### ISSUE TITLE
I don't have yarn and you have a deprecation warning

### ISSUE THREAD

**Issue by MarkMurphy** [infinitered/ignite#1079]
Just installed fresh following the readme instructions and got this:

```
ignite new PizzaApp
  Error: not found: yarn
  
  - which.js:13 getNotFoundError
    [lib]/[ignite-cli]/[which]/which.js:13:12
  
  - which.js:131 Function.whichSync [as sync]
    [lib]/[ignite-cli]/[which]/which.js:131:9
  
  - system-extension.js:113 Object.which
    [lib]/[ignite-cli]/[gluegun]/src/core-extensions/system-extension.js:113:22
  
  - ignite.js:41 Object.attach [as setup]
    [lib]/[ignite-cli]/src/extensions/ignite.js:41:39
  
  - runtime.js:147 extension
    [lib]/[ignite-cli]/[gluegun]/src/domain/runtime.js:147:34
  
  - forEach.js:43 forEach
    [lib]/[ignite-cli]/[ramda]/src/forEach.js:43:5
  
  - _checkForMethod.js:22 
    [lib]/[ignite-cli]/[ramda]/src/internal/_checkForMethod.js:22:10
  
  - _curry2.js:25 f2
    [lib]/[ignite-cli]/[ramda]/src/internal/_curry2.js:25:16
  
  - runtime.js:145 Runtime.run
    [lib]/[ignite-cli]/[gluegun]/src/domain/runtime.js:145:5
  
  - cli.js:65 run
    [lib]/[ignite-cli]/src/cli/cli.js:65:29
  

(node:5874) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: not found: yarn
(node:5874) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

---
`ignite doctor` results:

```
ignite doctor
  Error: not found: yarn
  
  - which.js:13 getNotFoundError
    [lib]/[ignite-cli]/[which]/which.js:13:12
  
  - which.js:131 Function.whichSync [as sync]
    [lib]/[ignite-cli]/[which]/which.js:131:9
  
  - system-extension.js:113 Object.which
    [lib]/[ignite-cli]/[gluegun]/src/core-extensions/system-extension.js:113:22
  
  - ignite.js:41 Object.attach [as setup]
    [lib]/[ignite-cli]/src/extensions/ignite.js:41:39
  
  - runtime.js:147 extension
    [lib]/[ignite-cli]/[gluegun]/src/domain/runtime.js:147:34
  
  - forEach.js:43 forEach
    [lib]/[ignite-cli]/[ramda]/src/forEach.js:43:5
  
  - _checkForMethod.js:22 
    [lib]/[ignite-cli]/[ramda]/src/internal/_checkForMethod.js:22:10
  
  - _curry2.js:25 f2
    [lib]/[ignite-cli]/[ramda]/src/internal/_curry2.js:25:16
  
  - runtime.js:145 Runtime.run
    [lib]/[ignite-cli]/[gluegun]/src/domain/runtime.js:145:5
  
  - cli.js:65 run
    [lib]/[ignite-cli]/src/cli/cli.js:65:29
  

(node:6176) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: not found: yarn
(node:6176) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Node v8.0.0

**Comment by MarkMurphy** [comment]
Clearly, I don't have `yarn` installed. 😄  But I figure `ignite doctor` should be able to handle that and you should probably be aware of the unhandled promise rejection deprecation

**Comment by skellock** [comment]
Thanks for the report.

**Comment by tecfu** [comment]
Same issue.

**Comment by jamonholmgren** [comment]
A similar issue still happens with this. Without `yarn` installed, you get this error with `ignite doctor`:

```
❯ ignite doctor
System
  platform           darwin                                                                                               
  arch               x64                                                                                                  
  cpu                4 cores                                          Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz  
  directory          /Users/jh/Code/ReactNative/playground/PizzaApp                                                       
vvv -----[ DEBUG ]----- vvv
{ Error: not found: yarn
    at getNotFoundError (/Users/jh/.config/yarn/global/node_modules/ignite-cli/node_modules/gluegun/node_modules/which/which.js:13:12)
    at Function.whichSync [as sync] (/Users/jh/.config/yarn/global/node_modules/ignite-cli/node_modules/gluegun/node_modules/which/which.js:131:9)
    at which (/Users/jh/.config/yarn/global/node_modules/ignite-cli/node_modules/gluegun/src/core-extensions/system-extension.js:113:22)
    at Command.module.exports [as run] (/Users/jh/.config/yarn/global/node_modules/ignite-cli/src/commands/doctor.js:45:20)
    at process.internalTickCallback (internal/process/next_tick.js:77:7) code: 'ENOENT' }
^^^ -----[ DEBUG ]----- ^^^
```

This should be relatively straightforward to fix. On [this line](https://github.com/infinitered/ignite/blob/master/src/commands/doctor.js#L45-L46) we need to `try/catch` the exception.
