### ISSUE TITLE
[mac] ignite-ir-boilerplate is not available on npm.

### ISSUE THREAD

**Issue by WayneUong** [infinitered/ignite#1099]
---
What's going on?
I can't create a new app.
---
Steps to reproduce
```
Waynes-MacBook-Pro:Downloads wayneuong$ ignite new PizzaApp
Directory PizzaApp already exists.
? Do you want to overwrite this directory? true
Overwriting PizzaApp...
-----------------------------------------------
  (                  )   (                   
  )\ )   (        ( /(   )\ )    *   )       
 (()/(   )\ )     )\()) (()/(  ` )  /(   (   
  /(_)) (()/(    ((_)\   /(_))  ( )(_))  )\  
 (_))    /(_))_   _((_) (_))   (_(_())  ((_) 
 |_ _|  (_)) __| | \| | |_ _|  |_   _|  | __|
  | |     | (_ | | .` |  | |     | |    | _| 
 |___|     \___| |_|\_| |___|    |_|    |___|
-----------------------------------------------

An unfair headstart for your React Native apps.
https://infinite.red/ignite

-----------------------------------------------

🔥 igniting app PizzaApp
✖ ignite-ir-boilerplate is not available on npm.

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
  We also searched in these directories:

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

```
---
`ignite doctor` results:
```
Waynes-MacBook-Pro:Downloads wayneuong$ ignite doctor
System
  platform           darwin                                                                            
  arch               x64                                                                               
  cpu                8 cores                      Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz  
  directory          /Users/wayneuong/Downloads                                                        
vvv -----[ DEBUG ]----- vvv
{ Error: Command failed: npm --version
module.js:487
    throw err;
    ^

Error: Cannot find module '../lib/utils/unsupported.js'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at /usr/local/lib/node_modules/npm/bin/npm-cli.js:19:21
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:92:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)

    at ChildProcess.exithandler (child_process.js:270:12)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:897:16)
    at Socket.stream.socket.on (internal/child_process.js:340:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:549:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'npm --version',
  stderr: 'module.js:487\n    throw err;\n    ^\n\nError: Cannot find module \'../lib/utils/unsupported.js\'\n    at Function.Module._resolveFilename (module.js:485:15)\n    at Function.Module._load (module.js:437:25)\n    at Module.require (module.js:513:17)\n    at require (internal/module.js:11:18)\n    at /usr/local/lib/node_modules/npm/bin/npm-cli.js:19:21\n    at Object.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:92:3)\n    at Module._compile (module.js:569:30)\n    at Object.Module._extensions..js (module.js:580:10)\n    at Module.load (module.js:503:32)\n    at tryModuleLoad (module.js:466:12)\n' }
^^^ -----[ DEBUG ]----- ^^^

```

**Comment by WayneUong** [comment]
I had to reinstall node + npm.

**Comment by travismgibson** [comment]
Need to upgrade npm:
     **npm install npm@latest -g**
