### ISSUE TITLE
Failing tests on freshly generated project

### ISSUE THREAD

**Issue by thexande** [infinitered/ignite#1109]
---
### The precommit tests are failing on a fresh install. 

```     
> husky - npm run -s precommit
> husky - node v6.3.0

 PASS  Tests/Services/FixtureAPITest.js
 PASS  Tests/Sagas/GithubSagaTest.js
 PASS  Tests/Components/AlertMessageTest.js
  ● Console

    console.error node_modules/fbjs/lib/warning.js:36
      Warning: PropTypes has been moved to a separate package. Accessing React.PropTypes is no longer supported and will be removed completely in React 16. Use the prop-types package on npm instead. (https://fb.me/migrating-from-react-proptypes)
    console.error node_modules/react-native/Libraries/Core/ExceptionsManager.js:71
      Warning: React.createClass is no longer supported. Use a plain JavaScript class instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement. (https://fb.me/migrating-from-react-create-class)

 PASS  Tests/Redux/GithubReduxTest.js
 PASS  Tests/Sagas/StartupSagaTest.js
 FAIL  Tests/Components/RoundedButtonTest.js
  ● Test suite failed to run

    react-dom is an implicit dependency in order to support react@0.13-14. Please add the appropriate version to your devDependencies. See https://github.com/airbnb/enzyme#installation

      at Object.<anonymous> (node_modules/enzyme/build/react-compat.js:108:11)
      at Object.<anonymous> (node_modules/enzyme/build/Utils.js:65:20)
      at Object.<anonymous> (node_modules/enzyme/build/MountedTraversal.js:36:14)

 FAIL  Tests/Components/FullButtonTest.js
  ● Test suite failed to run

    react-dom is an implicit dependency in order to support react@0.13-14. Please add the appropriate version to your devDependencies. See https://github.com/airbnb/enzyme#installation

      at Object.<anonymous> (node_modules/enzyme/build/react-compat.js:108:11)
      at Object.<anonymous> (node_modules/enzyme/build/Utils.js:65:20)
      at Object.<anonymous> (node_modules/enzyme/build/MountedTraversal.js:36:14)

 FAIL  Tests/Components/DrawerButtonTest.js
  ● Test suite failed to run

    react-dom is an implicit dependency in order to support react@0.13-14. Please add the appropriate version to your devDependencies. See https://github.com/airbnb/enzyme#installation

      at Object.<anonymous> (node_modules/enzyme/build/react-compat.js:108:11)
      at Object.<anonymous> (node_modules/enzyme/build/Utils.js:65:20)
      at Object.<anonymous> (node_modules/enzyme/build/MountedTraversal.js:36:14)

Test Suites: 3 failed, 5 passed, 8 total
Tests:       14 passed, 14 total
Snapshots:   3 passed, 3 total
Time:        2.694s, estimated 9s
Ran all test suites.

> husky - pre-commit hook failed (add --no-verify to bypass)
> husky - to debug, use 'npm run precommit'
```
---
Steps to reproduce

---
`ignite doctor` results:

```
System
  platform           darwin
  arch               x64
  cpu                4 cores                                                                       Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz
  directory          /Users/alexandermurphy/Documents/ignite_react_native/ignite_hello_world/ios

JavaScript
  node               8.1.3        /Users/alexandermurphy/.nvm/versions/node/v8.1.3/bin/node
  npm                5.0.3        /Users/alexandermurphy/.nvm/versions/node/v8.1.3/bin/npm
  yarn               0.27.5       /usr/local/bin/yarn

React Native
  react-native-cli   2.0.1

Ignite
  ignite             2.0.0        /Users/alexandermurphy/.nvm/versions/node/v8.1.3/bin/ignite

Android
  java               1.8.0_102    /usr/bin/java
  android home       -            /usr/local/opt/android-sdk

iOS
  xcode              8.3.3
```

**Comment by jamonholmgren** [comment]
Heyo, thanks @thexande for the issue. The enzyme tests failing is a known issue: https://github.com/infinitered/ignite/issues/1098#issuecomment-313288994

Unfortunately, React Native 0.45.1 isn't supported by Enzyme, so we have to wait until they release a version that does. Hopefully soon...

**Comment by jankalfus** [comment]
This is very frustrating. As a newcomer, it almost put me off. I had to disable the precommit and prepush npm scripts. What was the reasoning behind releasing something that's broken? :) I mean, why not just use the older react native version that is supported by Enzyme? I don't mean to be rude or anything, but this is simply unacceptable for production use. I get that the boilerplate is "bleeding edge", but why not just make a stable release let's say once a month? :)

**Comment by GantMan** [comment]
@jankalfus - that's an extremely fair assessment.   We've been quite frustrated with testing and we're sorry it's fallen over onto our tools.

To give you a bit of the tour of the product, we're in a strange place where we _need_ features from newer versions of React Native, but things like testing are having issues that we expect to be fixed fast and then aren't.  

So, in summary, I think you're right.  Sometimes we commit the engineering sin and just forget to think of the project on-boarding.  At the very least we should comment out the tests with a friendly note. 

If you'd like to take a shot at it with a PR, we'd happily accept it.  If not, I'll take it on.  Let me know 👍

**Comment by jankalfus** [comment]
@GantMan I see. Sometimes you gotta do, what you gotta do :)

I created the PR. Hopefully, it's fine this way.
