### ISSUE TITLE
[CPAT React16] npm test fails in just ignited project because of warnings 

### ISSUE THREAD

**Issue by l1br3** [infinitered/ignite#1126]
---
What's going on?
`npm test` fails.  

Might be related ? 
https://github.com/airbnb/enzyme/issues/893

**errors**
```
libre@libre:~/dev/ignited3$ npm test  

> ignited3@0.0.1 test /home/libre/dev/ignited3
> jest

 PASS  Tests/Services/FixtureAPITest.js
 PASS  Tests/Redux/GithubReduxTest.js
 PASS  Tests/Sagas/GithubSagaTest.js
 FAIL  Tests/Components/FullButtonTest.js
  ● Test suite failed to run

    react-dom is an implicit dependency in order to support react@0.13-14. Please add the appropriate version to your devDependencies. See https://github.com/airbnb/enzyme#installation
      
      at Object.<anonymous> (node_modules/enzyme/build/react-compat.js:108:11)
      at Object.<anonymous> (node_modules/enzyme/build/Utils.js:65:20)
      at Object.<anonymous> (node_modules/enzyme/build/MountedTraversal.js:36:14)

 FAIL  Tests/Components/RoundedButtonTest.js
  ● Test suite failed to run

    react-dom is an implicit dependency in order to support react@0.13-14. Please add the appropriate version to your devDependencies. See https://github.com/airbnb/enzyme#installation
      
      at Object.<anonymous> (node_modules/enzyme/build/react-compat.js:108:11)
      at Object.<anonymous> (node_modules/enzyme/build/Utils.js:65:20)
      at Object.<anonymous> (node_modules/enzyme/build/MountedTraversal.js:36:14)

 FAIL  Tests/Components/DrawerButtonTest.js
  ● Test suite failed to run

    react-dom is an implicit dependency in order to support react@0.13-14. Please add the appropriate version to your devDependencies. See https://github.com/airbnb/enzyme#installation
      
      at Object.<anonymous> (node_modules/enzyme/build/react-compat.js:108:11)
      at Object.<anonymous> (node_modules/enzyme/build/Utils.js:65:20)
      at Object.<anonymous> (node_modules/enzyme/build/MountedTraversal.js:36:14)

 PASS  Tests/Sagas/StartupSagaTest.js
 PASS  Tests/Components/AlertMessageTest.js
  ● Console

    console.error node_modules/fbjs/lib/warning.js:35
      Warning: PropTypes has been moved to a separate package. Accessing React.PropTypes is no longer supported and will be removed completely in React 16. Use the prop-types package on npm instead. (https://fb.me/migrating-from-react-proptypes)
    console.error node_modules/react-native/Libraries/Core/ExceptionsManager.js:71
      Warning: React.createClass is no longer supported. Use a plain JavaScript class instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement. (https://fb.me/migrating-from-react-create-class)


Snapshot Summary
 › 3 snapshots written in 1 test suite.

Test Suites: 3 failed, 5 passed, 8 total
Tests:       14 passed, 14 total
Snapshots:   3 added, 3 total
Time:        4.225s
Ran all test suites.
npm ERR! Test failed.  See above for more details.

```

---
Steps to reproduce
Simply install a new app.

---
`ignite doctor` results:
```json
System
  platform           linux                                                                          
  arch               x64                                                                            
  cpu                4 cores                    Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz  
  directory          /home/libre/dev/ignited3                                                       

JavaScript
  node               7.7.4        /home/libre/.nvm/versions/node/v7.7.4/bin/node  
  npm                4.1.2        /home/libre/.nvm/versions/node/v7.7.4/bin/npm   
  yarn               0.27.5       /home/libre/.nvm/versions/node/v7.7.4/bin/yarn  

React Native
  react-native-cli   2.0.1       
  app rn version     0.45.1      

Ignite
  ignite             2.0.0        /home/libre/.nvm/versions/node/v7.7.4/bin/ignite  

Android
  java               1.8.0_131    /usr/bin/java            
  android home       -            /home/libre/Android/Sdk  

```

**Comment by l1br3** [comment]
Well, already addressed, just more referencing !

https://github.com/infinitered/ignite/issues/1083#issuecomment-314274284
