### ISSUE TITLE
QR code not in terminal output

### ISSUE THREAD

**Issue by moracabanas** [infinitered/ignite#1147]
-Hello im trying to get QR code to use in Expo App with `npm start` everything is allright but the code is not printed on windows 10 console (CMD).
I've cheched this on this react github [issue](https://github.com/react-community/create-react-native-app/issues/309), but I think is not the right place to post besides the issue is closed. 

Ignite doctor output:
```System
  platform           win32
  arch               x64
  cpu                2 cores                    Intel(R) Pentium(R) CPU G3258 @ 3.20GHz
  directory          C:\Users\morac\igniteApp

JavaScript
  node               8.4.0        C:\Program Files\nodejs\node.EXE
  npm                5.3.0        C:\Program Files\nodejs\npm.CMD
  yarn               0.27.5       C:\Program Files (x86)\Yarn\bin\yarn.CMD

React Native
  react-native-cli   2.0.1
  app rn version     0.45.1

Ignite
  ignite             2.0.0        C:\Users\morac\AppData\Roaming\npm\ignite.CMD
vvv -----[ DEBUG ]----- vvv
{ Error: not found: java
    at getNotFoundError (C:\Users\morac\AppData\Roaming\npm\node_modules\ignite-cli\node_modules\which\which.js:13:12)
    at Function.whichSync [as sync] (C:\Users\morac\AppData\Roaming\npm\node_modules\ignite-cli\node_modules\which\which.js:131:9)
    at which (C:\Users\morac\AppData\Roaming\npm\node_modules\ignite-cli\node_modules\gluegun\src\core-extensions\system-extension.js:113:22)
    at Command.module.exports [as run] (C:\Users\morac\AppData\Roaming\npm\node_modules\ignite-cli\src\commands\doctor.js:83:20)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) code: 'ENOENT' }
^^^ -----[ DEBUG ]----- ^^^```

Thanks for all.

**Comment by GantMan** [comment]
Hiya!  so you switched the boilerplate to use Create React App?

Sorry for the dumb question.  Just catching up.  We don't currently ship with CRNApp.  So we'll need to know what you did to switch.  Cheers!
