### ISSUE TITLE
ignite generate screen is naming screens ScreenScreen

### ISSUE THREAD

**Issue by nikolalsvk** [infinitered/ignite#1157]
---
What's going on?

When I do `ignite generate screen Settings` I get proper file names like this:
```
✔︎ App/Containers/SettingsScreen.js
✔︎ App/Containers/Styles/SettingsScreenStyle.js
```
But when I open `App/Containers/SettingsScreen.js` this is the class name 
```
class SettingsScreenScreen extends React.Component
```

I found [the same issue](https://github.com/infinitered/ignite/issues/1070) but it seems it's not fixed in my case

---
Steps to reproduce

1. `ignite generate screen Settings`
2. open generated screen file
3. look at the class name
---
`ignite doctor` results:

```
System
  platform           darwin
  arch               x64
  cpu                8 cores                                       Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
  directory          /Users/nikolalsvk/Documents/master/LetsMeet

JavaScript
  node               7.9.0        /usr/local/bin/node
  npm                5.4.1        /usr/local/bin/npm
  yarn               1.0.0        /usr/local/bin/yarn

React Native
  react-native-cli   2.0.1
  app rn version     0.44.2

Ignite
  ignite             2.0.0        /usr/local/bin/ignite

Android
  java               1.8.0_131    /usr/bin/java
  android home       -            /Users/nikolalsvk/Library/Android/sdk
vvv -----[ DEBUG ]----- vvv
{ Error: Command failed: xcodebuild -version
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

    at ChildProcess.exithandler (child_process.js:205:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at Pipe._handle.close [as _onclose] (net.js:510:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'xcodebuild -version',
  stderr: 'xcode-select: error: tool \'xcodebuild\' requires Xcode, but active developer directory \'/Library/Developer/CommandLineTools\' is a command line tools instance\n' }
^^^ -----[ DEBUG ]----- ^^^
```

**Comment by GantMan** [comment]
What version of Ignite?  I think this is an older issue.

you can try `ignite add ir-boilerplate` and that might grab latest plugin for generators.

**Comment by nikolalsvk** [comment]
Ignite version is 2.0.0

It works fine after doing `ignite add ir-boilerplate`, thanks!
