### ISSUE TITLE
Unexpected Character '/'

### ISSUE THREAD

**Issue by sw-yx** [infinitered/ignite#1162]
### Hey there! Ignite CLI seems to be having a problem, eh?

Welllllll, it just might be. First, search the issues to make sure it's not already
here, and if not head over to http://community.infinite.red to
get some help. If you've identified that it's really an Ignite CLI issue, then:

- Explain what's going on and preferably how to replicate the issue (bonus points for a repro app)
- Run `ignite doctor` and paste the result below, including the lines with 3 backticks
- Delete these instructions! We don't want to look at them. ;)

---
What's going on?

unable to run `react-native run-ios`

```
Scanning 1068 folders for symlinks in /Users/swyx/Desktop/webdev/fullstacksr/PizzaApp/node_modules (13ms)
Found Xcode project PizzaApp.xcodeproj
CoreData: annotation:  Failed to load optimized model at path '/Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/Frameworks/InstrumentsPackaging.framework/Versions/A/Resources/XRPackageModel.momd/XRPackageModel 9.0.omo'
We couldn't boot your defined simulator due to an already booted simulator. We are limited to one simulator launched at a time.
Launching iPhone 6 (iOS 11.0)...
Building using "xcodebuild -project PizzaApp.xcodeproj -configuration Debug -scheme PizzaApp -destination id=BC368208-C2FF-4EF3-A1A2-5995444A8F6F -derivedDataPath build"
User defaults from command line:

    IDEDerivedDataPathOverride = /Users/swyx/Desktop/webdev/fullstacksr/PizzaApp/ios/build


2017-09-20 23:09:50.066 xcodebuild[9036:88494] Error Domain=NSCocoaErrorDomain Code=3840 "Unexpected character / at line 1" UserInfo={NSDebugDescription=Unexpected character / at line 1, kCFPropertyListOldStyleParsingError=Error Domain=NSCocoaErrorDomain Code=3840 "Expected terminating '}' for dictionary at line 35" UserInfo={NSDebugDescription=Expected terminating '}' for dictionary at line 35}}

xcodebuild: error: Unable to read project 'PizzaApp.xcodeproj'.
	Reason: Project /Users/swyx/Desktop/webdev/fullstacksr/PizzaApp/ios/PizzaApp.xcodeproj cannot be opened because the project file cannot be parsed.



Installing build/Build/Products/Debug-iphonesimulator/PizzaApp.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/PizzaApp.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist
```

---
Steps to reproduce

run `react-native run-ios`

---
`ignite doctor` results:

```
System
  platform           darwin
  arch               x64
  cpu                4 cores                                           Intel(R) Core(TM) i7-4650U CPU @ 1.70GHz
  directory          /Users/swyx/Desktop/webdev/fullstacksr/PizzaApp

JavaScript
  node               8.4.0        /Users/swyx/.nvm/versions/node/v8.4.0/bin/node
  npm                5.3.0        /Users/swyx/.nvm/versions/node/v8.4.0/bin/npm
  yarn               0.27.5       /usr/local/bin/yarn

React Native
  react-native-cli   2.0.1
  app rn version     0.48.3

Ignite
  ignite             2.0.0        /Users/swyx/.nvm/versions/node/v8.4.0/bin/ignite
vvv -----[ DEBUG ]----- vvv
{ Error: Command failed: java -version 2>&1

    at ChildProcess.exithandler (child_process.js:270:12)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
    at Socket.stream.socket.on (internal/child_process.js:348:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:545:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'java -version 2>&1',
  stderr: '' }
^^^ -----[ DEBUG ]----- ^^^
```

**Comment by GantMan** [comment]
try 
```shell
rm -rf node_modules && yarn
cd android
./gradlew clean
```

**Comment by sw-yx** [comment]
i did try that (and fyi i am targeting iOS for now) but no luck.

**Comment by GantMan** [comment]
I'm honestly kinda stuck.  This happens only on ignited apps?

**Comment by sw-yx** [comment]
yeah. I'll come back again if I have time  but unfortunately i hav eno more time to debug right now. closing. thanks for your attention.

**Comment by GantMan** [comment]
Sorry @sw-yx - if I can recreate the issue I will fix it.

**Comment by sw-yx** [comment]
thanks and if i get time to recreate i will reopen. frankly `ignite` is too "heavy" for me to adopt right now and people might benefit from an "ignite-lite"
