### ISSUE TITLE
Errors and warnings when using ignite new <...>

### ISSUE THREAD

**Issue by monotv** [infinitered/ignite#1172]
What's going on?
```
-----------------------------------------------
  (                  )   (
  )\ )   (        ( /(   )\ )    *   )
 (()/(   )\ )     )\()) (()/(  ` )  /(   (
  /(_)) (()/(    ((_)\   /(_))  ( )(_))  )\
 (_))    /(_))_   _((_) (_))   (_(_())  ((_)
 |_ _|  (_)) __| | \| | |_ _|  |_   _|  | __|
  | |     | (_ | | .` |  | |     | |    | _|
 |___|     \___| |_|\_| |___|    |_|    |___|
-----------------------------------------------

An unfair headstart for your React Native apps.
https://infinite.red/ignite

-----------------------------------------------
🔥 igniting app AppName
✔ using the Infinite Red boilerplate v2 (code name 'Andross')
✔ added React Native 0.49.3
? Would you like Ignite Development Screens? Yes
? What vector icon library will you use? react-native-vector-icons
? What internationalization library will you use? react-native-i18n
? What animation library will you use? react-native-animatable
✔ added ignite-ir-boilerplate
(node:45727) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: template not found /Users/path/to/code/AppName/AppName/node_modules/ignite-ir-boilerplate/templates/examples/RowExample.js.ejs.ejs
(node:45727) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:45727) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: template not found /Users/path/to/code/AppName/AppName/node_modules/ignite-ir-boilerplate/templates/examples/Styles/RowExampleStyle.js.ejs.ejs
(node:45727) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): Error: template not found /Users/path/to/code/AppName/AppName/node_modules/ignite-ir-boilerplate/templates/examples/GridExample.js.ejs.ejs
(node:45727) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): Error: template not found /Users/path/to/code/AppName/AppName/node_modules/ignite-ir-boilerplate/templates/examples/Styles/GridExampleStyle.js.ejs.ejs
(node:45727) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 5): Error: template not found /Users/path/to/code/AppName/AppName/node_modules/ignite-ir-boilerplate/templates/examples/SectionExample.js.ejs.ejs
(node:45727) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 6): Error: template not found /Users/path/to/code/AppName/AppName/node_modules/ignite-ir-boilerplate/templates/examples/Styles/SectionExampleStyle.js.ejs.ejs
✖ /Users/path/to/code/AppName/AppName/node_modules/ignite-dev-screens@"~>2.2.0"/plugin.js does not exist.  skipping.
✖ /Users/path/to/code/AppName/AppName/node_modules/ignite-vector-icons@"~>1.0.0"/plugin.js does not exist.  skipping.
✖ /Users/path/to/code/AppName/AppName/node_modules/ignite-i18n@"~>1.0.0"/plugin.js does not exist.  skipping.
✖ /Users/path/to/code/AppName/AppName/node_modules/ignite-animatable@"~>1.0.0"/plugin.js does not exist.  skipping.
✖ /Users/path/to/code/AppName/AppName/node_modules/ignite-standard@"~>1.0.0"/plugin.js does not exist.  skipping.
✔ configured git
✔ ignited AppName in 1800.46s
```

I think these errors and warnings should not appear when creating a new app. Also the path looks messed up with the double app name, which probably causes the errors and warnings.

Steps to reproduce
`ignite new AppName -b ignite-ir-boilerplate`, answer yes and select the default libs.

`ignite doctor` results:
```
System
  platform           darwin
  arch               x64
  cpu                8 cores                      Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
  directory          /Users/path/to/code

JavaScript
  node               7.6.0        /usr/local/opt/nvm/versions/node/v7.6.0/bin/node
  npm                4.1.2        /usr/local/opt/nvm/versions/node/v7.6.0/bin/npm
  yarn               -            null

React Native
  react-native-cli   2.0.1

Ignite
  ignite             2.0.0-beta.3   /usr/local/opt/nvm/versions/node/v7.6.0/bin/ignite

Android
  java               1.8.0_101    /usr/bin/java
  android home       -            /Development/3rdparty/android-sdk

iOS
  xcode              8.3.2
```

**Comment by robinheinze** [comment]
Hmm, it's working for me, here's my output. It looks like you're running an old beta version of ignite-cli, which is on 2.0.0 now, so that may be contributing to your issue.

```
~/Code/ir/internal/playground🐳  ignite new RocketMan --max
-----------------------------------------------
  (                  )   (
  )\ )   (        ( /(   )\ )    *   )
 (()/(   )\ )     )\()) (()/(  ` )  /(   (
  /(_)) (()/(    ((_)\   /(_))  ( )(_))  )\
 (_))    /(_))_   _((_) (_))   (_(_())  ((_)
 |_ _|  (_)) __| | \| | |_ _|  |_   _|  | __|
  | |     | (_ | | .` |  | |     | |    | _|
 |___|     \___| |_|\_| |___|    |_|    |___|
-----------------------------------------------

An unfair headstart for your React Native apps.
https://infinite.red/ignite

-----------------------------------------------

🔥 igniting app RocketMan
✔ using the Infinite Red boilerplate v2 (code name 'Andross')
✔ added React Native 0.49.3 in 23.77s
✔ added ignite-ir-boilerplate in 20.08s
✔ added ignite-dev-screens in 28.71s
✔ added ignite-vector-icons in 16.19s
✔ added ignite-i18n in 15.74s
✔ added ignite-animatable in 13.39s
✔ added ignite-standard in 68.08s
✔ configured git
✔ ignited RocketMan in 193.25s

    Ignite CLI ignited RocketMan in 193.25s

    To get started:

      cd RocketMan
      react-native run-ios
      react-native run-android
      ignite --help

    Read the walkthrough at https://github.com/infinitered/ignite-ir-boilerplate/blob/master/readme.md#boilerplate-walkthrough

    Need additional help? Join our Slack community at http://community.infinite.red.

    Now get cooking! 🍽

~/Code/ir/internal/playground🐳  ignite doctor
System
  platform           darwin
  arch               x64
  cpu                8 cores                                          Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
  directory          /Users/robinheinze/Code/ir/internal/playground

JavaScript
  node               8.6.0        /usr/local/bin/node
  npm                5.4.2        /usr/local/bin/npm
  yarn               1.1.0        /usr/local/bin/yarn

React Native
  react-native-cli   2.0.1

Ignite
  ignite             2.0.0        /usr/local/bin/ignite

Android
  java               1.8.0_121    /usr/bin/java
  android home       -            /Users/robinheinze/Library/Android/sdk

iOS
  xcode              9.0
```

**Comment by monotv** [comment]
@robinheinze you are correct sir, thanks for your help!

**Comment by robinheinze** [comment]
Awesome! Glad that worked.

**Comment by rubenvde** [comment]
It's crashing on the same file again when I try the Bowser option. The 'Andross' option is working. Maybe it's because it's in alpha but I couldn't get it to work.

```  
(                  )   (                   
  )\ )   (        ( /(   )\ )    *   )       
 (()/(   )\ )     )\()) (()/(  ` )  /(   (   
  /(_)) (()/(    ((_)\   /(_))  ( )(_))  )\  
 (_))    /(_))_   _((_) (_))   (_(_())  ((_) 
 |_ _|  (_)) __| | \| | |_ _|  |_   _|  | __|
  | |     | (_ | | .` |  | |     | |    | _| 
 |___|     \___| |_|\_| |___|    |_|    |___|
-----------------------------------------------

An unfair headstart for your React Native apps.
https://infinite.red/ignite

-----------------------------------------------

🔥 igniting app RocketMan
? Which boilerplate would you like to use? Bowser (alpha) (React Navigation, MobX State Tree, & TypeScript)
✔ using the Infinite Red boilerplate v3 (code name 'Bowser')
✔ added React Native 0.55.1 in 52.49s
✔ added ignite-ir-boilerplate-bowser in 74.11s
(node:5247) UnhandledPromiseRejectionWarning: Error: template not found /Users/path/to/dir/RocketMan/RocketMan/node_modules/ignite-ir-boilerplate-bowser/templates/examples/RowExample.js.ejs
    at Object.generate (/usr/local/lib/node_modules/ignite-cli/node_modules/gluegun/src/core-extensions/template-extension.js:51:13)
    at fileName (/usr/local/lib/node_modules/ignite-cli/src/extensions/ignite/addPluginScreenExamples.js:57:20)
    at _map (/usr/local/lib/node_modules/ignite-cli/node_modules/ramda/src/internal/_map.js:6:19)
    at map (/usr/local/lib/node_modules/ignite-cli/node_modules/ramda/src/map.js:57:14)
    at /usr/local/lib/node_modules/ignite-cli/node_modules/ramda/src/internal/_dispatchable.js:39:15
    at f2 (/usr/local/lib/node_modules/ignite-cli/node_modules/ramda/src/internal/_curry2.js:25:16)
    at Object.addPluginScreenExamples (/usr/local/lib/node_modules/ignite-cli/src/extensions/ignite/addPluginScreenExamples.js:45:7)
    at Object.add (/Users/path/to/dir/RocketMan/RocketMan/node_modules/ignite-ir-boilerplate-bowser/screenExamples.js:26:24)
    at Object.add (/Users/path/to/dir/RocketMan/RocketMan/node_modules/ignite-ir-boilerplate-bowser/plugin.js:9:24)
    at Command.module.exports [as run] (/usr/local/lib/node_modules/ignite-cli/src/commands/add.js:139:28)
(node:5247) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:5247) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:5247) UnhandledPromiseRejectionWarning: Error: template not found /Users/path/to/dir/RocketMan/RocketMan/node_modules/ignite-ir-boilerplate-bowser/templates/examples/Styles/RowExampleStyle.js.ejs
    at Object.generate (/usr/local/lib/node_modules/ignite-cli/node_modules/gluegun/src/core-extensions/template-extension.js:51:13)
    at fileName (/usr/local/lib/node_modules/ignite-cli/src/extensions/ignite/addPluginScreenExamples.js:57:20)
    at _map (/usr/local/lib/node_modules/ignite-cli/node_modules/ramda/src/internal/_map.js:6:19)
    at map (/usr/local/lib/node_modules/ignite-cli/node_modules/ramda/src/map.js:57:14)
    at /usr/local/lib/node_modules/ignite-cli/node_modules/ramda/src/internal/_dispatchable.js:39:15
    at f2 (/usr/local/lib/node_modules/ignite-cli/node_modules/ramda/src/internal/_curry2.js:25:16)
    at Object.addPluginScreenExamples (/usr/local/lib/node_modules/ignite-cli/src/extensions/ignite/addPluginScreenExamples.js:45:7)
    at Object.add (/Users/path/to/dir/RocketMan/RocketMan/node_modules/ignite-ir-boilerplate-bowser/screenExamples.js:26:24)
    at Object.add (/Users/path/to/dir/RocketMan/RocketMan/node_modules/ignite-ir-boilerplate-bowser/plugin.js:9:24)
    at Command.module.exports [as run] (/usr/local/lib/node_modules/ignite-cli/src/commands/add.js:139:28)
(node:5247) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:5247) UnhandledPromiseRejectionWarning: Error: template not found /Users/path/to/dir/RocketMan/RocketMan/node_modules/ignite-ir-boilerplate-bowser/templates/examples/GridExample.js.ejs
    at Object.generate (/usr/local/lib/node_modules/ignite-cli/node_modules/gluegun/src/core-extensions/template-extension.js:51:13)
    at fileName (/usr/local/lib/node_modules/ignite-cli/src/extensions/ignite/addPluginScreenExamples.js:57:20)
    at _map (/usr/local/lib/node_modules/ignite-cli/node_modules/ramda/src/internal/_map.js:6:19)
    at map (/usr/local/lib/node_modules/ignite-cli/node_modules/ramda/src/map.js:57:14)
    at /usr/local/lib/node_modules/ignite-cli/node_modules/ramda/src/internal/_dispatchable.js:39:15
    at f2 (/usr/local/lib/node_modules/ignite-cli/node_modules/ramda/src/internal/_curry2.js:25:16)
    at Object.addPluginScreenExamples (/usr/local/lib/node_modules/ignite-cli/src/extensions/ignite/addPluginScreenExamples.js:45:7)
    at Object.add (/Users/path/to/dir/RocketMan/RocketMan/node_modules/ignite-ir-boilerplate-bowser/screenExamples.js:26:24)
    at Object.add (/Users/path/to/dir/RocketMan/RocketMan/node_modules/ignite-ir-boilerplate-bowser/plugin.js:9:24)
    at Command.module.exports [as run] (/usr/local/lib/node_modules/ignite-cli/src/commands/add.js:139:28)
(node:5247) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:5247) UnhandledPromiseRejectionWarning: Error: template not found /Users/path/to/dir/RocketMan/RocketMan/node_modules/ignite-ir-boilerplate-bowser/templates/examples/Styles/GridExampleStyle.js.ejs
    at Object.generate (/usr/local/lib/node_modules/ignite-cli/node_modules/gluegun/src/core-extensions/template-extension.js:51:13)
    at fileName (/usr/local/lib/node_modules/ignite-cli/src/extensions/ignite/addPluginScreenExamples.js:57:20)
    at _map (/usr/local/lib/node_modules/ignite-cli/node_modules/ramda/src/internal/_map.js:6:19)
    at map (/usr/local/lib/node_modules/ignite-cli/node_modules/ramda/src/map.js:57:14)
    at /usr/local/lib/node_modules/ignite-cli/node_modules/ramda/src/internal/_dispatchable.js:39:15
    at f2 (/usr/local/lib/node_modules/ignite-cli/node_modules/ramda/src/internal/_curry2.js:25:16)
    at Object.addPluginScreenExamples (/usr/local/lib/node_modules/ignite-cli/src/extensions/ignite/addPluginScreenExamples.js:45:7)
    at Object.add (/Users/path/to/dir/RocketMan/RocketMan/node_modules/ignite-ir-boilerplate-bowser/screenExamples.js:26:24)
    at Object.add (/Users/path/to/dir/RocketMan/RocketMan/node_modules/ignite-ir-boilerplate-bowser/plugin.js:9:24)
    at Command.module.exports [as run] (/usr/local/lib/node_modules/ignite-cli/src/commands/add.js:139:28)
(node:5247) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:5247) UnhandledPromiseRejectionWarning: Error: template not found /Users/path/to/dir/RocketMan/RocketMan/node_modules/ignite-ir-boilerplate-bowser/templates/examples/SectionExample.js.ejs
    at Object.generate (/usr/local/lib/node_modules/ignite-cli/node_modules/gluegun/src/core-extensions/template-extension.js:51:13)
    at fileName (/usr/local/lib/node_modules/ignite-cli/src/extensions/ignite/addPluginScreenExamples.js:57:20)
    at _map (/usr/local/lib/node_modules/ignite-cli/node_modules/ramda/src/internal/_map.js:6:19)
    at map (/usr/local/lib/node_modules/ignite-cli/node_modules/ramda/src/map.js:57:14)
    at /usr/local/lib/node_modules/ignite-cli/node_modules/ramda/src/internal/_dispatchable.js:39:15
    at f2 (/usr/local/lib/node_modules/ignite-cli/node_modules/ramda/src/internal/_curry2.js:25:16)
    at Object.addPluginScreenExamples (/usr/local/lib/node_modules/ignite-cli/src/extensions/ignite/addPluginScreenExamples.js:45:7)
    at Object.add (/Users/path/to/dir/RocketMan/RocketMan/node_modules/ignite-ir-boilerplate-bowser/screenExamples.js:26:24)
    at Object.add (/Users/path/to/dir/RocketMan/RocketMan/node_modules/ignite-ir-boilerplate-bowser/plugin.js:9:24)
    at Command.module.exports [as run] (/usr/local/lib/node_modules/ignite-cli/src/commands/add.js:139:28)
(node:5247) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
(node:5247) UnhandledPromiseRejectionWarning: Error: template not found /Users/path/to/dir/RocketMan/RocketMan/node_modules/ignite-ir-boilerplate-bowser/templates/examples/Styles/SectionExampleStyle.js.ejs
    at Object.generate (/usr/local/lib/node_modules/ignite-cli/node_modules/gluegun/src/core-extensions/template-extension.js:51:13)
    at fileName (/usr/local/lib/node_modules/ignite-cli/src/extensions/ignite/addPluginScreenExamples.js:57:20)
    at _map (/usr/local/lib/node_modules/ignite-cli/node_modules/ramda/src/internal/_map.js:6:19)
    at map (/usr/local/lib/node_modules/ignite-cli/node_modules/ramda/src/map.js:57:14)
    at /usr/local/lib/node_modules/ignite-cli/node_modules/ramda/src/internal/_dispatchable.js:39:15
    at f2 (/usr/local/lib/node_modules/ignite-cli/node_modules/ramda/src/internal/_curry2.js:25:16)
    at Object.addPluginScreenExamples (/usr/local/lib/node_modules/ignite-cli/src/extensions/ignite/addPluginScreenExamples.js:45:7)
    at Object.add (/Users/path/to/dir/RocketMan/RocketMan/node_modules/ignite-ir-boilerplate-bowser/screenExamples.js:26:24)
    at Object.add (/Users/path/to/dir/RocketMan/RocketMan/node_modules/ignite-ir-boilerplate-bowser/plugin.js:9:24)
    at Command.module.exports [as run] (/usr/local/lib/node_modules/ignite-cli/src/commands/add.js:139:28)
(node:5247) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)
✔ configured git
✔ ignited RocketMan in 129.87s
```

This is what I get when I try ```ignite doctor```:
```
System
  platform           darwin                                                                                            
  arch               x64                                                                                               
  cpu                4 cores                                       Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz  
  directory          /Users/path/to/dir/                                                  

JavaScript
  node               10.0.0       /usr/local/bin/node  
  npm                6.0.0        /usr/local/bin/npm   
  yarn               1.6.0        /usr/local/bin/yarn  

React Native
  react-native-cli   2.0.1       

Ignite
  ignite             2.1.0        /usr/local/bin/ignite  

Android
  java               1.8.0_144    /usr/bin/java  
  android home       -            undefined      

iOS
  xcode              9.3      
```

**Comment by GantMan** [comment]
@carlinisaacson and @kevinvangelder - can you look into this please?

**Comment by robinheinze** [comment]
@GantMan I think was fixed with my last PR. We just have to release a new version of the boilerplate.
