### ISSUE TITLE
Unexpected linter output Error

### ISSUE THREAD

**Issue by darioajr** [infinitered/ignite#1283]
"babel-eslint": "7.1.1",
"standard": "10.0.2",
"lint": "standard --verbose | snazzy"
Mac OS 10.13.4
Node v9.11.1
Npm 5.6.0

npm run lint -s

standard: Unexpected linter output:

RangeError: Line number out of range (line 11 requested, but only 10 lines present).
at SourceCode.getIndexFromLoc (/Users/dario/Documents/srm-app/node_modules/eslint/lib/util/source-code.js:389:19)
at Object.fix (/Users/dario/Documents/srm-app/node_modules/eslint/lib/rules/no-multiple-empty-lines.js:116:52)
at RuleContext.report (/Users/dario/Documents/srm-app/node_modules/eslint/lib/rule-context.js:127:34)
at Program:exit.allLines.reduce.concat.reduce (/Users/dario/Documents/srm-app/node_modules/eslint/lib/rules/no-multiple-empty-lines.js:108:37)
at Array.reduce ()
at EventEmitter.Program:exit (/Users/dario/Documents/srm-app/node_modules/eslint/lib/rules/no-multiple-empty-lines.js:93:22)
at EventEmitter.emit (events.js:185:15)
at NodeEventGenerator.applySelector (/Users/dario/Documents/srm-app/node_modules/eslint/lib/util/node-event-generator.js:265:26)
at NodeEventGenerator.applySelectors (/Users/dario/Documents/srm-app/node_modules/eslint/lib/util/node-event-generator.js:294:22)
at NodeEventGenerator.leaveNode (/Users/dario/Documents/srm-app/node_modules/eslint/lib/util/node-event-generator.js:317:14)

**Comment by mlaco** [comment]
Hi @darioajr sorry for the (very) delayed response. Did you manage to solve the problem? I'm going to close this since old issues are often abandoned, but please do open another if you're still having problems. If you do, please include the output of `ignite doctor`,  and let us know what command you were trying to run. Thanks!

**Comment by darioajr** [comment]
Hi, I fixed this project, updating versions.
