### ISSUE TITLE
Bowser boiler doesnt compile.

### ISSUE THREAD

**Issue by mikecann** [infinitered/ignite#1293]
What's going on?

Following the guide listed in the Readme.md then doing `yarn compile` I get the following errors:

```
src/navigation/example-navigator.ts:1:10 - error TS2305: Module '"/Users/mike.cann/dev/bam/experiments/PizzaApp/node_modules/@types/react-navigation/index"' has no exported member 'createStackNavigator'.

1 import { createStackNavigator } from "react-navigation"
           ~~~~~~~~~~~~~~~~~~~~


src/navigation/root-navigator.ts:1:10 - error TS2305: Module '"/Users/mike.cann/dev/bam/experiments/PizzaApp/node_modules/@types/react-navigation/index"' has no exported member 'createStackNavigator'.

1 import { createStackNavigator } from "react-navigation"
           ~~~~~~~~~~~~~~~~~~~~


src/navigation/stateful-navigator.tsx:5:1 - error TS6133: 'throttle' is declared but its value is never read.

5 import throttle from "lodash.throttle"
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

---
Steps to reproduce

1) `ignite new PizzaApp`
  ( Choose `Bowser (alpha)` when prompted )
2) `cd PizzaApp`
3) `yarn compile`

---
`ignite doctor` results:

```
System
  platform           darwin
  arch               x64
  cpu                8 cores                                         Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  directory          /Users/mike.cann/dev/bam/experiments/PizzaApp

JavaScript
  node               8.11.1       /Users/mike.cann/.nvm/versions/node/v8.11.1/bin/node
  npm                5.6.0        /Users/mike.cann/.nvm/versions/node/v8.11.1/bin/npm
  yarn               1.7.0        /usr/local/bin/yarn

React Native
  react-native-cli   2.0.1
  app rn version     0.55.4

Ignite
  ignite             2.1.0        /Users/mike.cann/.nvm/versions/node/v8.11.1/bin/ignite
vvv -----[ DEBUG ]----- vvv
{ Error: Command failed: java -version 2>&1

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'java -version 2>&1',
  stderr: '' }
^^^ -----[ DEBUG ]----- ^^^
```

**Comment by fadeojo** [comment]
@mikecann what version of `@types/react-navigation` is installed ?

**Comment by mikecann** [comment]
@fadeojo We decided not to go with Ignite in the end but to help you debug. This is the package.json, its basically just the Pizza app taken from your guide: 

```
{
  "name": "PizzaApp",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest",
    "compile": "tsc --noEmit -p . --pretty",
    "format": "npm-run-all format:*",
    "format:js": "prettier --write {.,**}/*.js",
    "format:json": "prettier --write {.,**}/*.json",
    "format:md": "prettier --write {.,**}/*.md",
    "format:ts": "prettier --write {.,**}/*.{ts,tsx} && tslint --fix -p .",
    "lint": "npm-run-all lint:*",
    "lint:ts": "tslint -p .",
    "postinstall": "solidarity",
    "hack:types-react-navigation": "rimraf node_modules/@types/react-navigation/node_modules/@types",
    "hack:types-react-native": "rimraf node_modules/@types/react-native/node_modules/@types",
    "hack:types-react-test-renderer": "rimraf node_modules/@types/react-test-renderer/node_modules/@types",
    "patch": "patch-package",
    "prepare": "npm-run-all patch hack:*",
    "storybook": "storybook start -p 9001 --skip-packager",
    "ios": "react-native run-ios"
  },
  "dependencies": {
    "apisauce": "0.14.3",
    "lodash.throttle": "4.1.1",
    "mobx": "4.2.1",
    "mobx-react": "5.1.2",
    "mobx-state-tree": "2.0.5",
    "ramda": "0.25.0",
    "react": "16.3.1",
    "react-native": "0.55.4",
    "react-native-i18n": "2.0.12",
    "react-native-keychain": "3.0.0-rc.3",
    "react-native-splash-screen": "3.0.6",
    "react-navigation": "2.0.4",
    "reactotron-mst": "2.0.0-beta.2",
    "reactotron-react-native": "2.0.0-beta.2",
    "validate.js": "0.12.0"
  },
  "devDependencies": {
    "@storybook/addon-storyshots": "github:infinitered/addon-storyshots",
    "@storybook/react-native": "3.4.3",
    "@types/jest": "22.2.3",
    "@types/ramda": "0.25.28",
    "@types/react": "16.0.40",
    "@types/react-native": "0.55.12",
    "@types/react-navigation": "1.5.2",
    "@types/react-test-renderer": "16.0.1",
    "@types/validate.js": "0.11.0",
    "babel-jest": "23.2.0",
    "babel-plugin-transform-inline-environment-variables": "0.4.1",
    "babel-preset-react-native": "4.0.0",
    "ignite-ir-boilerplate-bowser": "^1.0.0-alpha.8",
    "jest": "23.2.0",
    "jest-preset-ignite": "0.5.0",
    "npm-run-all": "4.1.3",
    "patch-package": "5.1.1",
    "postinstall-prepare": "1.0.1",
    "prettier": "1.12.1",
    "react-dom": "16.2.0",
    "react-native-typescript-transformer": "1.2.5",
    "react-powerplug": "0.1.5",
    "react-test-renderer": "16.3.1",
    "rimraf": "2.6.2",
    "solidarity": "2.1.0",
    "tslint": "5.10.0",
    "tslint-config-prettier": "1.12.0",
    "typescript": "2.8.3"
  },
  "jest": {
    "preset": "jest-preset-ignite"
  },
  "rnpm": {
    "assets": [
      "./src/theme/fonts/"
    ]
  }
}

```

**Comment by fadeojo** [comment]
@mikecann you need to upgrade `"@types/react-navigation": "1.5.2"` to v2. I think you should reconsider ignite. The infinite-red team are very solid OSS maintainers and I can vouch for their design decisions. You should re-consider ignite. You can find me as `@fadeojo` on the infinite-red Slack.

**Comment by mikecann** [comment]
thanks @fadeojo but its too late for us, we have already gone too far down the ejected CRA route now but we may reconsider for a future project. Thanks again.
