### ISSUE TITLE
Ignite Bowser + NativeBase: Error: Cannot find module 'C:\...\npm-cache\_cacache\scripts\prepare.js'

### ISSUE THREAD

**Issue by Kamaropoulos** [infinitered/ignite#1305]
### Hey there! Ignite CLI seems to be having a problem, eh?

Welllllll, it just might be. First, search the issues to make sure it's not already
here, and if not head over to http://community.infinite.red to
get some help. If you've identified that it's really an Ignite CLI issue, then:

- Explain what's going on and preferably how to replicate the issue (bonus points for a repro app)
- Run `ignite doctor` and paste the result below, including the lines with 3 backticks
- Delete these instructions! We don't want to look at them. ;)

---
What's going on?

So I just started looking into Ignite and React Native in general. I grabbed the Bowser boilerplate, created a screen and a few models and I installed nativebase to start working on the screens. But the problem is that right after I installed it, the Metro packager started complaining about some missing packages and it sais to do remove the node_modules directory, run `npm install` again and do some more cleanup. I tried installing the missing packages manually with no luck so I finally did what it said. And now I'm getting the following error log when trying to run `npm install`:

```
npm WARN deprecated @types/validate.js@0.11.0: This is a stub types definition for Validate.js (https://github.com/ansman/validate.js). Validate.js provides its own type definitions, so you don't need @types/validate.js installed!
npm ERR! prepareGitDep 1>
npm ERR! prepareGitDep > uglifyjs-webpack-plugin@0.4.6 postinstall C:\Users\<Username>\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-b667c3b6\node_modules\webpack\node_modules\uglifyjs-webpack-plugin
npm ERR! prepareGitDep > node lib/post_install.js
npm ERR! prepareGitDep
npm ERR! prepareGitDep
npm ERR! prepareGitDep > @storybook/addon-storyshots@3.4.3 prepare C:\Users\<Username>\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-b667c3b6
npm ERR! prepareGitDep > node ../../scripts/prepare.js
npm ERR! prepareGitDep
npm ERR! prepareGitDep
npm ERR! prepareGitDep 2> npm WARN install Usage of the `--dev` option is deprecated. Use `--only=dev` instead.
npm ERR! prepareGitDep npm WARN deprecated array.prototype.flatten@1.2.1: This method has been renamed to "flat" - please use `array.prototype.flat` instead
npm ERR! prepareGitDep npm WARN deprecated browserslist@2.11.3: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm ERR! prepareGitDep npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm ERR! prepareGitDep module.js:545
npm ERR! prepareGitDep     throw err;
npm ERR! prepareGitDep     ^
npm ERR! prepareGitDep
npm ERR! prepareGitDep Error: Cannot find module 'C:\Users\<Username>\AppData\Roaming\npm-cache\_cacache\scripts\prepare.js'
npm ERR! prepareGitDep     at Function.Module._resolveFilename (module.js:543:15)
npm ERR! prepareGitDep     at Function.Module._load (module.js:470:25)
npm ERR! prepareGitDep     at Function.Module.runMain (module.js:690:10)
npm ERR! prepareGitDep     at startup (bootstrap_node.js:194:16)
npm ERR! prepareGitDep     at bootstrap_node.js:666:3
npm ERR! prepareGitDep npm ERR! code ELIFECYCLE
npm ERR! prepareGitDep npm ERR! errno 1
npm ERR! prepareGitDep npm ERR! @storybook/addon-storyshots@3.4.3 prepare: `node ../../scripts/prepare.js`
npm ERR! prepareGitDep npm ERR! Exit status 1
npm ERR! prepareGitDep npm ERR!
npm ERR! prepareGitDep npm ERR! Failed at the @storybook/addon-storyshots@3.4.3 prepare script.
npm ERR! prepareGitDep npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! prepareGitDep
npm ERR! prepareGitDep npm ERR! A complete log of this run can be found in:
npm ERR! prepareGitDep npm ERR!     C:\Users\<Username>\AppData\Roaming\npm-cache\_logs\2018-07-28T13_32_08_365Z-debug.log
npm ERR! prepareGitDep
npm ERR! code ENOPACKAGEJSON
npm ERR! package.json Non-registry package missing package.json: @storybook/addon-storyshots@github:infinitered/addon-storyshots.
npm ERR! package.json npm can't find a package.json file in your current directory.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\<Username>\AppData\Roaming\npm-cache\_logs\2018-07-28T13_32_10_476Z-debug.log
```
---
Steps to reproduce

- Clone my Todo demo app attempt from https://github.com/Kamaropoulos/ToDoMore-Frontend
- CD into the directory
- Run `npm install`

---
`ignite doctor` results:

```
System
  platform           win32
  arch               x64
  cpu                8 cores                                  AMD FX(tm)-8350 Eight-Core Processor
  directory          C:\Projects\ToDoMore\ToDoMore-Frontend

JavaScript
  node               9.8.0        C:\Program Files\nodejs\node.EXE
  npm                6.2.0        C:\Program Files\nodejs\npm.CMD
  yarn               1.5.1        C:\Program Files (x86)\Yarn\bin\yarn.CMD

React Native
  react-native-cli   2.0.1

Ignite
  ignite             2.1.1        C:\Users\<Username>\AppData\Roaming\npm\ignite.CMD

Android
  java               -            C:\ProgramData\Oracle\Java\javapath\java.EXE
  android home       -            C:\Users\<Username>\AppData\Local\Android\Sdk
```

**Comment by adrienthiery** [comment]
Hi @Kamaropoulos ,

Does it happen if you restart a new project from the boilerplate in another folder ? Like `ignite new TodoMore-Frontend-test/ -b ir-boilerplate-bowser` ?

**Comment by derekdon** [comment]
Tried and see the same on a mac.

**Comment by david-martyn-ford** [comment]
Also have the same issue when starting bowser boilerplate from scratch.

OS: `Windows 10 Pro 1803`
Ignite version: `2.1.2`
Node: `v10.6.0`
Npm: `6.1.0`

**Comment by rubenvde** [comment]
```
System
  platform           darwin
  arch               x64
  cpu                8 cores                                   Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
  directory          /Users/username/Desktop/test

JavaScript
  node               8.11.2       /Users/username/.nvm/versions/node/v8.11.2/bin/node
  npm                5.6.0        /Users/username/.nvm/versions/node/v8.11.2/bin/npm
  yarn               1.7.0        /usr/local/bin/yarn

React Native
  react-native-cli   2.0.1

Ignite
  ignite             2.1.2        /Users/username/.nvm/versions/node/v8.11.2/bin/ignite

Android
  java               1.8.0_162    /usr/bin/java
  android home       -            /Users/username/Library/Android/sdk

iOS
  xcode              10.0
```

Got the same issue here

**Comment by elirangoshen** [comment]
I just had this issue and I solve it by copying the node-modules dir from a fresh bower install.
you can merge it as well so if you install native base it should still be there.

**Comment by jamonholmgren** [comment]
@Kamaropoulos Is this still happening for you?

**Comment by Kamaropoulos** [comment]
@jamonholmgren honestly, I don't know, it's been a while since I last touched it and I don't even remember how it ended up 😂
I'll check later today and let you know :)

**Comment by jamonholmgren** [comment]
Sounds good @Kamaropoulos ! Let us know if we can help.
