### ISSUE TITLE
(Fresh install) bundling failed: Error: Unable to resolve module `seamless-immutable` 

### ISSUE THREAD

**Issue by mikael-johansson** [infinitered/ignite#1314]
Am I doing something stupid? Version mismatch somewhere? I think this worked on the same machine a few months ago.

### Init
```
🔥 igniting app oaignite3
? Which boilerplate would you like to use? Andross (React Navigation, Redux, & Redux Saga
✔ using the Infinite Red boilerplate v2 (code name 'Andross')
✔ added React Native 0.55.1 in 25.62s
? Would you like Ignite Development Screens? Yes
? What vector icon library will you use? react-native-vector-icons
? What internationalization library will you use? react-native-i18n
? What animation library will you use? none
? Would you like to include redux-persist? No
✔ added ignite-ir-boilerplate-andross in 41.6s
✔ added ignite-dev-screens in 28.47s
✔ added ignite-vector-icons in 11.89s
✔ added ignite-i18n in 11.55s
✔ added ignite-standard in 24.99s
✔ configured git
✔ ignited oaignite3 in 161.64s

    Ignite CLI ignited oaignite3 in 161.64s
```

### Commands
```
cd oaignite3
echo 'sdk.dir = /Users/mikaeljo/Library/Android/sdk' > android/local.properties
react-native run-android
```

### Output
```
error: bundling failed: Error: Unable to resolve module `seamless-immutable` from `/Users/mikaeljo/git/openapp/oaignite/App/Config/ReactotronConfig.js`: Module `seamless-immutable` does not exist in the Haste module map or in these directories:
  /Users/mikaeljo/git/openapp/oaignite/node_modules

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.  4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`.
    at ModuleResolver.resolveDependency (/Users/mikaeljo/git/openapp/oaignite/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:161:1460)
    at ResolutionRequest.resolveDependency (/Users/mikaeljo/git/openapp/oaignite/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:91:16)
    at DependencyGraph.resolveDependency (/Users/mikaeljo/git/openapp/oaignite/node_modules/metro/src/node-haste/DependencyGraph.js:272:4579)
    at dependencies.map.relativePath (/Users/mikaeljo/git/openapp/oaignite/node_modules/metro/src/DeltaBundler/traverseDependencies.js:376:19)
    at Array.map (<anonymous>)
    at resolveDependencies (/Users/mikaeljo/git/openapp/oaignite/node_modules/metro/src/DeltaBundler/traverseDependencies.js:374:16)
    at /Users/mikaeljo/git/openapp/oaignite/node_modules/metro/src/DeltaBundler/traverseDependencies.js:212:33
    at Generator.next (<anonymous>)
    at step (/Users/mikaeljo/git/openapp/oaignite/node_modules/metro/src/DeltaBundler/traverseDependencies.js:297:313)
    at /Users/mikaeljo/git/openapp/oaignite/node_modules/metro/src/DeltaBundler/traverseDependencies.js:297:473

```

^^^ Tried this but didn't help.

### Doctor
```
mikaeljo@polk:~/git/openapp/oaignite3$ ignite doctor
System
  platform           darwin                                                                                       
  arch               x64                                                                                          
  cpu                8 cores                                 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz  
  directory          /Users/mikaeljo/git/openapp/oaignite3                                                        

JavaScript
  node               10.5.0       /usr/local/bin/node  
  npm                6.1.0        /usr/local/bin/npm   
  yarn               1.9.4        /usr/local/bin/yarn  

React Native
  react-native-cli   2.0.1       
  app rn version     0.55.1      

Ignite
  ignite             2.1.1        /usr/local/bin/ignite  

Android
  java               1.8.0_171    /usr/bin/java  
  android home       -            undefined      

iOS
  xcode              8.2.1       

```

**Comment by mikael-johansson** [comment]
Ok got it to work by messing around a bit. Updating react-native probably did the trick.
