### ISSUE TITLE
ignite new application fails, spins on plugin installation

### ISSUE THREAD

**Issue by robpaveza** [infinitered/ignite#1354]
---
What's going on?

From a completely clean bootstrap of `sudo npm i -g ignite-cli`, trying to bootstrap a new app using Bowser gets me a series of failing installations that I can't even Ctrl+C from:

```
roberts-mbp:projects robpaveza$ ignite new AzbsRn2019
-----------------------------------------------
  (                  )   (                   
  )\ )   (        ( /(   )\ )    *   )       
 (()/(   )\ )     )\()) (()/(  ` )  /(   (   
  /(_)) (()/(    ((_)\   /(_))  ( )(_))  )\  
 (_))    /(_))_   _((_) (_))   (_(_())  ((_) 
 |_ _|  (_)) __| | \| | |_ _|  |_   _|  | __|
  | |     | (_ | | .` |  | |     | |    | _| 
 |___|     \___| |_|\_| |___|    |_|    |___|
-----------------------------------------------

An unfair headstart for your React Native apps.
https://infinite.red/ignite

-----------------------------------------------

🔥 igniting app AzbsRn2019
? Which boilerplate would you like to use? Bowser (React Navigation, MobX State Tree, & TypeScript)
✔ using the Infinite Red boilerplate v3 (code name 'Bowser')
✔ added React Native 0.57.7 in 23.37s
✖ ignite-ir-boilerplate-bowser was not able to be installed. Is it a valid NPM module?
----------
Command failed: yarn add ignite-ir-boilerplate-bowser --dev
warning @storybook/react-native > @storybook/core > autoprefixer > browserslist@2.11.3: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning @storybook/react-native > @storybook/core > css-loader > cssnano > autoprefixer > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning @storybook/react-native > @storybook/core > css-loader > cssnano > postcss-merge-rules > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning @storybook/react-native > @storybook/core > css-loader > cssnano > postcss-merge-rules > caniuse-api > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning @types/validate.js@0.11.0: This is a stub types definition for Validate.js (https://github.com/ansman/validate.js). Validate.js provides its own type definitions, so you don't need @types/validate.js installed!
warning "metro-react-native-babel-preset > @babel/plugin-proposal-class-properties@7.2.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "metro-react-native-babel-preset > @babel/plugin-proposal-nullish-coalescing-operator@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "metro-react-native-babel-preset > @babel/plugin-proposal-object-rest-spread@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning " > @babel/plugin-proposal-optional-catch-binding@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "metro-react-native-babel-preset > @babel/plugin-proposal-optional-chaining@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "metro-react-native-babel-preset > @babel/plugin-transform-flow-strip-types@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "metro-react-native-babel-preset > @babel/plugin-transform-modules-commonjs@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "metro-react-native-babel-preset > @babel/plugin-transform-arrow-functions@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "metro-react-native-babel-preset > @babel/plugin-transform-block-scoping@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "metro-react-native-babel-preset > @babel/plugin-transform-classes@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "metro-react-native-babel-preset > @babel/plugin-transform-computed-properties@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "metro-react-native-babel-preset > @babel/plugin-transform-destructuring@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "metro-react-native-babel-preset > @babel/plugin-transform-for-of@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "metro-react-native-babel-preset > @babel/plugin-transform-function-name@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "metro-react-native-babel-preset > @babel/plugin-transform-literals@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "metro-react-native-babel-preset > @babel/plugin-transform-parameters@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "metro-react-native-babel-preset > @babel/plugin-transform-react-display-name@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "metro-react-native-babel-preset > @babel/plugin-transform-react-jsx@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "metro-react-native-babel-preset > @babel/plugin-transform-shorthand-properties@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "metro-react-native-babel-preset > @babel/plugin-transform-spread@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "metro-react-native-babel-preset > @babel/plugin-transform-template-literals@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "metro-react-native-babel-preset > @babel/plugin-proposal-export-default-from@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "metro-react-native-babel-preset > @babel/plugin-syntax-dynamic-import@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "metro-react-native-babel-preset > @babel/plugin-syntax-export-default-from@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "metro-react-native-babel-preset > @babel/plugin-transform-exponentiation-operator@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "metro-react-native-babel-preset > @babel/plugin-transform-object-assign@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "metro-react-native-babel-preset > @babel/plugin-transform-react-jsx-source@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "metro-react-native-babel-preset > @babel/plugin-transform-regenerator@7.0.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "metro-react-native-babel-preset > @babel/plugin-transform-runtime@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "metro-react-native-babel-preset > @babel/plugin-transform-sticky-regex@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "metro-react-native-babel-preset > @babel/plugin-transform-typescript@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "metro-react-native-babel-preset > @babel/plugin-transform-unicode-regex@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "react-navigation > react-navigation-tabs@1.0.1" has unmet peer dependency "react-native-screens@^1.0.0 || ^1.0.0-alpha".
warning "react-navigation > react-navigation-stack@1.0.4" has unmet peer dependency "react-native-gesture-handler@^1.0.0".
warning "react-navigation > react-navigation-stack@1.0.4" has unmet peer dependency "react-native-screens@^1.0.0 || ^1.0.0-alpha".
warning "react-navigation > react-navigation-drawer@1.0.4" has unmet peer dependency "react-native-gesture-handler@^1.0.0".
warning "react-navigation > react-navigation-drawer@1.0.4" has unmet peer dependency "react-native-screens@^1.0.0 || ^1.0.0-alpha".
warning "react-navigation > @react-navigation/core > create-react-context@0.2.3" has unmet peer dependency "prop-types@^15.0.0".
warning " > babel-jest@23.6.0" has unmet peer dependency "babel-core@^6.0.0 || ^7.0.0-0".
warning " > metro-react-native-babel-preset@0.50.0" has unmet peer dependency "@babel/core@*".
warning " > @babel/plugin-proposal-decorators@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/plugin-proposal-decorators > @babel/plugin-syntax-decorators@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning " > @storybook/react-native@3.4.3" has unmet peer dependency "babel-core@^6.26.0 || ^7.0.0-0".
warning " > @storybook/react-native@3.4.3" has unmet peer dependency "babel-runtime@>=6.0.0".
warning "@storybook/react-native > babel-loader@7.1.5" has unmet peer dependency "babel-core@6".
error Command failed with exit code 1.

----------
⠸ ▸ installing react-native-gesture-handler@1.0.9 an error occured while installing ignite-ir-boilerplate-bowser boilerplate.
Error: Command failed: yarn add react-native-gesture-handler@1.0.9
warning "metro-react-native-babel-preset > @babel/plugin-proposal-class-properties@7.2.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "metro-react-native-babel-preset > @babel/plugin-proposal-nullish-coalescing-operator@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "metro-react-native-babel-preset > @babel/plugin-proposal-object-rest-spread@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning " > @babel/plugin-proposal-optional-catch-binding@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "metro-react-native-babel-preset > @babel/plugin-proposal-optional-chaining@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "metro-react-native-babel-preset > @babel/plugin-transform-flow-strip-types@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "metro-react-native-babel-preset > @babel/plugin-transform-modules-commonjs@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "metro-react-native-babel-preset > @babel/plugin-transform-arrow-functions@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "metro-react-native-babel-preset > @babel/plugin-transform-block-scoping@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "metro-react-native-babel-preset > @babel/plugin-transform-classes@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "metro-react-native-babel-preset > @babel/plugin-transform-computed-properties@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "metro-react-native-babel-preset > @babel/plugin-transform-destructuring@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "metro-react-native-babel-preset > @babel/plugin-transform-for-of@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "metro-react-native-babel-preset > @babel/plugin-transform-function-name@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "metro-react-native-babel-preset > @babel/plugin-transform-literals@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "metro-react-native-babel-preset > @babel/plugin-transform-parameters@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "metro-react-native-babel-preset > @babel/plugin-transform-react-display-name@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "metro-react-native-babel-preset > @babel/plugin-transform-react-jsx@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "metro-react-native-babel-preset > @babel/plugin-transform-shorthand-properties@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "metro-react-native-babel-preset > @babel/plugin-transform-spread@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "metro-react-native-babel-preset > @babel/plugin-transform-template-literals@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "metro-react-native-babel-preset > @babel/plugin-proposal-export-default-from@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "metro-react-native-babel-preset > @babel/plugin-syntax-dynamic-import@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "metro-react-native-babel-preset > @babel/plugin-syntax-export-default-from@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "metro-react-native-babel-preset > @babel/plugin-transform-exponentiation-operator@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "metro-react-native-babel-preset > @babel/plugin-transform-object-assign@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "metro-react-native-babel-preset > @babel/plugin-transform-react-jsx-source@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "metro-react-native-babel-preset > @babel/plugin-transform-regenerator@7.0.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "metro-react-native-babel-preset > @babel/plugin-transform-runtime@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "metro-react-native-babel-preset > @babel/plugin-transform-sticky-regex@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "metro-react-native-babel-preset > @babel/plugin-transform-typescript@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "metro-react-native-babel-preset > @babel/plugin-transform-unicode-regex@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "react-navigation > react-navigation-drawer@1.0.4" has unmet peer dependency "react-native-screens@^1.0.0 || ^1.0.0-alpha".
warning "react-navigation > react-navigation-stack@1.0.4" has unmet peer dependency "react-native-screens@^1.0.0 || ^1.0.0-alpha".
warning "react-navigation > react-navigation-tabs@1.0.1" has unmet peer dependency "react-native-screens@^1.0.0 || ^1.0.0-alpha".
warning "react-navigation > @react-navigation/core > create-react-context@0.2.3" has unmet peer dependency "prop-types@^15.0.0".
warning " > @babel/plugin-proposal-decorators@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/plugin-proposal-decorators > @babel/plugin-syntax-decorators@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning " > @storybook/react-native@3.4.3" has unmet peer dependency "babel-core@^6.26.0 || ^7.0.0-0".
warning " > @storybook/react-native@3.4.3" has unmet peer dependency "babel-runtime@>=6.0.0".
warning "@storybook/react-native > babel-loader@7.1.5" has unmet peer dependency "babel-core@6".
warning " > babel-jest@23.6.0" has unmet peer dependency "babel-core@^6.0.0 || ^7.0.0-0".
warning " > metro-react-native-babel-preset@0.50.0" has unmet peer dependency "@babel/core@*".
error Command failed with exit code 1.
```

It's still spinning on another attempt at `react-native-gesture-handler@1.0.9`.  It looks like I will need to force-quit.  It's been going for a good 15 minutes.

---
Steps to reproduce

1. `ignite new app` 
1. (select Bowser)

---
`ignite doctor` results:
Doctor output is interesting.  It says I have a CLI-only installation of Xcode, but that's wrong.  Perhaps because I upgraded to Mojave?

```
Roberts-MacBook-Pro:AzbsRn2019 robpaveza$ ignite doctor
System
  platform           darwin                                                                                      
  arch               x64                                                                                         
  cpu                12 cores                               Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz  
  directory          /Users/robpaveza/projects/AzbsRn2019                                                        

JavaScript
  node               10.10.0      /usr/local/bin/node  
  npm                6.4.1        /usr/local/bin/npm   
  yarn               1.12.3       /usr/local/bin/yarn  

React Native
  react-native-cli   2.0.1       

Ignite
  ignite             2.1.2        /usr/local/bin/ignite  

Android
  java               11.0.1       /usr/bin/java  
  android home       -            undefined      
vvv -----[ DEBUG ]----- vvv
{ Error: Command failed: xcodebuild -version
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

    at ChildProcess.exithandler (child_process.js:289:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'xcodebuild -version',
  stderr:
   'xcode-select: error: tool \'xcodebuild\' requires Xcode, but active developer directory \'/Library/Developer/CommandLineTools\' is a command line tools instance\n' }
^^^ -----[ DEBUG ]----- ^^^
```

**Comment by jamonholmgren** [comment]
Hey @robpaveza , can you try a non-sudo install of Ignite?

**Comment by robpaveza** [comment]
Maybe I'm outdated on npm?  But I need to `sudo` in order to `npm i -g`, otherwise I get `EACCES`.  And if I just `npm i ignite-cli`, that would just install to a local directory?  (That works, but doesn't register the `ignite` command line; instead it's installed like a regular Node module).

Separately: I solved the problem about Xcode.  https://github.com/nodejs/node-gyp/issues/569 `sudo xcode-select -s /Applications/Xcode.app/Contents/Developer`.  However, that just allows `ignite doctor` to complete as expected.

```
Roberts-MacBook-Pro:ChainReactApp2018 robpaveza$ ignite doctor
System
  platform           darwin                                                                                             
  arch               x64                                                                                                
  cpu                12 cores                                      Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz  
  directory          /Users/robpaveza/projects/ChainReactApp2018                                                        

JavaScript
  node               10.10.0      /usr/local/bin/node  
  npm                6.4.1        /usr/local/bin/npm   
  yarn               1.12.3       /usr/local/bin/yarn  

React Native
  react-native-cli   2.0.1       
  app rn version     0.55.4      

Ignite
  ignite             2.1.2        /usr/local/bin/ignite  

Android
  java               11.0.1       /usr/bin/java  
  android home       -            undefined      

iOS
  xcode              10.1        
```

**Comment by jamonholmgren** [comment]
I think it's related to the issue we're fixing with this: https://github.com/infinitered/ignite-ir-boilerplate-bowser/pull/127 and this https://github.com/infinitered/ignite-ir-boilerplate-bowser/pull/130. I'm going to try to get these deployed by the end of the week. Apologies for the delay, it's been a very busy week!

**Comment by jamonholmgren** [comment]
@robpaveza I went ahead and merged those PRs. If you want to `npm i -g ignite-cli` and then try to spin up a new app, it should pick up Bowser version `1.1.1` which should _hopefully_ fix your issues.

(It should never take more than a couple minutes to complete, by the way.)

**Comment by jamonholmgren** [comment]
![image](https://user-images.githubusercontent.com/1479215/49566617-201e0080-f8e0-11e8-9288-81cf650a0218.png)

It appears to be working for me with a bare install.

**Comment by carlinisaacson** [comment]
If you are still having issues with EACCES errors, here are some [npm docs](https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally) about solving those.
