### ISSUE TITLE
`ignite new` with local relative path to boilerplate is broken

### ISSUE THREAD

**Issue by jamonholmgren** [infinitered/ignite#1362]
Steps to reproduce:

1. Try installing a local boilerplate (e.g. `ignite new PizzaApp -b ../ignite-my-boilerplate`)

I added a few logging statements.

```
-----------------------------------------------

🔥 igniting app Foo1
{ directory: '/Users/jh/Code/ReactNative/ignite-bowser',
  moduleName: 'ignite-bowser',
  type: 'directory' }
⠋ adding ignite-bowser{ directory: '/Users/jh/Code/ReactNative/ignite-bowser',
  moduleName: 'ignite-bowser',
  type: 'directory' }
✔ using the Infinite Red boilerplate v3 (code name 'Bowser')
✔ added React Native 0.57.8 in 25.44s
⠋ adding /Users/jh/Code/ReactNative/playground/Foo1/ignite-bowser{ moduleName: '/Users/jh/Code/ReactNative/playground/Foo1/ignite-bowser',
  version: null,
  type: 'npm' }
⠹ adding /Users/jh/Code/ReactNative/playground/Foo1/ignite-bowser{ Error: Command failed: yarn add /Users/jh/Code/ReactNative/playground/Foo1/ignite-bowser --dev
warning @storybook/react-native > @storybook/core > autoprefixer > browserslist@2.11.3: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning @storybook/react-native > @storybook/core > css-loader > cssnano > autoprefixer > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning @storybook/react-native > @storybook/core > css-loader > cssnano > postcss-merge-rules > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning @storybook/react-native > @storybook/core > css-loader > cssnano > postcss-merge-rules > caniuse-api > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
error Package "/Users/jh/Code/ReactNative/playground/Foo1/ignite-bowser" refers to a non-existing file '"/Users/jh/Code/ReactNative/playground/Foo1/ignite-bowser"'.

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:188:13)
    at maybeClose (internal/child_process.js:978:16)
    at Socket.stream.socket.on (internal/child_process.js:395:11)
    at Socket.emit (events.js:188:13)
    at Pipe._handle.close (net.js:610:12)
  killed: false,
  code: 1,
  signal: null,
  cmd:
   'yarn add /Users/jh/Code/ReactNative/playground/Foo1/ignite-bowser --dev',
  stderr:
   `warning @storybook/react-native > @storybook/core > autoprefixer > browserslist@2.11.3: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.\nwarning @storybook/react-native > @storybook/core > css-loader > cssnano > autoprefixer > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.\nwarning @storybook/react-native > @storybook/core > css-loader > cssnano > postcss-merge-rules > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.\nwarning @storybook/react-native > @storybook/core > css-loader > cssnano > postcss-merge-rules > caniuse-api > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.\nerror Package "/Users/jh/Code/ReactNative/playground/Foo1/ignite-bowser" refers to a non-existing file '"/Users/jh/Code/ReactNative/playground/Foo1/ignite-bowser"'.\n` }
✖ /Users/jh/Code/ReactNative/playground/Foo1/ignite-bowser was not able to be installed. Is it a valid NPM module?
----------
Command failed: yarn add /Users/jh/Code/ReactNative/playground/Foo1/ignite-bowser --dev
warning @storybook/react-native > @storybook/core > autoprefixer > browserslist@2.11.3: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning @storybook/react-native > @storybook/core > css-loader > cssnano > autoprefixer > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning @storybook/react-native > @storybook/core > css-loader > cssnano > postcss-merge-rules > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning @storybook/react-native > @storybook/core > css-loader > cssnano > postcss-merge-rules > caniuse-api > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
error Package "/Users/jh/Code/ReactNative/playground/Foo1/ignite-bowser" refers to a non-existing file '"/Users/jh/Code/ReactNative/playground/Foo1/ignite-bowser"'.
```

**Comment by jamonholmgren** [comment]
It seems like a return of #985, but the fix is still in place. I'm puzzled.

Workaround is to use absolute paths ... again.

**Comment by donnes** [comment]
@jamonholmgren relative and absolute paths are not working on Windows when using Git Bash.
Trying to figure out a workaround, but if I find a definelly solution for the issue I'll send a PR.

For know, the evidence...

![image](https://user-images.githubusercontent.com/9506146/52480314-78000e80-2b92-11e9-93c2-6733332b6cb7.png)

**Comment by ryanlntn** [comment]
Relative paths to boilerplates appear to be fixed with Ignite 3. Still need to investigate windows but I believe we don't currently support an absolute path like `C:/path/to/boilerplate` since we're matching on `~`, `.`, `\\`, or `/`.

**Comment by jamonholmgren** [comment]
I'm going to close this, but if anyone wants to fix the absolute paths on Windows, feel free!
