### ISSUE TITLE
 Module `core-js/modules/es6.object.define-property` does not exist in the Haste module map

### ISSUE THREAD

**Issue by shawn-tangsc** [infinitered/ignite#1386]
### Hey there! Ignite CLI seems to be having a problem, eh?

---
What's going on?

```
error: bundling failed: Error: Unable to resolve module `core-js/modules/es6.object.define-property` from `/Users/tangsicheng/myCode/learn/react/CFP_NEW/node_modules/@storybook/addons/dist/index.js`: Module `core-js/modules/es6.object.define-property` does not exist in the Haste module map
```
---
Steps to reproduce

```
ignite new CFP_NEW
Which boilerplate would you like to use? Bowser (React Navigation, MobX State Tree, & T
ypeScript)
react-native run-ios
```
```
error: bundling failed: Error: Unable to resolve module `core-js/modules/es6.object.define-property` from `/Users/tangsicheng/myCode/learn/react/CFP_NEW/node_modules/@storybook/addons/dist/index.js`: Module `core-js/modules/es6.object.define-property` does not exist in the Haste module map

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.
  4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`.
    at ModuleResolver.resolveDependency (/Users/tangsicheng/myCode/learn/react/CFP_NEW/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:139:15)
    at ResolutionRequest.resolveDependency (/Users/tangsicheng/myCode/learn/react/CFP_NEW/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:49:18)
    at DependencyGraph.resolveDependency (/Users/tangsicheng/myCode/learn/react/CFP_NEW/node_modules/metro/src/node-haste/DependencyGraph.js:218:16)
    at Object.resolve (/Users/tangsicheng/myCode/learn/react/CFP_NEW/node_modules/metro/src/lib/transformHelpers.js:141:30)
    at dependencies.map.result (/Users/tangsicheng/myCode/learn/react/CFP_NEW/node_modules/metro/src/DeltaBundler/traverseDependencies.js:373:31)
    at Array.map (<anonymous>)
    at resolveDependencies (/Users/tangsicheng/myCode/learn/react/CFP_NEW/node_modules/metro/src/DeltaBundler/traverseDependencies.js:369:18)
    at /Users/tangsicheng/myCode/learn/react/CFP_NEW/node_modules/metro/src/DeltaBundler/traverseDependencies.js:188:33
    at Generator.next (<anonymous>)
    at step (/Users/tangsicheng/myCode/learn/react/CFP_NEW/node_modules/metro/src/DeltaBundler/traverseDependencies.js:298:30)
 BUNDLE  [ios, dev] ../../index.js ▓▓▓▓▓▓▓▓▓░░░░░░░ 61.1% (997/1291)::1 - - [26/Feb/2019:11:43:07 +0000] "GET /index.bundle?platform=ios&dev=true&minify=false HTTP/1.1" 200 - "-" "CFP_NEW/1 CFNetwork/975.0.3 Darwin/18.2.0"
 BUNDLE  [ios, dev] ../../index.js ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░ 98.8% (1370/1378)

```
---
`ignite doctor` results:

```
System
  platform           darwin                                                                                               
  arch               x64                                                                                                  
  cpu                8 cores                                         Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz  
  directory          /Users/tangsicheng/myCode/learn/react/CFP_NEW                                                        

JavaScript
  node               8.10.0       /usr/local/bin/node  
  npm                5.6.0        /usr/local/bin/npm   
  yarn               1.13.0       /usr/local/bin/yarn  

React Native
  react-native-cli   2.0.1       
  app rn version     0.57.8      

Ignite
  ignite             2.2.2           /usr/local/bin/ignite  
  boilerplate        ignite-bowser                                    

Android
  java               1.8.0_112    /Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home/bin/java  
  android home       -            /Applications/eclipse_android/sdk                                          

iOS
  xcode              10.1        
```

**Comment by shawn-tangsc** [comment]
It looks like I've solved it.
run 
```
npm install core-js --save 
```
its seem fixed it .

**Comment by freevital** [comment]
I have the same issues and the command above doesn't fix it.

**Comment by jrgiant** [comment]
@freevital I ran into the same issue. core-js just updated to 3.0.0 (on 2019.03.19 according to changelog). Also mentioned in [Babel issue #9734](https://github.com/babel/babel/issues/9734#issue-423654875). A work around is to downgrade to core-js@2.6.5 until the issue is resolved.
