### ISSUE TITLE
package.json version of react not compatible with react-native

### ISSUE THREAD

**Issue by budda** [infinitered/ignite#1402]
What's going on?

Created a new project using boilerplate and ran ```npm install``` but this fails due to some forced package version in dependency.

react-native 0.59.3 required react 16.8.3 but the ignite package.json specifies 16.6.1

error:
```
npm WARN react-native@0.59.3 requires a peer of react@16.8.3 but none is installed. You must install peer dependencies yourself.
```

i fixed by modifying the projects generated package.json to require react@16.8.3 instead.

---
Steps to reproduce

run ```npm install``` on a fresh new project.

---
`ignite doctor` results:
```
System
  platform           darwin
  arch               x64
  cpu                8 cores                                            Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
  directory          /Users/mikec/Documents/code/mobile/awesomeIgnite
vvv -----[ DEBUG ]----- vvv
{ Error: not found: yarn
    at getNotFoundError (/usr/local/lib/node_modules/ignite-cli/node_modules/gluegun/node_modules/which/which.js:13:12)
    at Function.whichSync [as sync] (/usr/local/lib/node_modules/ignite-cli/node_modules/gluegun/node_modules/which/which.js:131:9)
    at which (/usr/local/lib/node_modules/ignite-cli/node_modules/gluegun/src/core-extensions/system-extension.js:113:22)
    at Command.module.exports [as run] (/usr/local/lib/node_modules/ignite-cli/src/commands/doctor.js:45:20)
    at processTicksAndRejections (internal/process/task_queues.js:86:5) code: 'ENOENT' }
^^^ -----[ DEBUG ]----- ^^^
```

**Comment by jamonholmgren** [comment]
What version of Ignite CLI are you running, @budda ?

**Comment by budda** [comment]
Ignite CLI was a fresh NPM install 4 days ago. I've since upgraded it today to test the other fixes.

**Comment by jamonholmgren** [comment]
Okay, thanks @budda!

**Comment by ryanlntn** [comment]
This should be fixed with Ignite 3 and the latest Andross and Bowser boilerplates.
