### ISSUE TITLE
Storybook not working out of the boy 

### ISSUE THREAD

**Issue by conradkirschner** [infinitered/ignite#1407]
maybe related to https://github.com/storybooks/storybook/issues/4179

---
What's going on?
ERROR in ./storybook/addons.js
Module build failed: Error: Couldn't find preset "module:metro-react-native-babel-preset" relative to directory "C:\\Users\\conrad\\Desktop\\react-native\\boilerplate_samples\\MyNewAppName12\\MyNewAppName12\\storybook"
---
Steps to reproduce
after try to use the sample code from pizza app 

npm run storybook
---
`ignite doctor` results:
System
  platform           win32                                                                                              
  arch               x64                                                                                                
  cpu                8 cores                                                                                  Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
  directory          C:\Users\conrad\Desktop\react-native\boilerplate_samples\MyNewAppName12\MyNewAppName12             

JavaScript
  node               8.12.0       C:\Program Files\nodejs\node.EXE
  npm                6.4.1        C:\Program Files\nodejs\npm.CMD
  yarn               1.15.2       C:\Program Files (x86)\Yarn\bin\yarn.CMD

React Native
  react-native-cli   2.0.1
  app rn version     0.57.7

Ignite
  ignite             2.2.4            C:\Program Files\nodejs\ignite.CMD
  boilerplate        ignite-andross
vvv -----[ DEBUG ]----- vvv
{ Error: not found: java
    at getNotFoundError (C:\Users\conrad\AppData\Roaming\nvm\v8.12.0\node_modules\ignite-cli\node_modules\gluegun\node_modules\which\which.js:13:12)
    at Function.whichSync [as sync] (C:\Users\conrad\AppData\Roaming\nvm\v8.12.0\node_modules\ignite-cli\node_modules\gluegun\node_modules\which\which.js:131:9)
    at which (C:\Users\conrad\AppData\Roaming\nvm\v8.12.0\node_modules\ignite-cli\node_modules\gluegun\src\core-extensions\system-extension.js:113:22)
    at Command.module.exports [as run] (C:\Users\conrad\AppData\Roaming\nvm\v8.12.0\node_modules\ignite-cli\src\commands\doctor.js:96:20)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7) code: 'ENOENT' }
^^^ -----[ DEBUG ]----- ^^^

**Comment by jamonholmgren** [comment]
@conradkirschner Would you mind using the latest beta Ignite CLI?

```
npm uninstall -g ignite-cli
npm install -g ignite-cli

# or with yarn (recommended)
yarn global remove ignite-cli
yarn global add ignite-cli
```

**Comment by ryanlntn** [comment]
This is being tracked on the ignite-andross repo here: https://github.com/infinitered/ignite-andross/issues/216
