### ISSUE TITLE
CLI error when installing Browser bolierplate ignite beta

### ISSUE THREAD

**Issue by stevematdavies** [infinitered/ignite#1409]
CLI bolerplate install error.

```
🔥 igniting app MyTestApp
✔ Which boilerplate would you like to use? · Bowser (React Navigation, MobX State Tree, & TypeScript) - RECOMMENDED
🐉 You're using a prerelease version of bowser@beta4.
⠋ installing boilerplate
```
```

> Error call stack:
> ...../TestApp/node_modules/ignite-bowser/boilerplate.js:233
>     print.error('
>                 ^
> 
> SyntaxError: Invalid or unexpected token
>     at new Script (vm.js:84:7)
>     at createScript (vm.js:264:10)
>     at Object.runInThisContext (vm.js:312:10)
>     at Module._compile (internal/modules/cjs/loader.js:684:28)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
>     at Module.load (internal/modules/cjs/loader.js:620:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:552:3)
>     at Module.require (internal/modules/cjs/loader.js:657:17)
>     at require (internal/modules/cjs/helpers.js:20:18)
> ✖ error loading the boilerplate
> error installing boilerplate

```

 `ignite new TestApp`  causes the error

`ignite doctor`

```
System
  platform           darwin

  arch               x64
  cpu                12 cores                               Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
  directory          /Users/#/Projects/ReactNative

JavaScript
  node               11.7.0       /Users/#/.nvm/versions/node/v11.7.0/bin/node
  npm                6.7.0        /Users/#/.nvm/versions/node/v11.7.0/bin/npm
  yarn               1.13.0       /Users/#/.nvm/versions/node/v11.7.0/bin/yarn

React Native
  react-native-cli   2.0.1

Ignite
  ignite             3.0.0-beta.3   /usr/local/bin/ignite

Android
  java               1.8.0_202    /usr/bin/java
  android home       -            /Users/#/Library/Android/sdk

iOS
  xcode              10.1
```

**Comment by stevematdavies** [comment]
could it be due to `You're using a prerelease version of bowser@beta4.` ?

**Comment by jamonholmgren** [comment]
@stevematdavies I found the issue and pushed up a fix. Can you try again, please?

I'm going to close this issue as I believe it's fixed.

Ref: https://github.com/infinitered/ignite-bowser/commit/45b7122856228fb3f5fb91ea5f44392ff25c5506

**Comment by stevematdavies** [comment]
Looks good from my side all working, top job @jamonholmgren many thanks
