### ISSUE TITLE
spork ignite fails

### ISSUE THREAD

**Issue by AnonymousSB** [infinitered/ignite#1433]
# What's the matta?
`ignite spork` fails epically

# What happened?
ran `ignite spork` in the root directory, received the following error:

> Error: AssertionError [ERR_ASSERTION]: Prompt "checkbox" is not registered
>   
>   - index.js:105 Enquirer.ask
>     [lib]/[ignite-cli]/[enquirer]/index.js:105:5
>   
>   - index.js:82 Enquirer.prompt
>     [lib]/[ignite-cli]/[enquirer]/index.js:82:20
>   
>   - prompt-tools.js:95 Object.<anonymous>
>     [lib]/[ignite-cli]/[gluegun]/build/toolbox/prompt-tools.js:95:49
>   
>   - prompt-tools.js:32 step
>     [lib]/[ignite-cli]/[gluegun]/build/toolbox/prompt-tools.js:32:23
>   
>   - prompt-tools.js:13 Object.next
>     [lib]/[ignite-cli]/[gluegun]/build/toolbox/prompt-tools.js:13:53
>   
>   - prompt-tools.js:7 
>     [lib]/[ignite-cli]/[gluegun]/build/toolbox/prompt-tools.js:7:71

# How'd I do it?
* New Project
* ignite-cli 3.1.1
* ran `ignite spork` in the root directory of my project

**Comment by jamonholmgren** [comment]
Can you give us the results of `ignite doctor` please? Thanks!

**Comment by AnonymousSB** [comment]
System
  platform           darwin                                                          
                                          
  arch               x64                                                             
  cpu                4 cores                Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz 
  directory          /Users/username                                            

JavaScript
  node               11.14.0      /usr/local/bin/node 
  npm                6.9.0        /usr/local/bin/npm  
  yarn               1.15.2       /usr/local/bin/yarn 

React Native
  react-native-cli   2.0.1      

Ignite
  ignite-cli         3.1.3        /usr/local/bin/ignite 

Android
  java               11.0.2       /usr/bin/java                            
  android home       -            /Users/username/Library/Android/sdk 

iOS
  xcode              10.2.1

**Comment by dkocich** [comment]
the same issue happened to me:

```
david@HPdk:~/it/XYZ$ ignite spork
  Error: AssertionError [ERR_ASSERTION]: Prompt "checkbox" is not registered
  
  - index.js:105 Enquirer.ask
    [lib]/[ignite-cli]/[enquirer]/index.js:105:5
  
  - index.js:82 Enquirer.prompt
    [lib]/[ignite-cli]/[enquirer]/index.js:82:20
  
  - prompt-tools.js:95 Object.<anonymous>
    [lib]/[ignite-cli]/[gluegun]/build/toolbox/prompt-tools.js:95:49
  
  - prompt-tools.js:32 step
    [lib]/[ignite-cli]/[gluegun]/build/toolbox/prompt-tools.js:32:23
  
  - prompt-tools.js:13 Object.next
    [lib]/[ignite-cli]/[gluegun]/build/toolbox/prompt-tools.js:13:53
  
  - prompt-tools.js:7 
    [lib]/[ignite-cli]/[gluegun]/build/toolbox/prompt-tools.js:7:71
  
  - new Promise
  
  - prompt-tools.js:3 __awaiter
    [lib]/[ignite-cli]/[gluegun]/build/toolbox/prompt-tools.js:3:12
  
  - prompt-tools.js:76 Object.ask
    [lib]/[ignite-cli]/[gluegun]/build/toolbox/prompt-tools.js:76:40
  
  - spork.js:96 Command.<anonymous>
    [lib]/[ignite-cli]/build/commands/spork.js:96:65
  

/home/david/.nvm/versions/node/v12.2.0/lib/node_modules/ignite-cli/node_modules/gluegun/build/index.js:13
    throw up;
    ^

AssertionError [ERR_ASSERTION]: Prompt "checkbox" is not registered
    at Enquirer.ask (/home/david/.nvm/versions/node/v12.2.0/lib/node_modules/ignite-cli/node_modules/enquirer/index.js:105:5)
    at Enquirer.prompt (/home/david/.nvm/versions/node/v12.2.0/lib/node_modules/ignite-cli/node_modules/enquirer/index.js:82:20)
    at Object.<anonymous> (/home/david/.nvm/versions/node/v12.2.0/lib/node_modules/ignite-cli/node_modules/gluegun/build/toolbox/prompt-tools.js:95:49)
    at step (/home/david/.nvm/versions/node/v12.2.0/lib/node_modules/ignite-cli/node_modules/gluegun/build/toolbox/prompt-tools.js:32:23)
    at Object.next (/home/david/.nvm/versions/node/v12.2.0/lib/node_modules/ignite-cli/node_modules/gluegun/build/toolbox/prompt-tools.js:13:53)
    at /home/david/.nvm/versions/node/v12.2.0/lib/node_modules/ignite-cli/node_modules/gluegun/build/toolbox/prompt-tools.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/home/david/.nvm/versions/node/v12.2.0/lib/node_modules/ignite-cli/node_modules/gluegun/build/toolbox/prompt-tools.js:3:12)
    at Object.ask (/home/david/.nvm/versions/node/v12.2.0/lib/node_modules/ignite-cli/node_modules/gluegun/build/toolbox/prompt-tools.js:76:40)
    at Command.<anonymous> (/home/david/.nvm/versions/node/v12.2.0/lib/node_modules/ignite-cli/build/commands/spork.js:96:65)

```

```
david@HPdk:~/it/XYZ$ ignite doctor
System
  platform           linux                                                                      
                                          
  arch               x64                                                                        
  cpu                8 cores                           Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz 
  directory          /home/david/it/XYZ                                            

JavaScript
  node               12.2.0       /home/david/.nvm/versions/node/v12.2.0/bin/node 
  npm                6.10.0       /home/david/.nvm/versions/node/v12.2.0/bin/npm  
  yarn               1.16.0       /home/david/.nvm/versions/node/v12.2.0/bin/yarn 

React Native
  react-native-cli   2.0.1      
  app rn version     0.59.8     

Ignite
  ignite-cli           3.1.5                                                                                                                                                                                        /home/david/.nvm/versions/node/v12.2.0/bin/ignite 
  createdWith          3.1.1                                                                                                                                                                                                                                          
  boilerplate          ignite-andross                                                                                                                                                                                                                                 
  examples             classic                                                                                                                                                                                                                                        
  navigation           react-navigation                                                                                                                                                                                                                               
  askToOverwrite       true                                                                                                                                                                                                                                           
  generators           {"component":"ignite-andross","container":"ignite-andross","listview":"ignite-andross","list":"ignite-andross","redux":"ignite-andross","saga":"ignite-andross","screen":"ignite-andross"}                                                     
  boilerplateVersion   4.0.3                                                                                                                                                                                                                                          

Android
  java               1.8.0_212    /usr/lib/jvm/java-8-openjdk-amd64/bin/java 
  android home       -            /home/david/Android/Sdk                    

```
