### ISSUE TITLE
ignite new error

### ISSUE THREAD

**Issue by BirdsAndFish** [infinitered/ignite#1448]
<img width="956" alt="image" src="https://user-images.githubusercontent.com/13975743/61989622-21fe2500-b065-11e9-97cb-01ed3c55184e.png">

**Comment by lander854** [comment]
use sudo [rest of the command]

**Comment by BirdsAndFish** [comment]
thank you

**Comment by mikasaloli** [comment]
`🔥 igniting app PizzaApp                                                                                                √ Which boilerplate would you like to use? · ignite-bowser                                                              √ using the Infinite Red boilerplate v3 (code name 'Bowser')                                                            √ added React Native 0.60.4 in 140.06s                                                                                  √ added ignite-bowser in 118.03s                                                                                        an error occured while installing ignite-bowser boilerplate.                                                            { Error: Command failed: yarn                                                                                           The system cannot find the path specified.                                                                              error Command failed with exit code 1.                                                                                  
    at ChildProcess.exithandler (child_process.js:294:12)                                                                   at ChildProcess.emit (events.js:189:13)                                                                                 at maybeClose (internal/child_process.js:970:16)                                                                        at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)                                              killed: false,                                                                                                          code: 1,                                                                                                                signal: null,                                                                                                           cmd: 'yarn',                                                                                                            stderr:                                                                                                                  'The system cannot find the path specified.\r\nerror Command failed with exit code 1.\n' }                           error installing boilerplate      `

**Comment by mikasaloli** [comment]
![asd](https://user-images.githubusercontent.com/32994521/62825127-f9336f00-bbd0-11e9-95b8-a95677309e0e.PNG)
how about mine i tried to change pc but same result

**Comment by geekz-reno** [comment]
> ![asd](https://user-images.githubusercontent.com/32994521/62825127-f9336f00-bbd0-11e9-95b8-a95677309e0e.PNG)
> how about mine i tried to change pc but same result

same here, please help,

**Comment by abuslah** [comment]
asme here ! HELP LEASE !

**Comment by markrickert** [comment]
@mikasaloli and @geekz-reno, looks like you guys have a different issue. Looks like yarn package manager isn't installed.

try following the instructions here and trying again: https://yarnpkg.com/lang/en/docs/install/#mac-stable

**Comment by markrickert** [comment]
The original issue was solved by running the command in `sudo` mode. Closing this isssue.
