### ISSUE TITLE
postinstall works only on iOS

### ISSUE THREAD

**Issue by kbzowski** [infinitered/ignite#1454]
Creating a new project with ignite-bowser on Windows 10 ends with an error:. 

```09:39:27 [ignite] requiring ignite plugin from f:\PRACA\PRIV_PROJECT\conf-mobile\test1\test1/node_modules/ignite-bowser
09:39:27 [ignite] running add() on ignite plugin
√ added ignite-bowser in 47s
- ▸ installing react-native-gesture-handler@^1.3.0 09:39:27 [ignite] yarn add react-native-gesture-handler@^1.3.0
an error occured while installing ignite-bowser boilerplate.
Error: Command failed: yarn
System cannot find the path specified.
error Command failed with exit code 1.

    at ChildProcess.exithandler (child_process.js:297:12)
    at ChildProcess.emit (events.js:203:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5) {
  killed: false,
  code: 1,
  signal: null,
  cmd: 'yarn',
  stderr: 'System cannot find the path specified.\r\n' +
    'error Command failed with exit code 1.\n'
}
error installing boilerplate
```

I guess the blame is on the postinstall script, which assumes that cocoapods is installed (which is available AFAIK only for iOS).

`"postinstall": "solidarity && jetify && (cd ios; pod install)",`

Removing last part of the script fixes the problem.

---
`ignite doctor` results:

```System
  platform           win32

  arch               x64
  cpu                8 cores                             Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
  directory          f:\PRACA\PRIV_PROJECT\conf-mobile

JavaScript
  node               12.6.0       C:\Program Files\nodejs\node.EXE
  npm                6.9.0        C:\Program Files\nodejs\npm.CMD
  yarn               1.17.3       C:\Program Files (x86)\Yarn\bin\yarn.CMD

React Native
  react-native-cli   2.0.1

Ignite
  ignite-cli         3.1.6        C:\Users\Krzysztof\AppData\Local\Yarn\bin\ignite.CMD

Android
  java               -            C:\Program Files (x86)\Common Files\Oracle\Java\javapath\java.EXE
  android home       -            D:\Android\SDK
```

**Comment by RaitoBezarius** [comment]
I confirm this issue, I'm on Linux, I get this error before the postinstall makes node gives up: `sh: pod: command not found`

**Comment by RaitoBezarius** [comment]
Related to: https://github.com/infinitered/ignite-bowser/issues/231

**Comment by RaitoBezarius** [comment]
I implemented a fix in the boilerplate "bowser-postfinall-fixed" to install with: `ignite new MyProject -b bower-postinstall-fixed`: https://github.com/RaitoBezarius/ignite-bowser — I'll open a PR

**Comment by FrederickEngelhardt** [comment]
@kbzowski for react-native 0.60.4 you will need cocoapods for iOS linking and AFAIK iOS development. 

This case could be solved by adding postinstall script which detects if the user either has linux or darwin. Or we could detect if pod exists in path.

Example:

*create a file called postinstall.js*
```
const { exec } = require('child_process')
if (process.platform === 'linux' || process.platform === 'darwin') {
	exec('yarn link:ios', (error, stdout, stderr) => {
		console.log(stdout);
		console.log(stderr);
		if (error !== null) {
			console.log(`exec error: ${error}`);
		}
	})
}
```
In package json under scripts we would replace postinstall like this:
```"postinstall": "node postinstall.js"```

**Comment by kevinvangelder** [comment]
#1456 Is an initial fix for this issue. Hopefully we'll get a chance to implement a more robust fix in the near future.

**Comment by imadmk** [comment]
I successfully created a project with Linux Bash Shell on windows 10. Need some works if you never install it before.
