### ISSUE TITLE
Error creating new project

### ISSUE THREAD

**Issue by MarkRabey** [infinitered/ignite#1477]
---
What's going on?

When trying to create a new project, I receive errors during the installation process. It take about 1 minute on the "adding React Native" step, then on the "adding ignite-bowser" step, I get an error that says `✖ ignite-bowser was not able to be installed. Is it a valid NPM module?`. Next there is an error shown relating to `react-native-gesture-handler`.

---
Steps to reproduce

run `ignite new MyApp` and select Bowser for the boilerplate.

---
`ignite doctor` results:
```
System
  platform           darwin

  arch               x64
  cpu                8 cores       Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
  directory          /Users/mark

JavaScript
  node               10.16.3      /usr/local/bin/node
  npm                6.9.0        /usr/local/bin/npm
  yarn               1.16.0       /usr/local/bin/yarn

React Native
  react-native-cli   2.0.1

Ignite
  ignite-cli         3.1.6        /usr/local/bin/ignite

Android
  java               1.8.0_131    /usr/bin/java
  android home       -            /Users/mark/Library/Android/sdk

iOS
  xcode              11.0
```

**Comment by dperez3** [comment]
Same...
```
System
  platform           linux                                                                            
                                         
  arch               x64                                                                              
  cpu                4 cores                                  Intel(R) Pentium(R) CPU 4405U @ 2.10GHz 
  directory          /home/domingo/Projects/Healthier%20App                                           

JavaScript
  node               12.11.1      /usr/bin/node                      
  npm                6.12.0       /home/domingo/.npm-global/bin/npm  
  yarn               1.19.1       /home/domingo/.npm-global/bin/yarn 

React Native
  react-native-cli   2.0.1      

Ignite
  ignite-cli         3.2.1        /home/domingo/.npm-global/bin/ignite 

Android
  java               11.0.4       /usr/bin/java             
  android home       -            /home/domingo/Android/Sdk 

```

**Comment by elirangoshen** [comment]
i solved it by validate cocoapods is latest version an xcode is located app /Application dir

and than run this command : sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

**Comment by amrox** [comment]
I'm seeing this too. I think my Xcode is fine.

I selected "false" for Detox.

```
✔ Which boilerplate would you like to use? · ignite-bowser
✔ using the Infinite Red boilerplate v3 (code name 'Bowser')
✔ Would you like to include Detox end-to-end tests? (y/N) · false
✔ added React Native 0.61.2 in 43.65s
✖ ignite-bowser was not able to be installed. Is it a valid NPM module?
----------
Command failed: yarn add ignite-bowser --dev
warning solidarity > gluegun > enquirer > set-value@1.0.0: Critical bug fixed in v3.0.1, please upgrade to the latest version.
warning solidarity > gluegun > enquirer > prompt-question > prompt-choices > set-value@1.0.0: Critical bug fixed in v3.0.1, please upgrade to the latest version.
warning solidarity > gluegun > prompt-autocompletion > prompt-choices > set-value@0.4.3: Critical bug fixed in v3.0.1, please upgrade to the latest version.
warning "react-navigation > react-navigation-drawer@1.2.1" has unmet peer dependency "react-native-screens@^1.0.0 || ^1.0.0-alpha".
warning "react-navigation > react-navigation-tabs@1.1.4" has unmet peer dependency "react-native-screens@^1.0.0 || ^1.0.0-alpha".
warning "react-navigation > react-navigation-stack@1.4.0" has unmet peer dependency "react-native-screens@^1.0.0 || ^1.0.0-alpha".
warning " > reactotron-mst@3.1.3" has unmet peer dependency "reactotron-core-client@^2.5.0".
warning "@storybook/react-native > @storybook/client-api > @storybook/router@5.1.11" has unmet peer dependency "react-dom@*".
warning "@storybook/addon-storyshots > @storybook/addons > @storybook/api > @storybook/theming@5.1.11" has unmet peer dependency "react-dom@*".
warning "@storybook/addon-storyshots > @storybook/addons > @storybook/api > @storybook/router > @reach/router@1.2.1" has unmet peer dependency "react-dom@15.x || 16.x || 16.4.0-alpha.0911da3".
warning " > @typescript-eslint/eslint-plugin@1.13.0" has incorrect peer dependency "eslint@^5.0.0".
warning " > @typescript-eslint/parser@1.13.0" has incorrect peer dependency "eslint@^5.0.0".
error Command failed with exit code 1.

----------
⠧ ▸ installing react-native-gesture-handler@^1.3.0
      There were errors while generating the project. Run with --debug to see verbose output.

an error occured while installing ignite-bowser boilerplate.
Error: Command failed: yarn add react-native-gesture-handler@^1.3.0
warning "react-navigation > react-navigation-drawer@1.2.1" has unmet peer dependency "react-native-screens@^1.0.0 || ^1.0.0-alpha".
warning "react-navigation > react-navigation-stack@1.4.0" has unmet peer dependency "react-native-screens@^1.0.0 || ^1.0.0-alpha".
warning "react-navigation > react-navigation-tabs@1.1.4" has unmet peer dependency "react-native-screens@^1.0.0 || ^1.0.0-alpha".
warning " > reactotron-mst@3.1.3" has unmet peer dependency "reactotron-core-client@^2.5.0".
warning "@storybook/react-native > @storybook/client-api > @storybook/router@5.1.11" has unmet peer dependency "react-dom@*".
warning "@storybook/addon-storyshots > @storybook/addons > @storybook/api > @storybook/theming@5.1.11" has unmet peer dependency "react-dom@*".
warning "@storybook/addon-storyshots > @storybook/addons > @storybook/api > @storybook/router > @reach/router@1.2.1" has unmet peer dependency "react-dom@15.x || 16.x || 16.4.0-alpha.0911da3".
warning " > @typescript-eslint/eslint-plugin@1.13.0" has incorrect peer dependency "eslint@^5.0.0".
warning " > @typescript-eslint/parser@1.13.0" has incorrect peer dependency "eslint@^5.0.0".
error Command failed with exit code 1.

    at ChildProcess.exithandler (child_process.js:295:12)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5) {
  killed: false,
  code: 1,
  signal: null,
  cmd: 'yarn add react-native-gesture-handler@^1.3.0',
  stderr: 'warning "react-navigation > react-navigation-drawer@1.2.1" has unmet peer dependency "react-native-screens@^1.0.0 || ^1.0.0-alpha".\n' +
    'warning "react-navigation > react-navigation-stack@1.4.0" has unmet peer dependency "react-native-screens@^1.0.0 || ^1.0.0-alpha".\n' +
    'warning "react-navigation > react-navigation-tabs@1.1.4" has unmet peer dependency "react-native-screens@^1.0.0 || ^1.0.0-alpha".\n' +
    'warning " > reactotron-mst@3.1.3" has unmet peer dependency "reactotron-core-client@^2.5.0".\n' +
    'warning "@storybook/react-native > @storybook/client-api > @storybook/router@5.1.11" has unmet peer dependency "react-dom@*".\n' +
    'warning "@storybook/addon-storyshots > @storybook/addons > @storybook/api > @storybook/theming@5.1.11" has unmet peer dependency "react-dom@*".\n' +
    'warning "@storybook/addon-storyshots > @storybook/addons > @storybook/api > @storybook/router > @reach/router@1.2.1" has unmet peer dependency "react-dom@15.x || 16.x || 16.4.0-alpha.0911da3".\n' +
    'warning " > @typescript-eslint/eslint-plugin@1.13.0" has incorrect peer dependency "eslint@^5.0.0".\n' +
    'warning " > @typescript-eslint/parser@1.13.0" has incorrect peer dependency "eslint@^5.0.0".\n' +
    'error Command failed with exit code 1.\n'
}
error installing boilerplate
```
```
❯ ignite doctor
System
  platform           darwin

  arch               x64
  cpu                8 cores        Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz
  directory          /Users/amrox

JavaScript
  node               12.12.0      /usr/local/bin/node
  npm                6.11.3       /usr/local/bin/npm
  yarn               1.19.1       /usr/local/bin/yarn

React Native
  react-native-cli   2.0.1

Ignite
  ignite-cli         3.2.2        /usr/local/bin/ignite
  generators         {}

Android
  java               1.8.0_202-ea   /usr/bin/java
  android home       -              undefined

iOS
  xcode              11.1
  cocoapods          1.6.1        /usr/local/bin/pod
```

**Comment by jamonholmgren** [comment]
@amrox Try upgrading your CocoaPods to the latest:

```
gem install cocoapods
# if that doesn't work ...
sudo gem install cocoapods
```

**Comment by MarkRabey** [comment]
Thanks @jamonholmgren! That did the trick.

**Comment by elirangoshen** [comment]
@jamonholmgren worth to update docs maybe :)
