### ISSUE TITLE
Ignite-cli can not create a new project

### ISSUE THREAD

**Issue by TnasuH** [infinitered/ignite#1498]
Hi there,

I cannot create a new project via ignite-cli. Could you help me? Where is there problem? I tried fix it but I can't.
```

MacBook-Pro:projects tnasuh$ ignite new TargetImp
-----------------------------------------------
  (                  )   (                   
  )\ )   (        ( /(   )\ )    *   )       
 (()/(   )\ )     )\()) (()/(  ` )  /(   (   
  /(_)) (()/(    ((_)\   /(_))  ( )(_))  )\  
 (_))    /(_))_   _((_) (_))   (_(_())  ((_) 
 |_ _|  (_)) __| | \| | |_ _|  |_   _|  | __|
  | |     | (_ | | .` |  | |     | |    | _| 
 |___|     \___| |_|\_| |___|    |_|    |___|
-----------------------------------------------

An unfair headstart for your React Native apps.
https://infinite.red/ignite

-----------------------------------------------

🔥 igniting app TargetImp
✔ Which boilerplate would you like to use? · ignite-bowser
✔ using the Infinite Red boilerplate v3 (code name 'Bowser')
✔ Would you like to include Detox end-to-end tests? (y/N) · true

          You'll love Detox for testing your app! There are some additional requirements to
          install, so make sure to check out e2e/README.md in your generated app!
        
✔ added React Native 0.61.2 in 66.34s
✖ ignite-bowser was not able to be installed. Is it a valid NPM module?
----------
Command failed: yarn add ignite-bowser --dev
warning solidarity > gluegun > enquirer > set-value@1.0.0: Critical bug fixed in v3.0.1, please upgrade to the latest version.
warning solidarity > gluegun > prompt-autocompletion > prompt-choices > set-value@0.4.3: Critical bug fixed in v3.0.1, please upgrade to the latest version.
warning solidarity > gluegun > enquirer > prompt-question > prompt-choices > set-value@1.0.0: Critical bug fixed in v3.0.1, please upgrade to the latest version.
warning " > react-native@0.61.2" has incorrect peer dependency "react@16.9.0".
warning "react-navigation > react-navigation-tabs@1.1.4" has incorrect peer dependency "react-native-screens@^1.0.0 || ^1.0.0-alpha".
warning "react-navigation > react-navigation-drawer@1.2.1" has incorrect peer dependency "react-native-screens@^1.0.0 || ^1.0.0-alpha".
warning "react-navigation > react-navigation-stack@1.4.0" has incorrect peer dependency "react-native-screens@^1.0.0 || ^1.0.0-alpha".
warning " > reactotron-mst@3.1.3" has unmet peer dependency "reactotron-core-client@^2.5.0".
warning "@storybook/react-native > @storybook/client-api > @storybook/router@5.1.11" has unmet peer dependency "react-dom@*".
warning "@storybook/addon-storyshots > @storybook/addons > @storybook/api > @storybook/theming@5.1.11" has unmet peer dependency "react-dom@*".
warning "@storybook/addon-storyshots > @storybook/addons > @storybook/api > @storybook/router > @reach/router@1.2.1" has unmet peer dependency "react-dom@15.x || 16.x || 16.4.0-alpha.0911da3".
warning " > @typescript-eslint/eslint-plugin@1.13.0" has unmet peer dependency "eslint@^5.0.0".
warning "@typescript-eslint/eslint-plugin > @typescript-eslint/experimental-utils@1.13.0" has unmet peer dependency "eslint@*".
warning " > @typescript-eslint/parser@1.13.0" has unmet peer dependency "eslint@^5.0.0".
warning " > eslint-config-prettier@6.5.0" has unmet peer dependency "eslint@>=3.14.1".
warning " > eslint-config-standard@13.0.1" has unmet peer dependency "eslint@>=6.0.1".
warning " > eslint-plugin-import@2.18.2" has unmet peer dependency "eslint@2.x - 6.x".
warning " > eslint-plugin-node@9.2.0" has unmet peer dependency "eslint@>=5.16.0".
warning "eslint-plugin-node > eslint-plugin-es@1.4.1" has unmet peer dependency "eslint@>=4.19.1".
warning " > eslint-plugin-react@7.16.0" has unmet peer dependency "eslint@^3.0.0 || ^4.0.0 || ^5.0.0 || ^6.0.0".
warning " > eslint-plugin-react-native@3.8.1" has unmet peer dependency "eslint@^3.17.0 || ^4 || ^5 || ^6".
warning " > eslint-plugin-standard@4.0.1" has unmet peer dependency "eslint@>=5.0.0".
error Command failed with exit code 1.

----------
⠸ ▸ installing react-native-gesture-handler@^1.3.0 
      There were errors while generating the project. Run with --debug to see verbose output.
    
an error occured while installing ignite-bowser boilerplate.
Error: Command failed: yarn add react-native-gesture-handler@^1.3.0
warning " > react-native@0.61.2" has incorrect peer dependency "react@16.9.0".
warning "react-navigation > react-navigation-drawer@1.2.1" has incorrect peer dependency "react-native-screens@^1.0.0 || ^1.0.0-alpha".
warning "react-navigation > react-navigation-stack@1.4.0" has incorrect peer dependency "react-native-screens@^1.0.0 || ^1.0.0-alpha".
warning "react-navigation > react-navigation-tabs@1.1.4" has incorrect peer dependency "react-native-screens@^1.0.0 || ^1.0.0-alpha".
warning " > reactotron-mst@3.1.3" has unmet peer dependency "reactotron-core-client@^2.5.0".
warning "@storybook/react-native > @storybook/client-api > @storybook/router@5.1.11" has unmet peer dependency "react-dom@*".
warning "@storybook/addon-storyshots > @storybook/addons > @storybook/api > @storybook/theming@5.1.11" has unmet peer dependency "react-dom@*".
warning "@storybook/addon-storyshots > @storybook/addons > @storybook/api > @storybook/router > @reach/router@1.2.1" has unmet peer dependency "react-dom@15.x || 16.x || 16.4.0-alpha.0911da3".
warning " > @typescript-eslint/eslint-plugin@1.13.0" has unmet peer dependency "eslint@^5.0.0".
warning "@typescript-eslint/eslint-plugin > @typescript-eslint/experimental-utils@1.13.0" has unmet peer dependency "eslint@*".
warning " > @typescript-eslint/parser@1.13.0" has unmet peer dependency "eslint@^5.0.0".
warning " > eslint-config-prettier@6.5.0" has unmet peer dependency "eslint@>=3.14.1".
warning " > eslint-config-standard@13.0.1" has unmet peer dependency "eslint@>=6.0.1".
warning " > eslint-plugin-import@2.18.2" has unmet peer dependency "eslint@2.x - 6.x".
warning " > eslint-plugin-node@9.2.0" has unmet peer dependency "eslint@>=5.16.0".
warning "eslint-plugin-node > eslint-plugin-es@1.4.1" has unmet peer dependency "eslint@>=4.19.1".
warning " > eslint-plugin-react@7.16.0" has unmet peer dependency "eslint@^3.0.0 || ^4.0.0 || ^5.0.0 || ^6.0.0".
warning " > eslint-plugin-react-native@3.8.1" has unmet peer dependency "eslint@^3.17.0 || ^4 || ^5 || ^6".
warning " > eslint-plugin-standard@4.0.1" has unmet peer dependency "eslint@>=5.0.0".
error Command failed with exit code 1.

    at ChildProcess.exithandler (child_process.js:295:12)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:210:5)
    at Pipe.<anonymous> (net.js:658:12) {
  killed: false,
  code: 1,
  signal: null,
  cmd: 'yarn add react-native-gesture-handler@^1.3.0',
  stderr: 'warning " > react-native@0.61.2" has incorrect peer dependency "react@16.9.0".\n' +
    'warning "react-navigation > react-navigation-drawer@1.2.1" has incorrect peer dependency "react-native-screens@^1.0.0 || ^1.0.0-alpha".\n' +
    'warning "react-navigation > react-navigation-stack@1.4.0" has incorrect peer dependency "react-native-screens@^1.0.0 || ^1.0.0-alpha".\n' +
    'warning "react-navigation > react-navigation-tabs@1.1.4" has incorrect peer dependency "react-native-screens@^1.0.0 || ^1.0.0-alpha".\n' +
    'warning " > reactotron-mst@3.1.3" has unmet peer dependency "reactotron-core-client@^2.5.0".\n' +
    'warning "@storybook/react-native > @storybook/client-api > @storybook/router@5.1.11" has unmet peer dependency "react-dom@*".\n' +
    'warning "@storybook/addon-storyshots > @storybook/addons > @storybook/api > @storybook/theming@5.1.11" has unmet peer dependency "react-dom@*".\n' +
    'warning "@storybook/addon-storyshots > @storybook/addons > @storybook/api > @storybook/router > @reach/router@1.2.1" has unmet peer dependency "react-dom@15.x || 16.x || 16.4.0-alpha.0911da3".\n' +
    'warning " > @typescript-eslint/eslint-plugin@1.13.0" has unmet peer dependency "eslint@^5.0.0".\n' +
    'warning "@typescript-eslint/eslint-plugin > @typescript-eslint/experimental-utils@1.13.0" has unmet peer dependency "eslint@*".\n' +
    'warning " > @typescript-eslint/parser@1.13.0" has unmet peer dependency "eslint@^5.0.0".\n' +
    'warning " > eslint-config-prettier@6.5.0" has unmet peer dependency "eslint@>=3.14.1".\n' +
    'warning " > eslint-config-standard@13.0.1" has unmet peer dependency "eslint@>=6.0.1".\n' +
    'warning " > eslint-plugin-import@2.18.2" has unmet peer dependency "eslint@2.x - 6.x".\n' +
    'warning " > eslint-plugin-node@9.2.0" has unmet peer dependency "eslint@>=5.16.0".\n' +
    'warning "eslint-plugin-node > eslint-plugin-es@1.4.1" has unmet peer dependency "eslint@>=4.19.1".\n' +
    'warning " > eslint-plugin-react@7.16.0" has unmet peer dependency "eslint@^3.0.0 || ^4.0.0 || ^5.0.0 || ^6.0.0".\n' +
    'warning " > eslint-plugin-react-native@3.8.1" has unmet peer dependency "eslint@^3.17.0 || ^4 || ^5 || ^6".\n' +
    'warning " > eslint-plugin-standard@4.0.1" has unmet peer dependency "eslint@>=5.0.0".\n' +
    'error Command failed with exit code 1.\n'
}
error installing boilerplate
MacBook-Pro:projects tnasuh$ ignite doctor
System
  platform           darwin                                                 
  arch               x64                                                    
  cpu                8 cores      Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz 
  directory          projects     /Users/tnasuh/Desktop/projects    

JavaScript
  node               12.13.0      /usr/local/bin/node 
  npm                6.12.0       /usr/local/bin/npm  
  yarn               1.19.1       /usr/local/bin/yarn 

Ignite
  ignite-cli         3.3.1        /usr/local/bin/ignite                                                   
  ignite src         build        /Users/tnasuh/.config/yarn/global/node_modules/ignite-cli/build 
  generators         {}                                                                                   

Android
  java               1.8.0_131    /usr/bin/java 
  android home       -            undefined     

iOS
  xcode              11.2       
  cocoapods          1.8.4        /usr/local/bin/pod 
MacBook-Pro:projects tnasuh$ 

```

**Comment by TnasuH** [comment]
Sorry guys.
I found solution.
The problem was caused by the macOS update to Catalina from Mojave.

I **re-installed** the following installation list using **sudo**. If try without sudo, problem is not solved.

node.js 13.0.1 (Latest)
brew install node
brew link --overwrite node
brew install watchman
sudo gem install cocoapods
brew install yarn
sudo yarn global add ignite-cli
