### ISSUE TITLE
[Bug] Can not Create new Project on Windows 10

### ISSUE THREAD

**Issue by conradkirschner** [infinitered/ignite#1502]
### Can not create new Project
---
What's going on?
I've installed ignite globally on Windows 10. 
Then I tried to use the wizzard to create a new project

---
- adding ignite-andross
- installing boilerplate
- using the Infinite Red boilerplate v2 (code name 'Andross')
√ using the Infinite Red boilerplate v2 (code name 'Andross')
- adding React Native 0.59.9 (30 seconds-ish)
√ added React Native 0.59.9 in 34.66s
an error occured while installing ignite-andross boilerplate.
Error: ENOENT: no such file or directory, chdir 'C:\Users\conrad\Desktop\programming project\react-native\ignite\NewsApi' -> 'NewsApi'
    at process.chdir (internal/process/main_thread_only.js:29:13)
    at Object.<anonymous> (C:\Users\conrad\AppData\Roaming\npm\node_modules\ignite-cli\build\extensions\reactNative.js:114:33)
    at step (C:\Users\conrad\AppData\Roaming\npm\node_modules\ignite-cli\build\extensions\reactNative.js:32:23)
    at Object.next (C:\Users\conrad\AppData\Roaming\npm\node_modules\ignite-cli\build\extensions\reactNative.js:13:53)
    at fulfilled (C:\Users\conrad\AppData\Roaming\npm\node_modules\ignite-cli\build\extensions\reactNative.js:4:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'chdir',
  path: 'C:\\Users\\conrad\\Desktop\\programming project\\react-native\\ignite\\NewsApi',
  dest: 'NewsApi'
}
error installing boilerplate

**Comment by conradkirschner** [comment]
to get it work, i had to install it **NOT GLOBAL** should be written into readme, or fixed (this only apears to andross)

**Comment by egemenkayalidere** [comment]
I have the same issue. How to solve it ?

**Comment by egemenkayalidere** [comment]
I found a solution. I reinstalled homebrew, node & npm, ignite-cli, react-native-cli and it worked !

**Comment by Venipa** [comment]
> I found a solution. I reinstalled homebrew, node & npm, ignite-cli, react-native-cli and it worked !

this issue is related to Windows 10, homebrew is for mac afaik so this is still unsolved for op.

im currently having the same issue on Windows 10 1903, the setup just stops afterwards
![image](https://user-images.githubusercontent.com/17952364/68688279-c356ab80-056e-11ea-96fc-1d1737350dfb.png)

**Comment by egemenkayalidere** [comment]
Yes, you are right and I know the homebrew is for mac too. I suggest you guys to use this way that you reinstall node & npm, ignite-cli, react-native-cli to solve your case. Forget homebrew.

**Comment by masonlin** [comment]
> I found a solution. I reinstalled homebrew, node & npm, ignite-cli, react-native-cli and it worked !

I have the same issue, and follow your suggest to uninstall all of those packages and reinstall to solve it. Thank you.
