### ISSUE TITLE
console.tron.log is undefined

### ISSUE THREAD

**Issue by tayfunyasar** [infinitered/ignite#1511]
ERROR:

> 12-03 13:42:38.436 18257-18277/? E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
>     Process: com.instaton, PID: 18257
>     com.facebook.react.common.JavascriptException: TypeError: undefined is not an object (evaluating 'console.tron.log'), stack:
>     <unknown>@1413:472
>     <unknown>@714:290
>     <unknown>@722:741
>     onPress@1282:1566
>     touchableHandlePress@214:2247
>     touchableHandlePress@-1
>     _performSideEffectsForTransition@205:9659
>     _performSideEffectsForTransition@-1
>     _receiveSignal@205:8341
>     _receiveSignal@-1
>     touchableHandleResponderRelease@205:5629
>     touchableHandleResponderRelease@-1
>     b@89:1197
>     k@89:1340
>     C@89:1394
>     N@89:1692
>     A@89:2482
>     forEach@-1
>     z@89:2282
>     <unknown>@89:13914
>     _e@89:88659
>     Ne@89:13582
>     Ue@89:13755
>     receiveTouches@89:14547
>     value@24:3685
>     <unknown>@24:841
>     value@24:2939
>     value@24:813
>     value@-1
>     
>         at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:71)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at java.lang.reflect.Method.invoke(Method.java:372)
>         at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:371)
>         at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:150)
>         at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
>         at android.os.Handler.handleCallback(Handler.java:739)
>         at android.os.Handler.dispatchMessage(Handler.java:95)
>         at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26)
>         at android.os.Looper.loop(Looper.java:145)
>         at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225)
>         at java.lang.Thread.run(Thread.java:818)

package.json
```

{
  "name": "instaton",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "clean": "rm -rf $TMPDIR/react-* && watchman watch-del-all && npm cache clean --force",
    "clean:android": "cd android/ && ./gradlew clean && cd .. && react-native run-android",
    "newclear": "rm -rf $TMPDIR/react-* && watchman watch-del-all && rm -rf ios/build && rm -rf node_modules/ && npm cache clean --force && npm i",
    "test:watch": "jest --watch",
    "updateSnapshot": "jest --updateSnapshot",
    "coverage": "jest --coverage && open coverage/lcov-report/index.html || xdg-open coverage/lcov-report/index.html",
    "android:build": "cd android && ./gradlew assembleRelease",
    "android:install": "cd android && ./gradlew assembleRelease && ./gradlew installRelease",
    "android:hockeyapp": "cd android && ./gradlew assembleRelease && puck -submit=auto app/build/outputs/apk/app-release.apk",
    "android:devices": "$ANDROID_HOME/platform-tools/adb devices",
    "android:logcat": "$ANDROID_HOME/platform-tools/adb logcat *:S ReactNative:V ReactNativeJS:V",
    "android:shake": "$ANDROID_HOME/platform-tools/adb devices | grep '\\t' | awk '{print $1}' | sed 's/\\s//g' | xargs -I {} $ANDROID_HOME/platform-tools/adb -s {} shell input keyevent 82",
    "storybook": "storybook start -p 7007",
    "lint": "standard --verbose | snazzy && eslint .",
    "lintdiff": "git diff --name-only --cached --relative | grep '\\.js$' | xargs standard | snazzy",
    "fixcode": "standard --fix",
    "git-hook": "npm run lint -s && npm run test -s",
    "eslint-check": "eslint --print-config App/Containers/TimelineScreen/index.js | eslint-config-prettier-check"
  },
  "dependencies": {
    "@react-native-community/geolocation": "^2.0.2",
    "apisauce": "^1.1.1",
    "format-json": "^1.0.3",
    "identity-obj-proxy": "^3.0.0",
    "lodash": "^4.17.11",
    "prop-types": "^15.6.1",
    "querystringify": "2.1.0",
    "ramda": "^0.26.1",
    "react": "16.8.1",
    "react-native": "0.61.3",
    "react-native-animatable": "^1.3.2",
    "react-native-config": "^0.11.7",
    "react-native-elements": "^1.1.0",
    "react-native-gesture-handler": "1.5.0",
    "react-native-i18n": "2.0.14",
    "react-native-permissions": "^2.0.4",
    "react-native-vector-icons": "^6.6.0",
    "react-native-video": "^5.0.2",
    "react-navigation": "3.11.0",
    "react-navigation-redux-helpers": "^3.0.2",
    "react-redux": "^6.0.0",
    "redux": "^4.0.0",
    "redux-saga": "^1.0.0",
    "reduxsauce": "1.0.1",
    "seamless-immutable": "^7.1.2"
  },
  "devDependencies": {
    "@babel/core": "^7.5.0",
    "@babel/runtime": "^7.5.0",
    "@react-native-community/eslint-config": "^0.0.3",
    "@storybook/addon-actions": "5.0.11",
    "@storybook/addon-links": "5.0.11",
    "@storybook/addon-storyshots": "^4.1.11",
    "@storybook/addons": "^4.1.11",
    "@storybook/channels": "^4.1.11",
    "@storybook/react-native": "^4.1.11",
    "babel-core": "6.26.3",
    "babel-eslint": "^7.2.3",
    "babel-jest": "^24.1.0",
    "babel-plugin-ignite-ignore-reactotron": "^0.3.0",
    "babel-preset-env": "^1.6.1",
    "babel-preset-react-native": "^4.0.1",
    "enzyme": "^3.2.0",
    "enzyme-adapter-react-16": "^1.1.0",
    "eslint-config-airbnb": "^18.0.1",
    "eslint-config-babel": "^9.0.0",
    "eslint-config-prettier": "^6.3.0",
    "eslint-plugin-babel": "^5.3.0",
    "eslint-plugin-flowtype": "^4.3.0",
    "eslint-plugin-import": "^2.18.2",
    "eslint-plugin-jsx-a11y": "^6.2.3",
    "eslint-plugin-prettier": "^3.1.0",
    "eslint-plugin-react": "^7.14.3",
    "eslint-plugin-standard": "^4.0.1",
    "eslint-plugin-unicorn": "^11.0.1",
    "ignite-andross": "^4.1.0",
    "ignite-animatable": "1.0.2",
    "ignite-i18n": "1.2.0",
    "ignite-standard": "1.0.0",
    "jest": "^24.1.0",
    "metro-react-native-babel-preset": "^0.51.1",
    "mockery": "^2.1.0",
    "prettier": "^1.18.2",
    "prettier-eslint": "^9.0.0",
    "react-devtools-core": "3.6.0",
    "react-dom": "16.7.0",
    "react-test-renderer": "16.8.1",
    "reactotron-react-native": "^2.1.0",
    "reactotron-redux": "^2.1.0",
    "reactotron-redux-saga": "^3.0.0",
    "snazzy": "^8.0.0",
    "standard": "10.0.2"
  },
  "jest": {
    "preset": "react-native",
    "testMatch": [
      "<rootDir>/Tests/**/*.js",
      "**/?(*.)(spec|test).js?(x)"
    ],
    "testPathIgnorePatterns": [
      "/node_modules/",
      "<rootDir>/Tests/Setup.js"
    ],
    "moduleNameMapper": {
      "^.+\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$": "identity-obj-proxy"
    },
    "transform": {
      "^.+\\.(js)$": "<rootDir>/node_modules/react-native/jest/preprocessor.js"
    },
    "setupFiles": [
      "<rootDir>/Tests/Setup"
    ]
  },
  "config": {},
  "standard": {
    "parser": "babel-eslint",
    "globals": [
      "describe",
      "test",
      "jest",
      "expect",
      "fetch",
      "navigator",
      "__DEV__",
      "XMLHttpRequest",
      "FormData",
      "React$Element"
    ]
  }
}

```

I think Reactotron dependencies should be in prod dependencies. What do you think?

**Comment by tayfunyasar** [comment]
I commented out bold sections. And it worked.

App/Redux/ScreenTrackingMiddleware.js

import { NavigationActions } from 'react-navigation'

```
// gets the current screen from navigation state
const getCurrentRouteName = (navigationState) => {
  if (!navigationState) {
    return null
  }
  const route = navigationState.routes[navigationState.index]
  // dive into nested navigators
  if (route.routes) {
    return getCurrentRouteName(route)
  }
  return route.routeName
}

const screenTracking = ({ getState }) => next => (action) => {
  if (
    action.type !== NavigationActions.NAVIGATE &&
    action.type !== NavigationActions.BACK
  ) {
    return next(action)
  }

  const currentScreen = getCurrentRouteName(getState().nav)
  const result = next(action)
  const nextScreen = getCurrentRouteName(getState().nav)
  if (nextScreen !== currentScreen) {
    try {
      **console.tron.log(`NAVIGATING ${currentScreen} to ${nextScreen}`)**
      // Example: Analytics.trackEvent('user_navigation', {currentScreen, nextScreen})
    } catch (e) {
      **console.tron.log(e)**
    }
  }
  return result
}

export default screenTracking

```

**Comment by tayfunyasar** [comment]
there is a plugin for it. Ignite shouldnt require any extra plugin.

https://github.com/infinitered/babel-plugin-ignite-ignore-reactotron

**Comment by ruddell** [comment]
This only affects the `ignite-andross` boilerplate.  The babel plugin has not been updated since 2017 so I don't think it will work.

You can see how `ignite-bowser` prevents Reactotron crashes in prod in [reactotron.ts#L22-L48](https://github.com/infinitered/ignite-bowser/blob/e8b5d9ed941c3d374b39da0f0b7435918866affc/boilerplate/app/services/reactotron/reactotron.ts#L22-L48). Doing something similar in your app will help. 

This should be added to the boilerplate if anyone has time for a pull request.

**Comment by kevinvangelder** [comment]
@tayfunyasar Reactotron is purposely excluded from running in production by default because it provides access to behind the scenes information, which if someone discovered in your production app could be harmful to your business (for example, they might be able to bypass payment requirements to access premium content or delete data from your database bypassing user type checks). If you want to run Reactotron in production you need to set that up manually.

**Comment by tayfunyasar** [comment]
Thats why i got this error when i run app in debug mode on my real device. Thanks for details.

**Comment by egemenkayalidere** [comment]
To solve this problem easily my suggestion is, search in your project for "console.tron.log" and add if condition to check either your project is in DEV mode or not. You can do this simply by using  "__DEV__ && console.tron.log()"

Thanks

**Comment by okcompewter** [comment]
I am using ignite-bowser in my project, but ran into this same problem yesterday after making my first release bundle. Like you said, @ruddell , I see the code in [reactotron.ts#L22-L48](https://github.com/infinitered/ignite-bowser/blob/e8b5d9ed941c3d374b39da0f0b7435918866affc/boilerplate/app/services/reactotron/reactotron.ts#L22-L48), but it doesn't seem be mocking out the `console.tron.log` properly, as it still crashes and I see this message using `adb logcat *:S ReactNative:V ReactNativeJS:V`:

`01-05 17:57:55.658 21146 21197 E ReactNativeJS: TypeError: undefined is not an object (evaluating 'console.tron.log')`

The only solution that seems to work is by prefixing each use like so:

`if (__DEV__) console.tron.log('test')`

Any ideas why the mocked `tron` if `!__DEV__` is not working?

**Comment by loiclouvet** [comment]
Same issue on ignite-bowser after an upgrade to v4.13.0.

`reactotron.ts` does clearly mock `console.tron` object in production mode but `reactotron.ts` is only imported in dev mode following `environment.ts` code source : 
```
if (__DEV__) {
  const { Reactotron } = require("../services/reactotron")
  ReactotronDev = Reactotron
}
```
That's why in production mode, console.tron is undefined

### 2 solutions
1. We only call console.tron methods in dev mode like @egemenkayalidere  suggests : 
`__DEV__ && console.tron...` and you can remove every `if (__DEV)` conditions in `reacotron.ts`.

1. We remove the conditional import in environment.ts, e.g. : 
```
const { Reactotron } = require("../services/reactotron")
const ReactotronDev = Reactotron
```

Solution 2 is safer in my opinion.
