### ISSUE TITLE
Ignite bowser was not able to be installed. Is it a valid NPM module?

### ISSUE THREAD

**Issue by dpaulino** [infinitered/ignite#1512]
What's going on?
I'm trying to create a new ignite app using bowser but I'm getting an error.
```
  stderr:
   '- \n- adding \u001b[36mignite-bowser\u001b[39m\n× \u001b[31mignite-bowser\u001b[39m was not able to be installed. Is it a valid NPM module?',
```
 Here's the full `--debug` log:
```
PS r2v2> ignite new testapp --debug
-----------------------------------------------
  (                  )   (
  )\ )   (        ( /(   )\ )    *   )
 (()/(   )\ )     )\()) (()/(  ` )  /(   (
  /(_)) (()/(    ((_)\   /(_))  ( )(_))  )\
 (_))    /(_))_   _((_) (_))   (_(_())  ((_)
 |_ _|  (_)) __| | \| | |_ _|  |_   _|  | __|
  | |     | (_ | | .` |  | |     | |    | _|
 |___|     \___| |_|\_| |___|    |_|    |___|
-----------------------------------------------

An unfair headstart for your React Native apps.
https://infinite.red/ignite

-----------------------------------------------

🔥 igniting app testapp
√ Which boilerplate would you like to use? · ignite-bowser
21:10:36 [ignite] making directory C:\Users\dapaulin\source\repos\r2v2\testapp
21:10:36 [ignite] switched directory to C:\Users\dapaulin\source\repos\r2v2\testapp
21:10:36 [ignite] running boilerplate-install command
\ adding ignite-bowser21:10:39 [ignite] ignite-bowser 4.11.3 on npm.
21:10:39 [ignite] yarn add ignite-bowser --dev
| adding ignite-bowser21:10:41 [ignite] finished yarn command
√ using the Infinite Red boilerplate v3 (code name 'Bowser')
21:10:41 [ignite] initializing react native
21:10:41 [ignite] npx react-native init testapp --version 0.61.2

               ######                ######
             ###     ####        ####     ###
            ##          ###    ###          ##
            ##             ####             ##
            ##             ####             ##
            ##           ##    ##           ##
            ##         ###      ###         ##
             ##  ########################  ##
          ######    ###            ###    ######
      ###     ##    ##              ##    ##     ###
   ###         ## ###      ####      ### ##         ###
  ##           ####      ########      ####           ##
 ##             ###     ##########     ###             ##
  ##           ####      ########      ####           ##
   ###         ## ###      ####      ### ##         ###
      ###     ##    ##              ##    ##     ###
          ######    ###            ###    ######
             ##  ########################  ##
            ##         ###      ###         ##
            ##           ##    ##           ##
            ##             ####             ##
            ##             ####             ##
            ##          ###    ###          ##
             ###     ####        ####     ###
               ######                ######


                  Welcome to React Native!
                 Learn once, write anywhere

√ Downloading template
√ Copying template
√ Processing template
√ Installing dependencies

  Run instructions for iOS:
    • cd C:\Users\dapaulin\source\repos\r2v2\testapp\testapp && npx react-native run-ios
    - or -
    • Open testapp\ios\testapp.xcodeproj in Xcode or run "xed -b ios"
    • Hit the Run button

  Run instructions for Android:
    • Have an Android emulator running (quickest way to get started), or a device connected.
    • cd C:\Users\dapaulin\source\repos\r2v2\testapp\testapp && npx react-native run-android

21:11:30 [ignite] done
√ added React Native 0.61.2 in 48.86s
21:11:30 [ignite] changed to directory C:\Users\dapaulin\source\repos\r2v2\testapp\testapp
21:11:30 [ignite] merging Bowser package.json with React Native package.json
21:11:30 [ignite] writing newly merged package.json
21:11:30 [ignite] adding boilerplate to project for generator commands
21:11:42 [ignite]
  Error: Command failed with exit code 2: ignite add ignite-bowser --debug

  - error.js:56 makeError
    [global]/[gluegun]/[execa]/lib/error.js:56:11

  - index.js:114 handlePromise
    [global]/[gluegun]/[execa]/index.js:114:26

  - next_tick.js:77 process.internalTickCallback
    internal/process/next_tick.js:77:7



      There were errors while generating the project. Run with --debug to see verbose output.

an error occured while installing ignite-bowser boilerplate.
{ Error: Command failed with exit code 2: ignite add ignite-bowser --debug
    at makeError (C:\Users\dapaulin\AppData\Local\Yarn\Data\global\node_modules\gluegun\node_modules\execa\lib\error.js:56:11)
    at handlePromise (C:\Users\dapaulin\AppData\Local\Yarn\Data\global\node_modules\gluegun\node_modules\execa\index.js:114:26)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
  command: 'ignite add ignite-bowser --debug',
  exitCode: 2,
  signal: undefined,
  signalDescription: undefined,
  stdout:
   '\u001b[90m21:11:32\u001b[39m \u001b[35m[ignite]\u001b[39m running add command\n\u001b[90m21:11:32\u001b[39m \u001b[35m[ignite]\u001b[39m installing C:\\Users\\dapaulin\\source\\repos\\r2v2\\testapp\\testapp/node_modules/ignite-bowser from source npm\n\u001b[90m21:11:35\u001b[39m \u001b[35m[ignite]\u001b[39m ignite-bowser 4.11.3 on npm.\n\u001b[90m21:11:35\u001b[39m \u001b[35m[ignite]\u001b[39m yarn add ignite-bowser --dev\n\u001b[31m----------\u001b[39m\n\u001b[31mCommand failed: yarn add ignite-bowser --dev\u001b[39m\n\u001b[31mwarning @types/jest > @types/jest-diff@24.3.0: This is a stub types definition. jest-diff provides its own type definitions, so you do not need this installed.\u001b[39m\n\u001b[31mwarning solidarity > gluegun > enquirer > set-value@1.0.0: Critical bug fixed in v3.0.1, please upgrade to the latest version.\u001b[39m\n\u001b[31mwarning solidarity > gluegun > prompt-autocompletion > prompt-choices > set-value@0.4.3: Critical bug fixed in v3.0.1, please upgrade to the latest version.\u001b[39m\n\u001b[31mwarning solidarity > gluegun > enquirer > prompt-question > prompt-choices > set-value@1.0.0: Critical bug fixed in v3.0.1, please upgrade to the latest version.\u001b[39m\n\u001b[31merror eslint@6.7.2: The engine "node" is incompatible with this module. Expected version "^8.10.0 || ^10.13.0 || >=11.10.1". Got "11.0.0"\u001b[39m\n\u001b[31merror Found incompatible module.\u001b[39m\n\u001b[31m\u001b[39m\n\u001b[31m----------\u001b[39m',
  stderr:
   '- \n- adding \u001b[36mignite-bowser\u001b[39m\n× \u001b[31mignite-bowser\u001b[39m was not able to be installed. Is it a valid NPM module?',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false }
error installing boilerplate
```
---
Steps to reproduce

1. Run `ignite new testapp --debug`
---
`ignite doctor` results:
```
PS r2v2> ignite doctor
System
  platform           win32
  arch               x64
  cpu                12 cores     Intel(R) Xeon(R) CPU E5-1650 v4 @ 3.60GHz
  directory          r2v2         C:\Users\dapaulin\source\repos\r2v2

JavaScript
  node               11.0.0       C:\Program Files\nodejs\node.EXE
  npm                6.11.3       C:\Program Files\nodejs\npm.CMD
  yarn               1.19.2       C:\Program Files (x86)\Yarn\bin\yarn.CMD

Ignite
  ignite-cli         3.3.1        C:\Users\dapaulin\AppData\Local\Yarn\bin\ignite.CMD
  ignite src         build        C:\Users\dapaulin\AppData\Local\Yarn\Data\global\node_modules\ignite-cli\build
  generators         {}

Android
  java               -            null
  android home       -            C:\Users\dapaulin\AppData\Local\Android\Sdk
```

**Comment by ruddell** [comment]
I see in the `stdout ` the error message: `The engine "node" is incompatible with this module. Expected version "^8.10.0 || ^10.13.0 || >=11.10.1". Got "11.0.0"` . It would be nice if Ignite prints this error in a readable format.

Does it work if you upgrade `node` to an acceptable version?

**Comment by dpaulino** [comment]
@ruddell I completely missed that due to my unfamiliarity with ignite. Thanks, I'll try updating node.

**Comment by dpaulino** [comment]
Updating to node v13.3.0 worked! Thanks again @ruddell!

**Comment by xavixie** [comment]
the same problem, update node v13.8.0 not work.
