### ISSUE TITLE
coordinatorlayout download error

### ISSUE THREAD

**Issue by bepehr** [infinitered/ignite#1521]
What's going on?
when is run npx react-native run-android i get this error:
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 976 file(s) to forward-jetify. Using 8 workers...

> Configure project :react-native-splash-screen
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
WARNING: Configuration 'testCompile' is obsolete and has been replaced with 'testImplementation'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
WARNING: The specified Android SDK Build Tools version (26.0.3) is ignored, as it is below the minimum supported version (28.0.3) for Android Gradle Plugin 3.4.2.
Android SDK Build Tools 28.0.3 will be used.
To suppress this warning, remove "buildToolsVersion '26.0.3'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.

> Task :react-native-screens:javaPreCompileDebug FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.5/userguide/command_line_interface.html#sec:command_line_warnings
55 actionable tasks: 2 executed, 53 up-to-date

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-screens:javaPreCompileDebug'.
> Could not resolve all files for configuration ':react-native-screens:debugCompileClasspath'.
   > Could not find coordinatorlayout.jar (androidx.coordinatorlayout:coordinatorlayout:1.0.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/androidx/coordinatorlayout/coordinatorlayout/1.0.0/coordinatorlayout-1.0.0.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s

error Failed to install the app. Make sure you have the Android development environment set up: https://facebook.github.io/react-native/docs/getting-started.html#android-development-environment. Run CLI with --verbose flag for more details.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-screens:javaPreCompileDebug'.
> Could not resolve all files for configuration ':react-native-screens:debugCompileClasspath'.
   > Could not find coordinatorlayout.jar (androidx.coordinatorlayout:coordinatorlayout:1.0.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/androidx/coordinatorlayout/coordinatorlayout/1.0.0/coordinatorlayout-1.0.0.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s

    at checkExecSyncError (child_process.js:629:11)
    at execFileSync (child_process.js:647:13)
    at runOnAllDevices (C:\Work\React Native\test4\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:94:39)
    at buildAndRun (C:\Work\React Native\test4\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\index.js:158:41)
    at then.result (C:\Work\React Native\test4\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\index.js:125:12)
    at process._tickCallback (internal/process/next_tick.js:68:7)

any problem is google gets 404 error on this url
https://dl.google.com/dl/android/maven2/androidx/coordinatorlayout/coordinatorlayout/1.0.0/coordinatorlayout-1.0.0.jar

---
Steps to reproduce
I just create a new project with this commands
ignite new test4
template is Bowser
cd test4
npx react-native run-android

---
`ignite doctor` results:
System
  platform           win32
  arch               x64
  cpu                8 cores      AMD FX(tm)-8350 Eight-Core Processor
  directory          test4        C:\Work\React Native\test4

JavaScript
  node               10.17.0      C:\Program Files\nodejs\node.EXE
  npm                6.11.3       C:\Program Files\nodejs\npm.CMD
  yarn               1.19.2       C:\Program Files (x86)\Yarn\bin\yarn.CMD

Ignite
  ignite-cli           3.4.0                                                                                                        C:\Users\bepeh\AppData\Local\Yarn\bin\ignite.CMD
  ignite src           build                                                                                                        C:\Users\bepeh\AppData\Local\Yarn\Data\global\node_modules\ignite-cli\build
  navigation           react-navigation
  generators           {"component":"ignite-bowser","model":"ignite-bowser","navigator":"ignite-bowser","screen":"ignite-bowser"}
  createdWith          3.4.0
  boilerplate          ignite-bowser
  boilerplateVersion   4.11.3

Android
  java               -            C:\Program Files (x86)\Common Files\Oracle\Java\javapath\java.EXE
  android home       -            H:\Android\sdk

**Comment by bepehr** [comment]
I found my solution in this [link ](https://github.com/kmagiera/react-native-screens/issues/213)
