### ISSUE TITLE
Creation of app with name "Test" fails

### ISSUE THREAD

**Issue by immackay** [infinitered/ignite#1522]
---
When creating a new app using the name "Test", the tests directory, tsconfig.json, and yarn.lock fail to be moved to the parent directory during initialization.

```
  Error: ENOTEMPTY: directory not empty, rename '/Users/ian/Documents/Workspace/Test/Test/test' ->   '/Users/ian/Documents/Workspace/Test/test'
  
  - fs.js:665 Object.renameSync
    fs.js:665:3
  
  - move.js:27 Object.moveSync [as sync]
    [global]/[gluegun]/[fs-jetpack]/lib/move.js:27:8
  
  - jetpack.js:179 Object.move
    [global]/[gluegun]/[fs-jetpack]/lib/jetpack.js:179:12
  
  - new.js:201 
    [global]/[ignite-cli]/build/commands/new.js:201:40
  
  - Array.forEach
  
  - new.js:199 Command.<anonymous>
    [global]/[ignite-cli]/build/commands/new.js:199:35
  
  - new.js:32 step
    [global]/[ignite-cli]/build/commands/new.js:32:23
  
  - new.js:13 Object.next
    [global]/[ignite-cli]/build/commands/new.js:13:53
  
  - new.js:4 fulfilled
    [global]/[ignite-cli]/build/commands/new.js:4:58
  

/Users/ian/.config/yarn/global/node_modules/gluegun/build/index.js:13
    throw up;
    ^

Error: ENOTEMPTY: directory not empty, rename '/Users/ian/Documents/Workspace/Test/Test/test' -> '/Users/ian/Documents/Workspace/Test/test'
    at Object.renameSync (fs.js:665:3)
    at Object.moveSync [as sync] (/Users/ian/.config/yarn/global/node_modules/gluegun/node_modules/fs-jetpack/lib/move.js:27:8)
    at Object.move (/Users/ian/.config/yarn/global/node_modules/gluegun/node_modules/fs-jetpack/lib/jetpack.js:179:12)
    at /Users/ian/.config/yarn/global/node_modules/ignite-cli/build/commands/new.js:201:40
    at Array.forEach (<anonymous>)
    at Command.<anonymous> (/Users/ian/.config/yarn/global/node_modules/ignite-cli/build/commands/new.js:199:35)
    at step (/Users/ian/.config/yarn/global/node_modules/ignite-cli/build/commands/new.js:32:23)
    at Object.next (/Users/ian/.config/yarn/global/node_modules/ignite-cli/build/commands/new.js:13:53)
    at fulfilled (/Users/ian/.config/yarn/global/node_modules/ignite-cli/build/commands/new.js:4:58) {
  errno: -66,
  syscall: 'rename',
  code: 'ENOTEMPTY',
  path: '/Users/ian/Documents/Workspace/Test/Test/test',
  dest: '/Users/ian/Documents/Workspace/Test/test'
}
```

---
Steps to reproduce:

`npx ignite new Test -b bowser`

Press `y` when prompted for detox tests.

**Comment by immackay** [comment]
Looks like this is due to case-insensitive file paths. Perhaps the proto-app directory could be given a different name than the resultant name of the app? 

Either way, this is far from a major issue.

**Comment by mlaco** [comment]
Hey @immackay ! Thanks for filing the issue. I've just come off a project and have some time to address some Ignite issues. I can play around with this for a short time, but since it's a very fringe case (as you said), I think it'll be a low priority.

**Comment by bryanstearns** [comment]
Closing - this got stale, but with Ignite 6.2.0, both `ignite new test` and `ignite new Test` succeed and pass tests.
