### ISSUE TITLE
Getting "an error occured while installing ignite-bowser boilerplate." message

### ISSUE THREAD

**Issue by psaikali** [infinitered/ignite#1523]
When creating a new app with `ignite-bowser` boilerplate (RN 0.61.2), the first part of the process works fine:

```
🔥 igniting app EcouterLaRadioApp
✔ Which boilerplate would you like to use? · ignite-bowser
✔ using the Infinite Red boilerplate v3 (code name 'Bowser')
✔ Would you like to include Detox end-to-end tests? (y/N) · false
✔ added React Native 0.61.2 in 124.75s
```

But then I'm getting an error when the process is trying to install the libraries.

```
an error occured while installing ignite-bowser boilerplate.
Error: Command failed: yarn
warning You are using Node "13.5.0" which is not supported and may encounter bugs or unexpected behavior. Yarn supports the following semver range: "^4.8.0 || ^5.7.0 || ^6.2.2 || ^8.0.0"
(node:91738) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
/usr/local/Cellar/ruby/2.5.0/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': dlopen(/usr/local/Cellar/ruby/2.5.0/lib/ruby/2.5.0/x86_64-darwin17/openssl.bundle, 9): Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib (LoadError)
  Referenced from: /usr/local/Cellar/ruby/2.5.0/lib/ruby/2.5.0/x86_64-darwin17/openssl.bundle
  Reason: image not found - /usr/local/Cellar/ruby/2.5.0/lib/ruby/2.5.0/x86_64-darwin17/openssl.bundle
	from /usr/local/Cellar/ruby/2.5.0/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /usr/local/Cellar/ruby/2.5.0/lib/ruby/2.5.0/openssl.rb:13:in `<top (required)>'
	from /usr/local/Cellar/ruby/2.5.0/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /usr/local/Cellar/ruby/2.5.0/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /usr/local/Cellar/ruby/2.5.0/lib/ruby/2.5.0/net/http.rb:970:in `connect'
	from /usr/local/Cellar/ruby/2.5.0/lib/ruby/2.5.0/net/http.rb:920:in `do_start'
	from /usr/local/Cellar/ruby/2.5.0/lib/ruby/2.5.0/net/http.rb:909:in `start'
	from /usr/local/Cellar/ruby/2.5.0/lib/ruby/2.5.0/net/http.rb:1455:in `request'
	from /usr/local/lib/ruby/gems/2.5.0/gems/gh_inspector-1.1.3/lib/gh_inspector/sidekick.rb:84:in `get_api_results'
	from /usr/local/lib/ruby/gems/2.5.0/gems/gh_inspector-1.1.3/lib/gh_inspector/sidekick.rb:28:in `search'
	from /usr/local/lib/ruby/gems/2.5.0/gems/gh_inspector-1.1.3/lib/gh_inspector/inspector.rb:68:in `search_query'
	from /usr/local/lib/ruby/gems/2.5.0/gems/gh_inspector-1.1.3/lib/gh_inspector/inspector.rb:62:in `search_exception'
	from /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.7.5/lib/cocoapods/user_interface/error_report.rb:119:in `search_for_exceptions'
	from /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.7.5/lib/cocoapods/command.rb:67:in `report_error'
	from /usr/local/lib/ruby/gems/2.5.0/gems/claide-1.0.3/lib/claide/command.rb:396:in `handle_exception'
	from /usr/local/lib/ruby/gems/2.5.0/gems/claide-1.0.3/lib/claide/command.rb:337:in `rescue in run'
	from /usr/local/lib/ruby/gems/2.5.0/gems/claide-1.0.3/lib/claide/command.rb:324:in `run'
	from /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.7.5/lib/cocoapods/command.rb:52:in `run'
	from /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.7.5/bin/pod:55:in `<top (required)>'
	from /usr/local/bin/pod:23:in `load'
	from /usr/local/bin/pod:23:in `<main>'
error Command failed with exit code 1.

    at ChildProcess.exithandler (child_process.js:302:12)
    at ChildProcess.emit (events.js:305:20)
    at maybeClose (internal/child_process.js:1028:16)
    at Socket.<anonymous> (internal/child_process.js:443:11)
    at Socket.emit (events.js:305:20)
    at Pipe.<anonymous> (net.js:667:12) {
  killed: false,
  code: 1,
  signal: null,
  cmd: 'yarn',
  stderr: 'warning You are using Node "13.5.0" which is not supported and may encounter bugs or unexpected behavior. Yarn supports the following semver range: "^4.8.0 || ^5.7.0 || ^6.2.2 || ^8.0.0"\n' +
    '(node:91738) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.\n' +
    "/usr/local/Cellar/ruby/2.5.0/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': dlopen(/usr/local/Cellar/ruby/2.5.0/lib/ruby/2.5.0/x86_64-darwin17/openssl.bundle, 9): Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib (LoadError)\n" +
    '  Referenced from: /usr/local/Cellar/ruby/2.5.0/lib/ruby/2.5.0/x86_64-darwin17/openssl.bundle\n' +
    '  Reason: image not found - /usr/local/Cellar/ruby/2.5.0/lib/ruby/2.5.0/x86_64-darwin17/openssl.bundle\n' +
    "\tfrom /usr/local/Cellar/ruby/2.5.0/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'\n" +
    "\tfrom /usr/local/Cellar/ruby/2.5.0/lib/ruby/2.5.0/openssl.rb:13:in `<top (required)>'\n" +
    "\tfrom /usr/local/Cellar/ruby/2.5.0/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'\n" +
    "\tfrom /usr/local/Cellar/ruby/2.5.0/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'\n" +
    "\tfrom /usr/local/Cellar/ruby/2.5.0/lib/ruby/2.5.0/net/http.rb:970:in `connect'\n" +
    "\tfrom /usr/local/Cellar/ruby/2.5.0/lib/ruby/2.5.0/net/http.rb:920:in `do_start'\n" +
    "\tfrom /usr/local/Cellar/ruby/2.5.0/lib/ruby/2.5.0/net/http.rb:909:in `start'\n" +
    "\tfrom /usr/local/Cellar/ruby/2.5.0/lib/ruby/2.5.0/net/http.rb:1455:in `request'\n" +
    "\tfrom /usr/local/lib/ruby/gems/2.5.0/gems/gh_inspector-1.1.3/lib/gh_inspector/sidekick.rb:84:in `get_api_results'\n" +
    "\tfrom /usr/local/lib/ruby/gems/2.5.0/gems/gh_inspector-1.1.3/lib/gh_inspector/sidekick.rb:28:in `search'\n" +
    "\tfrom /usr/local/lib/ruby/gems/2.5.0/gems/gh_inspector-1.1.3/lib/gh_inspector/inspector.rb:68:in `search_query'\n" +
    "\tfrom /usr/local/lib/ruby/gems/2.5.0/gems/gh_inspector-1.1.3/lib/gh_inspector/inspector.rb:62:in `search_exception'\n" +
    "\tfrom /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.7.5/lib/cocoapods/user_interface/error_report.rb:119:in `search_for_exceptions'\n" +
    "\tfrom /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.7.5/lib/cocoapods/command.rb:67:in `report_error'\n" +
    "\tfrom /usr/local/lib/ruby/gems/2.5.0/gems/claide-1.0.3/lib/claide/command.rb:396:in `handle_exception'\n" +
    "\tfrom /usr/local/lib/ruby/gems/2.5.0/gems/claide-1.0.3/lib/claide/command.rb:337:in `rescue in run'\n" +
    "\tfrom /usr/local/lib/ruby/gems/2.5.0/gems/claide-1.0.3/lib/claide/command.rb:324:in `run'\n" +
    "\tfrom /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.7.5/lib/cocoapods/command.rb:52:in `run'\n" +
    "\tfrom /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.7.5/bin/pod:55:in `<top (required)>'\n" +
    "\tfrom /usr/local/bin/pod:23:in `load'\n" +
    "\tfrom /usr/local/bin/pod:23:in `<main>'\n" +
    'error Command failed with exit code 1.\n'
}
error installing boilerplate
```

Thanks for your help!

**Comment by mlaco** [comment]
Hey sorry you're having trouble @psaikali. We will try to reproduce the issue.

**Comment by fpena** [comment]
I'm getting this same error when using the latest version, `3.1.5`. My node version is `8.16.0`.

**Comment by fpena** [comment]
I did upgrade my Cocoapods version to `1.7.0.beta.3` and it started working again.

**Comment by mlaco** [comment]
@fpena That's good to hear! Do you mind if we close this issue then? Will you be good now that you're using the new Cocoapods version? (We can open it back up if not)
(Sorry for delay, I've been out of office for a while)
