### ISSUE TITLE
No generators found

### ISSUE THREAD

**Issue by tmaly1980** [infinitered/ignite#1567]
It looks like the ignite CLI doesn't even read the ignite/ignite.json file under the "generate" command. I just get a "No generators found" error. I've tried adding in a syntax error to ignite/ignite.json and "ignite generate" doesn't show a problem whereas "ignite doctor" does load the config file and shows an error.

Where are the generators loaded from? It's not even trying to load them from ignite/ignite.json . I had it working for a while but then changed to a fork of ignite-bowser, then it broke. I am able to find loadIgniteConfig() in build/commands/doctor.js but cannot find it in build/commands/generate.js

Is there some sort of caching going on? 

---
Steps to reproduce

```
ignite new TestProject
```

edit ignite/ignite.json to include:

```
{
SYNTAXERROR
  "navigation": "react-navigation",
  "generators": {
    "component": "ignite-bowser",
    "model": "ignite-bowser",
    "screen": "ignite-bowser"
  },
  "createdWith": "3.1.5",
  "boilerplate": "ignite-bowser",
  "boilerplateVersion": "5.3.0"
}
```

ignite doctor shows a parsing error, while ignite generate does not (ie doesn't even try to load the config file):

```

⚠️  No generators detected.

  Generators allow you to quickly make frequently created files such as:

    * components
    * screens
    * models
    * and more

  --------------------------------------------------------------------------
  Check out https://github.com/infinitered/ignite for more information
  or join our Slack community at http://community.infinite.red.
```

---
`ignite doctor` results:

System
  platform           darwin                                                   
  arch               x64                                                      
  cpu                12 cores        Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz 
  directory          HungryMonster   /Users/tomas/sites/TestProject         

JavaScript
  node               14.13.0      /usr/local/bin/node 
  npm                6.14.8       /usr/local/bin/npm  
  yarn               1.22.5       /usr/local/bin/yarn 
  Error: JSON parsing failed while reading /Users/tomas/sites/TestProject/ignite/ignite.json [SyntaxError: Unexpected token P in JSON at position 2]
  
  - read.js:38 makeNicerJsonParsingError
    [global]/[gluegun]/[fs-jetpack]/lib/read.js:38:22
  
  - read.js:76 Object.readSync [as sync]
    [global]/[gluegun]/[fs-jetpack]/lib/read.js:76:11
  
  - jetpack.js:188 Object.read
    [global]/[gluegun]/[fs-jetpack]/lib/jetpack.js:188:19
  
  - ignite-config.js:11 Object.loadIgniteConfig
    [global]/[ignite-cli]/build/extensions/ignite/ignite-config.js:11:69
  
  - doctor.js:108 Command.<anonymous>
    [global]/[ignite-cli]/build/commands/doctor.js:108:45
  
  - doctor.js:32 step
    [global]/[ignite-cli]/build/commands/doctor.js:32:23
  
  - doctor.js:13 Object.next
    [global]/[ignite-cli]/build/commands/doctor.js:13:53
  
  - doctor.js:4 fulfilled
    [global]/[ignite-cli]/build/commands/doctor.js:4:58
  
  - task_queues.js:93 processTicksAndRejections
    internal/process/task_queues.js:93:5
  

/Users/tomas/.config/yarn/global/node_modules/gluegun/build/index.js:13
    throw up;
    ^

Error: JSON parsing failed while reading /Users/tomas/sites/TestProject/ignite/ignite.json [SyntaxError: Unexpected token P in JSON at position 2]
    at makeNicerJsonParsingError (/Users/tomas/.config/yarn/global/node_modules/gluegun/node_modules/fs-jetpack/lib/read.js:38:22)
    at Object.readSync [as sync] (/Users/tomas/.config/yarn/global/node_modules/gluegun/node_modules/fs-jetpack/lib/read.js:76:11)
    at Object.read (/Users/tomas/.config/yarn/global/node_modules/gluegun/node_modules/fs-jetpack/lib/jetpack.js:188:19)
    at Object.loadIgniteConfig (/Users/tomas/.config/yarn/global/node_modules/ignite-cli/build/extensions/ignite/ignite-config.js:11:69)
    at Command.<anonymous> (/Users/tomas/.config/yarn/global/node_modules/ignite-cli/build/commands/doctor.js:108:45)
    at step (/Users/tomas/.config/yarn/global/node_modules/ignite-cli/build/commands/doctor.js:32:23)
    at Object.next (/Users/tomas/.config/yarn/global/node_modules/ignite-cli/build/commands/doctor.js:13:53)
    at fulfilled (/Users/tomas/.config/yarn/global/node_modules/ignite-cli/build/commands/doctor.js:4:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  originalError: SyntaxError: Unexpected token P in JSON at position 2
      at JSON.parse (<anonymous>)
      at Object.readSync [as sync] (/Users/tomas/.config/yarn/global/node_modules/gluegun/node_modules/fs-jetpack/lib/read.js:71:19)
      at Object.read (/Users/tomas/.config/yarn/global/node_modules/gluegun/node_modules/fs-jetpack/lib/jetpack.js:188:19)
      at Object.loadIgniteConfig (/Users/tomas/.config/yarn/global/node_modules/ignite-cli/build/extensions/ignite/ignite-config.js:11:69)
      at Command.<anonymous> (/Users/tomas/.config/yarn/global/node_modules/ignite-cli/build/commands/doctor.js:108:45)
      at step (/Users/tomas/.config/yarn/global/node_modules/ignite-cli/build/commands/doctor.js:32:23)
      at Object.next (/Users/tomas/.config/yarn/global/node_modules/ignite-cli/build/commands/doctor.js:13:53)
      at fulfilled (/Users/tomas/.config/yarn/global/node_modules/ignite-cli/build/commands/doctor.js:4:58)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
}

**Comment by tmaly1980** [comment]
Looks like I needed to run "npm install" and "yarn build" for my custom boilerplate, and then publish to npmjs via "npm login" and "npm publish". It seems the generators expect to be found under build/commands, rather than src/commands . Thus any cloning of the boilerplate will fail unless the build folder is compiled/included.
