### ISSUE TITLE
Missing .gitignore file in boilerplate

### ISSUE THREAD

**Issue by eugenemlee** [infinitered/ignite#1578]
What's going on?

In `ignite-cli@4.0.0`, `ignite-cli new` command fails when trying to copy non-existing `.gitignore` file from boilerplate. Manually adding the `.gitignore` to the `boilerplate` folder in `node_modules` fixes it. I have tried it with `npx` , global and local install.

Steps to reproduce

1. Run `ignite-cli new PizzaApp`.
2. Receive error:
```
/usr/local/lib/node_modules/ignite-cli/node_modules/gluegun/build/index.js:13
    throw up;
    ^

Error: Path to copy doesn't exist /usr/local/lib/node_modules/ignite-cli/boilerplate/.gitignore
    at generateNoSourceError (/usr/local/lib/node_modules/ignite-cli/node_modules/fs-jetpack/lib/copy.js:52:15)
    at checksBeforeCopyingSync (/usr/local/lib/node_modules/ignite-cli/node_modules/fs-jetpack/lib/copy.js:83:11)
    at Object.copySync [as sync] (/usr/local/lib/node_modules/ignite-cli/node_modules/fs-jetpack/lib/copy.js:150:3)
    at Object.copy (/usr/local/lib/node_modules/ignite-cli/node_modules/fs-jetpack/lib/jetpack.js:76:12)
    at /usr/local/lib/node_modules/ignite-cli/build/commands/new.js:129:36
    at step (/usr/local/lib/node_modules/ignite-cli/build/commands/new.js:44:23)
    at Object.next (/usr/local/lib/node_modules/ignite-cli/build/commands/new.js:25:53)
    at fulfilled (/usr/local/lib/node_modules/ignite-cli/build/commands/new.js:16:58) {
  code: 'ENOENT'
}
```

---

`ignite doctor` results:
```
  platform           darwin
  arch               x64
  cpu                12 cores     Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz

JavaScript
  node               15.4.0       /usr/local/bin/node
  npm                7.0.15       /usr/local/bin/npm
  yarn               1.22.10      /usr/local/bin/yarn

Ignite
  ignite-cli         4.0.0        /usr/local/bin/ignite
  ignite src         build        /usr/local/lib/node_modules/ignite-cli/build

Android
  java               1.8.0_275    /usr/bin/java

iOS
  xcode              12.3
  cocoapods          1.10.0       /usr/local/bin/pod
```

**Comment by a-atalla** [comment]
same issue 
```
# npx ignite-cli doctor
System
  platform           darwin
  arch               x64
  cpu                4 cores      Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
  directory          PizzaApp     /Users/a.atalla/Projects/PizzaApp

JavaScript
  node               14.14.0      /Users/a.atalla/.nvm/versions/node/v14.14.0/bin/node
  npm                6.14.8       /Users/a.atalla/.nvm/versions/node/v14.14.0/bin/npm
  yarn               1.22.10      /Users/a.atalla/.nvm/versions/node/v14.14.0/bin/yarn

Ignite
  ignite-cli         4.0.0        /Users/a.atalla/.npm/_npx/42235/bin/ignite
  ignite src         build        /Users/a.atalla/.npm/_npx/42235/lib/node_modules/ignite-cli/build

Android
  java               1.8.0_265    /usr/local/opt/openjdk@8/bin/java
  android home       -            /Users/a.atalla/Library/Android/sdk

iOS
  xcode              12.3
  cocoapods          1.10.0       /usr/local/bin/pod
```

**Comment by SnVosooghi** [comment]
same here!


```
/Users/thisisnotmyname/.config/yarn/global/node_modules/gluegun/build/index.js:13
    throw up;
    ^
yarn run v1.22.10
,warning ../../../package.json: No license field
,error Command "format" not found.
,info
```

**Comment by jamonholmgren** [comment]
Thanks for the report, we’ll look into this ASAP!

**Comment by a-atalla** [comment]
I temporary solved this as follow
```
npm i -g ignite-cli

# change the following according to where your npm set the global packages
touch .nvm/versions/node/v14.14.0/lib/node_modules/ignite-cli/boilerplate/.gitignore

ignite-cli new PizzaApp
```

**Comment by fabidi** [comment]
Same issue. After creating the .gitignore file, I ran into this issue

```
C:\Users\phaza\AppData\Roaming\npm\node_modules\ignite-cli\node_modules\gluegun\build\index.js:13
    throw up;
    ^

Error: spawn yarn ENOENT
    at notFoundError (C:\Users\phaza\AppData\Roaming\npm\node_modules\ignite-cli\node_modules\cross-spawn\lib\enoent.js:6:26)
    at verifyENOENT (C:\Users\phaza\AppData\Roaming\npm\node_modules\ignite-cli\node_modules\cross-spawn\lib\enoent.js:40:16)
    at ChildProcess.cp.emit (C:\Users\phaza\AppData\Roaming\npm\node_modules\ignite-cli\node_modules\cross-spawn\lib\enoent.js:27:25)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12) {
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn yarn',
  path: 'yarn',
  spawnargs: [ 'format' ]
}
```

ignite doctor
```
System
  platform           win32
  arch               x64
  cpu                8 cores      Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
  directory          Work         D:\Projects\Work

JavaScript
  node               14.15.3      D:\Program Files\nodejs\node.EXE
  npm                6.14.10      D:\Program Files\nodejs\npm.CMD
  yarn               -            not installed

Ignite
  ignite-cli         4.0.0        C:\Users\phaza\AppData\Roaming\npm\ignite.CMD
  ignite src         build        C:\Users\phaza\AppData\Roaming\npm\node_modules\ignite-cli\build

Android
  java               -            null
  android home       -            undefined
```

**Comment by jamonholmgren** [comment]
New version coming out shortly that should fix this. When it does, you'll just need to run one of the following:

If using `npx`, just run `npx ignite-cli <command here>`. Check the version first; `npx ignite-cli --version` should say `4.0.1` or higher. If not, use `npx --ignore-existing ignite-cli --version` to force an update.

If using `yarn`, run `yarn global upgrade ignite-cli --latest`.

If using `npm`, run `npm upgrade -g ignite-cli --latest`

**Comment by jamonholmgren** [comment]
4.0.1 is released: https://github.com/infinitered/ignite/pull/1582#issuecomment-751842223

**Comment by DeVoresyah** [comment]
Still got this issue on Ignite v7.4.0

```
  node                14.15.5      /Users/devoresyah/.nvm/versions/node/v14.15.5/bin/node 
  npm                 6.14.11      /Users/devoresyah/.nvm/versions/node/v14.15.5/bin/npm  
    npm               6.14.11                                                             
  yarn                1.22.11      /usr/local/bin/yarn                                    
    code-push-cli     3.0.0                                                               
    create-nuxt-app   3.6.0                                                               
    expo-cli          4.3.0                                                               
    osmi-cli          1.3.1                                                               
    rnpm              1.9.0                                                               
    truffle           5.3.2                                                               

Ignite
  ignite-cli         7.4.0        /Users/devoresyah/.npm/_npx/42513/bin/ignite                        
  ignite src         build        /Users/devoresyah/.npm/_npx/42513/lib/node_modules/ignite-cli/build 

Android
  java               1.8.0_292    /usr/bin/java                         
  android home       -            /Users/devoresyah/Library/Android/Sdk 

iOS
  xcode              12.5.1     
  cocoapods          1.10.1       /Users/devoresyah/.rbenv/shims/pod
```

**Comment by frankfancode** [comment]
same error
```
 npx ignite-cli doctor
System
  platform           darwin
  arch               arm64
  cpu                8 cores      Apple M1
  directory          _npx         /Users/frank/.npm/_npx

JavaScript (and globally-installed packages)
  node               14.17.3      /Users/frank/.nvm/versions/node/v14.17.3/bin/node
  npm                6.14.13      /Users/frank/.nvm/versions/node/v14.17.3/bin/npm
    npm              6.14.13
  yarn               1.22.10      /usr/local/bin/yarn
    ignite-cli       7.4.0
    ios-deploy       1.11.4

Ignite
  ignite-cli         7.4.0        /Users/frank/.npm/_npx/62209/bin/ignite
  ignite src         build        /Users/frank/.npm/_npx/62209/lib/node_modules/ignite-cli/build

Android
  java               1.8.0_291    /usr/bin/java
  android home       -            /Users/frank/Library/Android/sdk

iOS
  xcode              12.5.1
  cocoapods          1.10.1       /usr/local/bin/pod
```

**Comment by akhatriST** [comment]
I am getting the same error, below is the `npx ignite-cli doctor` command response

```
System
  platform           darwin                                                
  arch               x64                                                   
  cpu                4 cores      Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz 
  directory          asimkhatri   /Users/asimkhatri                        

JavaScript (and globally-installed packages)
  node               14.17.5      /usr/local/bin/node 
  npm                6.14.14      /usr/local/bin/npm  
    npm              6.14.14                          
    yarn             1.22.11                          
  yarn               1.22.11      /usr/local/bin/yarn 

Ignite
  ignite-cli         7.4.0        /Users/asimkhatri/.npm/_npx/26119/bin/ignite                        
  ignite src         build        /Users/asimkhatri/.npm/_npx/26119/lib/node_modules/ignite-cli/build 

Android
  java               11.0.10      /usr/bin/java                         
  android home       -            /Users/asimkhatri/Library/Android/sdk 

iOS
  xcode              12.5       
  cocoapods          1.10.1       /usr/local/bin/pod 
```

**Comment by chreck** [comment]
Same issue here, creating the `.gitignore` file fixed the issue.

**Examples**
`touch /Users/<user>/.config/yarn/global/node_modules/ignite-cli/boilerplate/.gitignore`
`touch /Users/<user>/.nvm/versions/node/<node-version>/lib/node_modules/ignite-cli/boilerplate/.gitignore`

**Comment by akhatriST** [comment]
To fix this error, simply copy the .gitignore [from here](https://github.com/infinitered/ignite/blob/master/boilerplate/.gitignore) and paste it on the reported missing path.
