### ISSUE TITLE
Error running `ignite doctor` on Windows

### ISSUE THREAD

**Issue by patevs** [infinitered/ignite#1579]
Running `ignite doctor` produces the following error:

```bash
JavaScript
  node               14.15.3      C:\Users\User\scoop\apps\nodejs-lts\current\node.EXE
  npm                6.14.10      C:\Users\User\scoop\apps\nodejs-lts\current\bin\npm.CMD
  yarn               1.22.5       C:\Users\User\scoop\apps\yarn\current\Yarn\bin\yarn.CMD

Ignite
  ignite-cli         4.0.0        C:\Users\User\scoop\apps\nodejs-lts\current\bin\ignite.CMD
  ignite src         build        C:\Users\User\scoop\persist\nodejs-lts\bin\node_modules\ignite-cli\build
C:\Users\User\scoop\persist\nodejs-lts\bin\node_modules\ignite-cli\node_modules\gluegun\build\index.js:13
    throw up;
    ^

TypeError: Cannot read property 'slice' of null
    at Command.<anonymous> (C:\Users\User\scoop\persist\nodejs-lts\bin\node_modules\ignite-cli\build\commands\doctor.js:152:57)
    at step (C:\Users\User\scoop\persist\nodejs-lts\bin\node_modules\ignite-cli\build\commands\doctor.js:33:23)
    at Object.next (C:\Users\User\scoop\persist\nodejs-lts\bin\node_modules\ignite-cli\build\commands\doctor.js:14:53)
    at fulfilled (C:\Users\User\scoop\persist\nodejs-lts\bin\node_modules\ignite-cli\build\commands\doctor.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

---

Steps to reproduce

1. Run: `ignite doctor`

---

**Comment by jamonholmgren** [comment]
Looking into this!

**Comment by jamonholmgren** [comment]
I'm getting a _different_ error. Still researching.

**Comment by jamonholmgren** [comment]
Fix is up in #1592!

**Comment by jamonholmgren** [comment]
@patevs Can you test with 6.1.1?

**Comment by patevs** [comment]
@jamonholmgren Can confirm `ignite doctor` command is now working as expected in version `6.1.1`. Many thanks!
