### ISSUE TITLE
Error in npm install (may due to expo-detox-hook)

### ISSUE THREAD

**Issue by suerta-git** [infinitered/ignite#1642]
## What's going on?

got error like this:
```
error /Users/jindong.zhang/Desktop/React Native/DressUp/node_modules/expo-detox-hook: Command failed.
Exit code: 1
Command: node scripts/postinstall.js
Arguments: 
Directory: /Users/jindong.zhang/Desktop/React Native/DressUp/node_modules/expo-detox-hook
Output:
+ xcodebuild -version
+++ dirname '/Users/jindong.zhang/Desktop/React Native/DressUp/node_modules/expo-detox-hook/scripts/build_framework.ios.sh'
++ dirname '/Users/jindong.zhang/Desktop/React Native/DressUp/node_modules/expo-detox-hook/scripts'
+ rootPath='/Users/jindong.zhang/Desktop/React Native/DressUp/node_modules/expo-detox-hook'
++ node -p 'require('\''/Users/jindong.zhang/Desktop/React Native/DressUp/node_modules/expo-detox-hook/package.json'\'').version'
+ version=1.0.10
++ echo 1.0.10
++ xcodebuild -version
++ shasum
++ awk '{print $1}'
+ sha1=5a799e947a5c6a97fffdc373ace463985005b26a
+ frameworkDirPath=/Users/jindong.zhang/Library/ExpoDetoxHook/ios/5a799e947a5c6a97fffdc373ace463985005b26a
+ frameworkPath=/Users/jindong.zhang/Library/ExpoDetoxHook/ios/5a799e947a5c6a97fffdc373ace463985005b26a/ExpoDetoxHook.framework
+ main
+ '[' -d /Users/jindong.zhang/Library/ExpoDetoxHook/ios/5a799e947a5c6a97fffdc373ace463985005b26a ']'
+ '[' '!' -d /Users/jindong.zhang/Library/ExpoDetoxHook/ios/5a799e947a5c6a97fffdc373ace463985005b26a/ExpoDetoxHook.framework ']'
+ echo '/Users/jindong.zhang/Library/ExpoDetoxHook/ios/5a799e947a5c6a97fffdc373ace463985005b26a was found, but could not find ExpoDetoxHook.framework inside it. This means that the ExpoDetoxHook framework build process was interrupted.
         deleting /Users/jindong.zhang/Library/ExpoDetoxHook/ios/5a799e947a5c6a97fffdc373ace463985005b26a and trying to rebuild.'
+ rm -rf /Users/jindong.zhang/Library/ExpoDetoxHook/ios/5a799e947a5c6a97fffdc373ace463985005b26a
/Users/jindong.zhang/Library/ExpoDetoxHook/ios/5a799e947a5c6a97fffdc373ace463985005b26a was found, but could not find ExpoDetoxHook.framework inside it. This means that the ExpoDetoxHook framework build process was interrupted.
         deleting /Users/jindong.zhang/Library/ExpoDetoxHook/ios/5a799e947a5c6a97fffdc373ace463985005b26a and trying to rebuild.
+ prepareAndBuildFramework
+ '[' -d '/Users/jindong.zhang/Desktop/React Native/DressUp/node_modules/expo-detox-hook/ios' ']'
+ sourcePath='/Users/jindong.zhang/Desktop/React Native/DressUp/node_modules/expo-detox-hook/ios_src'
+ extractSources '/Users/jindong.zhang/Desktop/React Native/DressUp/node_modules/expo-detox-hook/ios_src'
+ sourcePath='/Users/jindong.zhang/Desktop/React Native/DressUp/node_modules/expo-detox-hook/ios_src'
+ echo 'Extracting ExpoDetoxHook sources...'
+ mkdir -p '/Users/jindong.zhang/Desktop/React Native/DressUp/node_modules/expo-detox-hook/ios_src'
Extracting ExpoDetoxHook sources...
+ tar -xjf '/Users/jindong.zhang/Desktop/React Native/DressUp/node_modules/expo-detox-hook/ExpoDetoxHook-ios-src.tbz' -C '/Users/jindong.zhang/Desktop/React Native/DressUp/node_modules/expo-detox-hook/ios_src'
+ buildFramework '/Users/jindong.zhang/Desktop/React Native/DressUp/node_modules/expo-detox-hook/ios_src'
+ sourcePath='/Users/jindong.zhang/Desktop/React Native/DressUp/node_modules/expo-detox-hook/ios_src'
+ echo 'Building ExpoDetoxHook.framework from /Users/jindong.zhang/Desktop/React Native/DressUp/node_modules/expo-detox-hook/ios_src...'
+ mkdir -p /Users/jindong.zhang/Library/ExpoDetoxHook/ios/5a799e947a5c6a97fffdc373ace463985005b26a
Building ExpoDetoxHook.framework from /Users/jindong.zhang/Desktop/React Native/DressUp/node_modules/expo-detox-hook/ios_src...
+ '/Users/jindong.zhang/Desktop/React Native/DressUp/node_modules/expo-detox-hook/scripts/build_universal_framework.sh' '/Users/jindong.zhang/Desktop/React Native/DressUp/node_modules/expo-detox-hook/ios_src/ExpoDetoxHook.xcodeproj' /Users/jindong.zhang/Library/ExpoDetoxHook/ios/5a799e947a5c6a97fffdc373ace463985005b26a
child_process.js:637
    throw err;
    ^

Error: Command failed: /Users/jindong.zhang/Desktop/React Native/DressUp/node_modules/expo-detox-hook/scripts/build_framework.ios.sh
    at checkExecSyncError (child_process.js:616:11)
    at Object.execFileSync (child_process.js:634:15)
    at Object.<anonymous> (/Users/jindong.zhang/Desktop/React Native/DressUp/node_modules/expo-detox-hook/scripts/postinstall.js:2:27)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  status: 69,
  signal: null,
  output: [ null, null, null ],
  pid: 96585,
```
---

## Steps to reproduce

1. run command `npx ignite-cli new XXX --expo`
2. error occurs when installing dependencies

---

## `ignite doctor` results:

```
System
  platform           darwin
  arch               x64
  cpu                12 cores       Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  directory          React Native   /Users/jindong.zhang/Desktop/React Native

JavaScript (and globally-installed packages)
  node               14.15.0      /Users/jindong.zhang/.nvm/versions/node/v14.15.0/bin/node
  npm                6.14.8       /Users/jindong.zhang/.nvm/versions/node/v14.15.0/bin/npm
    npm              6.14.8
    yarn             1.22.10
  yarn               1.22.10      /Users/jindong.zhang/.nvm/versions/node/v14.15.0/bin/yarn

Ignite
  ignite-cli         6.6.0        /Users/jindong.zhang/.npm/_npx/99760/bin/ignite
  ignite src         build        /Users/jindong.zhang/.npm/_npx/99760/lib/node_modules/ignite-cli/build

Android
  java               1.8.0_281    /usr/bin/java
  android home       -            /Users/jindong.zhang/Library/Android/sdk

iOS
  xcode              12.4
  cocoapods          Not installed
```

---

maybe useful:

[issue in detox repo](https://github.com/wix/Detox/issues/1092)

moreover i see `expo-detox-hook`'s last update was in 2 years ago, maybe should consider whether it's out of date and no longer maintained？

**Comment by nirre7** [comment]
Try to install [cocoapods](https://guides.cocoapods.org/using/getting-started.html#installation)

**Comment by suerta-git** [comment]
> Try to install [cocoapods](https://guides.cocoapods.org/using/getting-started.html#installation)

Thank you, I will try it.

**Comment by suerta-git** [comment]
> Try to install [cocoapods](https://guides.cocoapods.org/using/getting-started.html#installation)

awesome, it works. thanks very much :)
