### ISSUE TITLE
CLI fails to initialize a new project

### ISSUE THREAD

**Issue by ibrahimelaradi** [infinitered/ignite#1645]
What's going on?

The CLI fails to initialize a new project, it stops while installing pods and throws the following error
```
[!] Invalid `Podfile` file: cannot load such file -- /Users/darkystel/Desktop/projects/PokemonApp/node_modules/react-native/scripts/react_native_pods
```
```
CocoaPodsError: The command `pod install` failed
└─ Cause: Error: pod exited with non-zero code: 1
    at CocoaPodsPackageManager._installAsync (/Users/darkystel/.npm/_npx/7cf525d1e16b4e35/node_modules/pod-install/build/index.js:2:85286)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async CocoaPodsPackageManager.installAsync (/Users/darkystel/.npm/_npx/7cf525d1e16b4e35/node_modules/pod-install/build/index.js:2:84649)
    at async runAsync (/Users/darkystel/.npm/_npx/7cf525d1e16b4e35/node_modules/pod-install/build/index.js:2:109680)
    at async /Users/darkystel/.npm/_npx/7cf525d1e16b4e35/node_modules/pod-install/build/index.js:2:109766 {
  code: 'COMMAND_FAILED',
  cause: Error: pod exited with non-zero code: 1
      at ChildProcess.h (/Users/darkystel/.npm/_npx/7cf525d1e16b4e35/node_modules/pod-install/build/index.js:2:1073)
      at Object.onceWrapper (node:events:476:26)
      at ChildProcess.emit (node:events:369:20)
      at maybeClose (node:internal/child_process:1067:16)
      at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
      ...
      at Object.spawnAsync [as default] (/Users/darkystel/.npm/_npx/7cf525d1e16b4e35/node_modules/pod-install/build/index.js:2:558)
      at CocoaPodsPackageManager._runAsync (/Users/darkystel/.npm/_npx/7cf525d1e16b4e35/node_modules/pod-install/build/index.js:2:86068)
      at CocoaPodsPackageManager._installAsync (/Users/darkystel/.npm/_npx/7cf525d1e16b4e35/node_modules/pod-install/build/index.js:2:84933)
      at CocoaPodsPackageManager.installAsync (/Users/darkystel/.npm/_npx/7cf525d1e16b4e35/node_modules/pod-install/build/index.js:2:84660)
      at runAsync (/Users/darkystel/.npm/_npx/7cf525d1e16b4e35/node_modules/pod-install/build/index.js:2:109688)
      at processTicksAndRejections (node:internal/process/task_queues:94:5)
      at async /Users/darkystel/.npm/_npx/7cf525d1e16b4e35/node_modules/pod-install/build/index.js:2:109766 {
    pid: 12514,
    output: [ '', '' ],
    stdout: '',
    stderr: '',
    status: 1,
    signal: null
  },
  isPackageManagerError: true
}
```

Steps to reproduce

1. Running `npx ignite-cli new AppName`

---

`ignite doctor` results:
```
System
  platform           darwin
  arch               x64
  cpu                8 cores      Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
  directory          projects     /Users/darkystel/Desktop/projects

JavaScript (and globally-installed packages)
  node               15.12.0      /Users/darkystel/.nvm/versions/node/v15.12.0/bin/node
  npm                7.6.3        /Users/darkystel/.nvm/versions/node/v15.12.0/bin/npm
    npm              7.6.3
  yarn               -            not installed

Ignite
  ignite-cli         6.6.0        /Users/darkystel/.npm/_npx/e31027f3785124a8/node_modules/.bin/ignite
  ignite src         build        /Users/darkystel/.npm/_npx/e31027f3785124a8/node_modules/ignite-cli/build

Android
  java               1.8.0_282    /usr/bin/java
  android home       -            /Users/darkystel/Library/Android/sdk

iOS
  xcode              12.4
  cocoapods          1.10.1       /usr/local/bin/pod
```

**Comment by nirre7** [comment]
Hi.
Try react native doctor:
`npx @react-native-community/cli doctor`

**Comment by dennis3124** [comment]
This worked for me
https://github.com/infinitered/ignite/issues/1639#issuecomment-810618577

**Comment by ibrahimelaradi** [comment]
> Hi.
> Try react native doctor:
> `npx @react-native-community/cli doctor`

I did, found some missing dependencies and fixed almost all errors, I still get this one error with Android SDK tho
```
 ✖ Android SDK - Required for building and installing your app on Android
   - Versions found: 29.0.2
   - Version supported: Not Found
```
This is the version I found on the guide that is supported by react native
Nonetheless, I ran the initialization again and it gave the same error

**Comment by ibrahimelaradi** [comment]
Apparently, forcing pods to use the latest version of Flipper (0.84) solved the issue for me, as for Android all I had to do was run it from Android Studio
