### ISSUE TITLE
"yarn build-android" errors on missing index.js

### ISSUE THREAD

**Issue by JeroenGoddijn** [infinitered/ignite#1654]
What's going on?
Trying to run `yarn build-android` to rebulid android bundle, but it errors/crashes due to missing index.js file in root folder. Shouldn't the index.js file be included when running the initial `npx ignite-cli new PizzaApp --expo` command?

*NOTE: I've replaced long absolute paths with relative paths for easier reading

Here's what terminal shows:

```
yarn run v1.22.5
$ react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res
                 Welcome to React Native!
                Learn once, write anywhere


error The resource `./PizzaApp/index.js` was not found. Run CLI with --verbose flag for more details.
Error: The resource `./PizzaApp/index.js` was not found.
    at ./PizzaApp/node_modules/metro/src/IncrementalBundler.js:157:26
    at gotStat (fs.js:1864:21)
    at FSReqCallback.oncomplete (fs.js:183:21)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

---

Steps to reproduce

1. run `npx ignite-cli new PizzaApp --expo` and wait for it to finish
2. run `yarn build-android` from terminal (as specified in package.json)

---

`ignite doctor` results:

````
System
  platform           linux                                                                                          
  arch               x64                                                                                            
  cpu                8 cores      Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz                                          
  directory          PizzaApp     ./PizzaApp 

JavaScript (and globally-installed packages)
  node                 14.15.4      /usr/local/bin/node 
  npm                  7.9.0        /usr/local/bin/npm  
    degit              2.8.4                            
    expo-cli           4.4.1                            
    n                  7.0.1                            
    nodemon            2.0.2                            
    npm                7.9.0                            
    npx                10.2.0                           
    vercel             21.1.0                           
  yarn                 1.22.5       /usr/bin/yarn       
    babel-cli          6.24.1                           
    firebase-tools     9.1.0                            
    git-labelmaker     0.9.0                            
    react-devtools     4.7.0                            
    react-native-cli   2.0.1                            
    serve              11.3.0                           
    vercel             21.1.0                           

Ignite
  ignite-cli         6.7.0        ./PizzaApp/node_modules/.bin/ignite      
  ignite src         build        ./PizzaApp/node_modules/ignite-cli/build 

Android
  java               1.8.0_282    /usr/bin/java                   
  android home       -            /home/jeroengoddijn/Android/Sdk 
````

**Comment by JeroenGoddijn** [comment]
Never mind..it seems to be resolved in latest release 6.7.0. I can run `yarn build-android` there without issue.
