### ISSUE TITLE
Cannot start on windows or macOS, missing /Libraries folder

### ISSUE THREAD

**Issue by 1mike12** [infinitered/ignite#1726]
Windows 10 
node version 16.1.0
npm v 6.14.13

I can init a new project fine via `npx ignite-cli new reactNative `. 

Yet when I start the project via `npx react-native run-android  ` the metro window spits out this error:

(I can confirm that the `Libraries\...` folder doesn't exist)

```
 BUNDLE  ./index.js

error: Error: While resolving module `react-native/Libraries/Image/AssetRegistry`, the Haste package `react-native` was found. However the module `Libraries/Image/AssetRegistry` could not be found within the package. Indeed, none of these files exist:

  * `C:\Users\1mike\go\scuba\reactNative\Libraries\Image\AssetRegistry(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)`
  * `C:\Users\1mike\go\scuba\reactNative\Libraries\Image\AssetRegistry\index(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)`
    at resolveHasteName (C:\Users\1mike\go\scuba\reactNative\node_modules\metro-resolver\src\resolve.js:255:9)
    at Object.resolve (C:\Users\1mike\go\scuba\reactNative\node_modules\metro-resolver\src\resolve.js:116:20)
    at ModuleResolver.resolveDependency (C:\Users\1mike\go\scuba\reactNative\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:187:31)
    at DependencyGraph.resolveDependency (C:\Users\1mike\go\scuba\reactNative\node_modules\metro\src\node-haste\DependencyGraph.js:413:43)
    at Object.resolve (C:\Users\1mike\go\scuba\reactNative\node_modules\metro\src\lib\transformHelpers.js:317:42)
    at resolve (C:\Users\1mike\go\scuba\reactNative\node_modules\metro\src\DeltaBundler\traverseDependencies.js:629:33)
    at C:\Users\1mike\go\scuba\reactNative\node_modules\metro\src\DeltaBundler\traverseDependencies.js:645:26
    at Array.reduce (<anonymous>)
    at resolveDependencies (C:\Users\1mike\go\scuba\reactNative\node_modules\metro\src\DeltaBundler\traverseDependencies.js:644:33)
    at C:\Users\1mike\go\scuba\reactNative\node_modules\metro\src\DeltaBundler\traverseDependencies.js:329:33
 BUNDLE  ./index.js
```
---

Steps to reproduce

1.  `npx ignite-cli new reactNative`
2.  `npx react-native run-android`

---

`ignite doctor` results:

```
npx ignite doctor
Downloading Chromium r588429 - 130.6 Mb [====================] 100% 0.0s
  √ cwebp pre-build test passed successfully
  √ gifsicle pre-build test passed successfully
  √ mozjpeg pre-build test passed successfully
  √ optipng pre-build test passed successfully
  √ pngquant pre-build test passed successfully
cannot find any package.json file
```

**Comment by 1mike12** [comment]
I verified the same thing happens on macos as well

**Comment by jamonholmgren** [comment]
Hi @1mike12 , thanks for the report!

I spun up a new app using the same command:

```
npx ignite-cli new reactNative
```

When running `npx react-native run-android`, I got an error.

However, when I spun up a new app using a different name:

```
npx ignite-cli new JustTryingThis
```

It worked fine. So maybe it's some issue with the name `reactNative`? Can you verify?

I'd entertain a PR disallowing that name. Here's the relevant file:

https://github.com/infinitered/ignite/blob/9a67d7c3d6b57a3b058431583117cff9bdc680da/src/tools/validations.ts

![image](https://user-images.githubusercontent.com/1479215/125518516-caadedd5-6f2e-4266-a9d0-a39152dcc5bb.png)

**Comment by 1mike12** [comment]
That's exactly what it was. I read elsewhere that the name can't have dashed either. So maybe blacklist both `react-native` and `reactNative`
