### ISSUE TITLE
npx ignite-cli new app [ERR_CHILD_PROCESS_STDIO_MAXBUFFER] 

### ISSUE THREAD

**Issue by Landson** [infinitered/ignite#1801]
What's going on?

I'm getting an error when creating a new app. The install is hanging and heavily using my cpu indefinitely. If I add
--debug to the creation command, the hanging stops but I get an error message that I'm not sure if I should ignore.

```
.
.
.
Pod installation complete! There are 74 dependencies from the Podfile and 65 total pods installed.

    ☕️ Baking CocoaPods
    ⠋  Backing everything up in source control 
          \rm -rf ./.git
          git init;
          git add -A;
          git commit -m "New Ignite 7.4.0 app";
        
    ⠼  Backing everything up in source control/Users/myusername/.npm-global/lib/node_modules/ignite-cli/node_modules/gluegun/build/index.js:13
    throw up;
    ^

RangeError [ERR_CHILD_PROCESS_STDIO_MAXBUFFER]: stdout maxBuffer length exceeded
    at new NodeError (internal/errors.js:322:7)
    at Socket.onChildStdout (child_process.js:443:14)
    at Socket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:293:12)
    at readableAddChunk (internal/streams/readable.js:263:11)
    at Socket.Readable.push (internal/streams/readable.js:206:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23) {
  code: 'ERR_CHILD_PROCESS_STDIO_MAXBUFFER',
  cmd: '\n' +
    '          \\rm -rf ./.git\n' +
    '          git init;\n' +
    '          git add -A;\n' +
    '          git commit -m "New Ignite 7.4.0 app";\n' +
    '        ',
  stdout: 'Initialized empty Git repository in /Users/myusername/Desktop/ReactNativeApp/.git/\n' +
    '[master (root-commit) c2e4339] New Ignite 7.4.0 app\n' +
    ' 86242 files changed, 10489714 insertions(+)\n' +
    ' create mode 100644 .gitignore\n' +
    ' create mode 100644 .prettierignore\n' +
    ' create mode 100644 .solidarity\n' +
    ' create mode 100644 README.md\n' +
    ' create mode 100644 android/app/BUCK\n' +
    ' create mode 100644 android/app/build.gradle\n' +
    ' create mode 100644 android/app/build_defs.bzl\n' +
    ' create mode 100644 android/app/debug.keystore\n' +
    ' create mode 100644 android/app/proguard-rules.pro\n' +
    ' create mode 100644 android/app/src/debug/AndroidManifest.xml\n' +
.
. 
.
```

The above continues to list a very very large number of files and then finishes with

```
.
.
.
  stderr: 'warning: CRLF will be replaced by LF in node_modules/jest-specific-snapshot/node_modules/@types/prettier/README.md.\n' +
    'The file will have its original line endings in your working directory\n' +
    'warning: CRLF will be replaced by LF in node_modules/jest-specific-snapshot/node_modules/@types/stack-utils/README.md.\n' +
    'The file will have its original line endings in your working directory\n' +
    'Auto packing the repository in background for optimum performance.\n' +
    'See "git help gc" for manual housekeeping.\n'
```

Steps to reproduce

1. Run the terminal command: npx ignite-cli new ReactNativeApp --debug

`npx ignite-cli doctor` results:

```
myusername@Chriss-MacBook-Pro ReactNativeApp % npx ignite-cli doctor
System
  platform           darwin                                                         
  arch               x64                                                            
  cpu                8 cores          Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz     
  directory          ReactNativeApp   /Users/myusername/Desktop/ReactNativeApp 

JavaScript (and globally-installed packages)
  node               14.18.0      /Users/myusername/.nvm/versions/node/v14.18.0/bin/node 
  npm                6.14.15      /Users/myusername/.nvm/versions/node/v14.18.0/bin/npm  
    npm              6.14.15                                                                  
  yarn               1.22.11      /Users/myusername/.npm-global/bin/yarn                 

Ignite
  ignite-cli         7.4.0        /Users/myusername.npm-global/bin/ignite                        
  ignite src         build        /Users/myusername/.npm-global/lib/node_modules/ignite-cli/build 

Android
  java               11.0.11      /usr/bin/java                              
  android home       -            /Users/myusername/Library/Android/sdk 

iOS
  xcode              12.4       
  cocoapods          1.10.2       /Users/myusername/.rvm/rubies/ruby-2.4.0/bin/pod 
```

**Comment by Landson** [comment]
I looked into this thinking it was a node default buffer size issue. Turns out that my npm global installation location was causing issues. Note my original **npx ignite-cli doctor**'s ignite-cli directory above is just a typo in my post, the actual location had a forward slash between username and .npm-global.

I've since fixed my npm global path following this post: _https://stackoverflow.com/a/14840304_
I then removed my global ignite-cli install and ran it using npx which downloaded/used 7.5.0 and that worked.

Thanks to anyone who had a look. Cheers!
