### ISSUE TITLE
Build iOS or Android

### ISSUE THREAD

**Issue by Aspedm** [infinitered/ignite#1814]
**What's going on?**

Trying to run `yarn build-ios.` First my error was 'index.js was not found'
I could not find index.js in project, but found App.js, i changed command line params and run yarn build-ios again. But got an error.

First error:
```
$ react-native bundle --entry-file index.js --platform ios --dev false --bundle-output ios/main.jsbundle --assets-dest ios
                 Welcome to React Native!
                Learn once, write anywhere


error The resource `/Users/tagirhadzhiev/Documents/react-native/PizzaApp/index.js` was not found. Run CLI with --verbose flag for more details.
Error: The resource `/Users/tagirhadzhiev/Documents/react-native/PizzaApp/index.js` was not found.
    at /Users/tagirhadzhiev/Documents/react-native/PizzaApp/node_modules/metro/src/IncrementalBundler.js:157:26
    at gotStat (fs.js:1665:21)
    at FSReqCallback.oncomplete (fs.js:158:21)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Second error:
```
yarn build-ios          
yarn run v1.19.1
$ react-native bundle --entry-file App.js --platform ios --dev false --bundle-output ios/main.jsbundle --assets-dest ios
                 Welcome to React Native!
                Learn once, write anywhere


info Writing bundle output to:, ios/main.jsbundle
error ENOENT: no such file or directory, open 'ios/main.jsbundle'. Run CLI with --verbose flag for more details.
Error: ENOENT: no such file or directory, open 'ios/main.jsbundle'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Steps to reproduce**

1. npx ignite-cli new PizzaApp
2. yarn build-ios

App.js from 7.5.0 version

<img width="733" alt="Screenshot 2021-10-18 at 23 41 09" src="https://user-images.githubusercontent.com/8427994/137803701-33e27537-27e5-422b-b778-a99fa3dc8ff6.png">

**ignite-cli doctor results:**

```
System
  platform           darwin                                                            
  arch               x64                                                               
  cpu                8 cores      Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz            
  directory          PizzaApp     /Users/tagirhadzhiev/Documents/react-native/PizzaApp 

JavaScript (and globally-installed packages)
  node                 12.14.1      /usr/local/bin/node 
  npm                  6.13.4       /usr/local/bin/npm  
    expo-cli           4.12.0                           
    npm                6.13.4                           
    react-native-cli   2.0.1                            
  yarn                 1.19.1       /usr/local/bin/yarn 
    gatsby-cli         2.10.4                           

Ignite
  ignite-cli         7.5.0        /Users/tagirhadzhiev/.npm/_npx/77336/bin/ignite                        
  ignite src         build        /Users/tagirhadzhiev/.npm/_npx/77336/lib/node_modules/ignite-cli/build 
/Users/tagirhadzhiev/.npm/_npx/77336/lib/node_modules/ignite-cli/node_modules/gluegun/build/index.js:13
    throw up;
    ^

Error: Command failed: java -version 2>&1

    at ChildProcess.exithandler (child_process.js:295:12)
    at ChildProcess.emit (events.js:223:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5) {
  killed: false,
  code: 1,
  signal: null,
  cmd: 'java -version 2>&1',
  stdout: 'The operation couldn’t be completed. Unable to locate a Java Runtime.\n' +
    'Please visit http://www.java.com for information on installing Java.\n' +
    '\n',
  stderr: ''
}

```

**Comment by derekgreenberg** [comment]
@Aspedm before we delve deeper into this issue, which appears to be an issue with Ignite being unable to complete the creation of a new app due to the inability to find a Java runtime, I recommend going through the [Installing React Native on Mac OS](https://academy.infinite.red/p/installing-react-native-tutorial-on-macos) course that covers the steps for setting up the Java environment.

This tutorial is 100% free of charge! Infinite Red offers it as a way to help the React Native community get set up with a working development environment and prepared to use Ignite.

Please go through the tutorial, which will help you set up the required Java runtime, and post the results of that process as well as whether you were able to create a new React Native app using Ignite.

> `npx ignite-cli new PizzaApp --expo` does not create android and iOS folder. Is this the expected?
