### ISSUE TITLE
Issue in generating app with custom bundle

### ISSUE THREAD

**Issue by lvlrSajjad** [infinitered/ignite#1856]
What's going on?

When I use the command below to generate app with custom bundle it throws an error in installing Colo loco and eventually fails.

---

Steps to reproduce

1.  Run this command:
```
npx ignite-cli new CustomBundleApp --bundle=com.custom.bundle
```

And after a while it shows following results:
```
   npx ignite-cli new CustomBundleApp --bundle=com.custom.bundle
   

   · · · · · · · · · · · · · · · · · · 🔥 Ignite 🔥 · · · · · · · · · · · · · · · · · ·

    █ Creating CustomBundleApp using Ignite 7.8.3
    █ Powered by Infinite Red - https://infinite.red
    █ Using ignite-cli
    █ Bundle identifier: com.custom.bundle
    ────────────────────────────────────────────────

    🔥 Igniting app
    🖨  3D-printing a new React Native app
    🧶 Unboxing npm dependencies
    🏝  Writing your app name in the sand
    ⠴ Installing React Native Colo Loco
/Users/Username/.npm/_npx/e31027f3785124a8/node_modules/gluegun/build/index.js:13
    throw up;
    ^
Setting up React Native Colo Loco!
Setting up React Native Colo Loco for CustomBundleApp in app
internal/fs/utils.js:312
    throw err;
    ^

Error: ENOENT: no such file or directory, open './android/app/src/main/java/com/custombundleapp/CustomBundleAppPackage.java'
    at Object.openSync (fs.js:498:3)
    at Object.writeFileSync (fs.js:1524:35)
    at setupAndroid (/My/Folder/Path/CustomBundleApp/node_modules/react-native-colo-loco/scripts/install-colo-loco:203:8)
    at setupColoLoco (/My/Folder/Path/CustomBundleApp/node_modules/react-native-colo-loco/scripts/install-colo-loco:95:3)
    at startSetup (/My/Folder/Path/CustomBundleApp/node_modules/react-native-colo-loco/scripts/install-colo-loco:86:5)
    at Object.<anonymous> (/My/Folder/Path/CustomBundleApp/node_modules/react-native-colo-loco/scripts/install-colo-loco:46:3)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: './android/app/src/main/java/com/custombundleapp/CustomBundleAppPackage.java'
}

(Use `node --trace-uncaught ...` to show where the exception was thrown)
```

---

`npx ignite-cli doctor` results:

```
lxvr.xaus@Sajjads-MacBook-Pro Path % npx ignite-cli doctor
System
  platform           darwin                                                             
  arch               x64                                                                
  cpu                8 cores      Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz             
  directory          Path      /My/Folder/Path 

JavaScript (and globally-installed packages)
  node                         14.17.0      /usr/local/bin/node 
  npm                          8.0.0        /usr/local/bin/npm  
    @sentry/wizard             1.0.1                            
    @vue/cli                   3.11.0                           
    depcheck                   1.4.2                            
    expo-cli                   4.4.6                            
    firebase-tools             9.10.0                           
    firestore-backup-restore   1.3.1                            
    gulp-cli                   2.3.0                            
    http-server                13.0.2                           
    live-server                1.2.1                            
    n                          7.2.2                            
    npm-check-updates          11.5.7                           
    npm                        8.0.0                            
    react-native-cli           2.0.1                            
  yarn                         1.22.10      /usr/local/bin/yarn 

Ignite
  ignite-cli         7.8.3        /Users/Username/.npm/_npx/e31027f3785124a8/node_modules/.bin/ignite      
  ignite src         build        /Users/Username/.npm/_npx/e31027f3785124a8/node_modules/ignite-cli/build 

Android
  java               11.0.13      /usr/bin/java 
  android home       -            undefined     

iOS
  xcode              13.1       
  cocoapods          1.11.2       /Users/Username/.rvm/rubies/ruby-2.6.6/bin/pod 

```

**Comment by dragonmaster784** [comment]
I am also facing the same error ⚠️

I am just did a fresh OS boot with a clean install of everything on my M1 MacBook.
Node v16.13.1 (lts)
iTerm2 (Running off Rosetta) **- I have tried running on a normal terminal too (_sans Rosetta_)**

You'll notice the same report as OP here 👇
[ignite_cli-crash-report.log](https://github.com/infinitered/ignite/files/7807452/ignite_cli-crash-report.log)

If I try to individually install the package after the premature igniting of an app, I get the out put I logged below 👇
[individual-installation-colo_loco.log](https://github.com/infinitered/ignite/files/7807423/individual-installation-colo_loco.log)

**Comment by dragonmaster784** [comment]
So I thought about not installing the **React Native Colo Loco** module, I found an option flag called _--no-colo-loco_ (in the commands/new.ts of the repo) that you can append to _ignite-cli new exampleName_ script. 
It got rid of the previous error with Colo Loco, but the Gluegun error still persists 👇
[gluegun_warning.log](https://github.com/infinitered/ignite/files/7807586/gluegun_warning.log)

**Comment by frankcalise** [comment]
Hello @lvlrSajjad and @dragonmaster784, thanks for the report! Have you tried this with the latest version if Ignite CLI? 7.14.2. I'm unable to produce the issue shown here.

**Comment by frankcalise** [comment]
I'm going to close this issue due to inactivity. However, if this problem still persists and you have updated to the latest version of ignite, please open a new issue stating the problem and the output of `npx ignite-cli doctor`.

Also, you can check out https://community.infinite.red to get help with us (and a bunch of other RN devs!) directly in Slack.
