### ISSUE TITLE
TypeError: Invalid Version

### ISSUE THREAD

**Issue by jschoolcraft** [infinitered/ignite#186]
I have a problem running `ignite new IgniteApp`:

```
☻  ignite --version

~/code/sandbox
☻  ignite --version
1.0.2

~/code/sandbox
☻  ignite new IgniteApp
🔥 Setting IgniteApp on FIRE! 🔥
-----------------------------------------------
  (                  )   (
  )\ )   (        ( /(   )\ )    *   )
 (()/(   )\ )     )\()) (()/(  ` )  /(   (
  /(_)) (()/(    ((_)\   /(_))  ( )(_))  )\
 (_))    /(_))_   _((_) (_))   (_(_())  ((_)
 |_ _|  (_)) __| | \| | |_ _|  |_   _|  | __|
  | |     | (_ | | .` |  | |     | |    | _|
 |___|     \___| |_|\_| |___|    |_|    |___|
-----------------------------------------------

An unfair headstart for your React Native apps.
https://ignite.infinite.red

-----------------------------------------------
Igniting IgniteApp

✔︎ Found react-native
✔︎ Found git
/usr/local/lib/node_modules/generator-react-native-ignite/node_modules/semver/semver.js:293
    throw new TypeError('Invalid Version: ' + version);
    ^

TypeError: Invalid Version:
    at new SemVer (/usr/local/lib/node_modules/generator-react-native-ignite/node_modules/semver/semver.js:293:11)
    at compare (/usr/local/lib/node_modules/generator-react-native-ignite/node_modules/semver/semver.js:566:10)
    at Function.lt (/usr/local/lib/node_modules/generator-react-native-ignite/node_modules/semver/semver.js:600:10)
    at /usr/local/lib/node_modules/generator-react-native-ignite/app/index.js:199:30
    at /usr/local/lib/node_modules/generator-react-native-ignite/node_modules/shelljs/src/exec.js:167:7
    at ChildProcess.exithandler (child_process.js:214:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)

~/code/sandbox
☻
```

**Comment by skellock** [comment]
Do you have `rnpm` installed?

**Comment by jschoolcraft** [comment]
I did, or thought I did.  But `rnpm --version` gave me pjson errors.

I `npm i -g rnpm` and then `ignite new IgniteApp` worked.

**Comment by skellock** [comment]
Great!  Ya, we're in an awkward period right now as `rnpm` is now rolled into `react-native link`.   Once we bump our version to 0.28+, we'll update the instructions and scripts to deprecate `rnpm`.

We were waiting a bit to see if `react-native-router-flux` would be compatible with 0.28 first.   

Our dependencies have dependencies.  hehe.
