### ISSUE TITLE
'CI' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by kittugit** [infinitered/ignite#195]
Tried to create new app.. Getting the following error..  Can someone help on this?
```
`C:\Users\kittu>ignite new IgniteApp
This command requires yo to be installed.
Installing yo...
'CI' is not recognized as an internal or external command,
operable program or batch file.
� Setting IgniteApp on FIRE! �
'yo' is not recognized as an internal or external command,
operable program or batch file.
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn yo ENOENT
    at notFoundError (C:\Users\kittu\AppData\Roaming\npm\node_modules\react-native-ignite\node_modules\cross-spawn\lib\enoent.js:11:11)
    at verifyENOENT (C:\Users\kittu\AppData\Roaming\npm\node_modules\react-native-ignite\node_modules\cross-spawn\lib\enoent.js:46:16)
    at ChildProcess.cp.emit (C:\Users\kittu\AppData\Roaming\npm\node_modules\react-native-ignite\node_modules\cross-spawn\lib\enoent.js:33:19)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)`
```

**Comment by GantMan** [comment]
hrmmm, can you elaborate on your environment?

Looks like `yo` failed to install.   Can you try a manual `npm i -g yo` for me?

**Comment by will-hart** [comment]
Same issue using `cmder` in Win 10. 

I was able to `npm i -g yo` and run (although it didn't complete due to another error)

**Comment by GantMan** [comment]
looks like we're too optimistic that things will install properly.   We'll have to build in better verification.   I thought we were checking for return values... so looks like I'll need to spin up a virtual machine.

**Comment by kittugit** [comment]
@GantMan Thanks for your quick response..
After uninstall and install yo, i'm getting the following error..

`
C:\Users\kittu>ignite new MyApp
� Setting MyApp on FIRE! �
C:\Users\kittu\AppData\Roaming\npm\node_modules\yo\node_modules\configstore\index.js:69
                                throw err;
                                ^

Error: EPERM: operation not permitted, rename 'C:\Users\kittu\.config\configstore\insight-yo.json.1459095819' -> 'C:\Users\kittu\.config\configstore\insight-yo.json'
    at Error (native)
    at Object.fs.renameSync (fs.js:681:18)
    at Function.writeFileSync [as sync] (C:\Users\kittu\AppData\Roaming\npm\node_modules\yo\node_modules\write-file-atomic\index.js:39:8)
    at Object.create.all.set (C:\Users\kittu\AppData\Roaming\npm\node_modules\yo\node_modules\configstore\index.js:62:21)
    at Object.Configstore.set (C:\Users\kittu\AppData\Roaming\npm\node_modules\yo\node_modules\configstore\index.js:93:11)
    at Insight.Object.defineProperty.set (C:\Users\kittu\AppData\Roaming\npm\node_modules\yo\node_modules\insight\lib\index.js:50:15)
    at Object.<anonymous> (C:\Users\kittu\AppData\Roaming\npm\node_modules\yo\lib\cli.js:184:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)`

**Comment by GantMan** [comment]
It looks like we'll need #196 worked all the way through, in order to resolve these tickets.

**Comment by GantMan** [comment]
closed in favor of 196

**Comment by HumayunSheikh** [comment]
> Same issue using `cmder` in Win 10.
> 
> I was able to `npm i -g yo` and run (although it didn't complete due to another error #138)

it works for me... Thanks

**Comment by CryptoGolden** [comment]
I solved
-my script
"scripts": {
    "analyze": "source-map-explorer 'build/static/js/*.js'",
    "start": "react-scripts start",
    "build": "CI=node && GENERATE_SOURCEMAP=true react-scripts build",
    "test": "react-scripts test --testPathIgnorePatterns=/src/__tests__/config/",
    "test:config": "react-scripts test --testPathPattern=/src/__tests__/config/",


-update
"scripts": {
    "analyze": "source-map-explorer 'build/static/js/*.js'",
    "start": "react-scripts start",
    "build": "react-scripts build",

consider "build"
