### ISSUE TITLE
Error after cloning fresh boilerplate. Unable to run.

### ISSUE THREAD

**Issue by Kirk-Str** [infinitered/ignite#1963]
What's going on?

Unable to run a fresh project after cloning the repo. Fighting with it for the last one week. What's going on? 

I used to remove `expo-linear-gradient` fix the issue last week. But this new release throws entirely different issue now.

Steps to reproduce

1.  npx ignite-cli new PizzaApp --bundle=com.infinitered.pizzaapp
2. npx react-native run-android
3. getting the following error now.

*Also the android package name does not get changed.

The error output.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS D:\Workspace\Heilo\Cinnamon> npx react-native run-android
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
warn Package expo-modules-core has been ignored because it contains invalid configuration. Reason: "dependency.platforms.ios" must be of type 
object
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 1578 file(s) to forward-jetify. Using 8 workers...
info Starting JS server...
info Installing the app...

> Configure project :app
Unable to detect AGP versions for included builds. All projects in the build should use the same AGP version. Class name for the included build object: org.gradle.composite.internal.DefaultIncludedBuild$IncludedBuildImpl_Decorated.

> Configure project :expo

Using expo modules
  - expo-application (4.1.0)
  - expo-constants (13.1.1)
  - expo-error-recovery (3.1.0)
  - expo-file-system (14.0.0)
  - expo-font (10.1.0)
  - expo-keep-awake (10.1.1)
  - expo-linear-gradient (11.3.0)
  - expo-localization (13.0.0)
  - expo-modules-core (0.9.2)

> Task :expo-constants:createDebugExpoConfig
Execution optimizations have been disabled for task ':expo-constants:createDebugExpoConfig' to ensure correctness due to the following reasons:
  - Gradle detected a problem with the following location: 'D:\Workspace\Heilo\Cinnamon\android'. Reason: Task ':expo-constants:createDebugExpoConfig' uses this output of task ':app:checkDebugAarMetadata' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.3.3/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: 'D:\Workspace\Heilo\Cinnamon\android'. Reason: Task ':expo-constants:createDebugExpoConfig' uses this output of task ':app:compileDebugAidl' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.3.3/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: 'D:\Workspace\Heilo\Cinnamon\android'. Reason: Task ':expo-constants:createDebugExpoConfig' uses this output of task ':app:compileDebugRenderscript' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.3.3/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: 'D:\Workspace\Heilo\Cinnamon\android'. Reason: Task ':expo-constants:createDebugExpoConfig' uses this output of task ':app:compileDebugShaders' without declaring an explicit or implicit dependency. This can lead to incorrect 
results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.3.3/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: 'D:\Workspace\Heilo\Cinnamon\android'. Reason: Task ':expo-constants:createDebugExpoConfig' uses this output of task ':app:generateDebugBuildConfig' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.3.3/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: 'D:\Workspace\Heilo\Cinnamon\android'. Reason: Task ':expo-constants:createDebugExpoConfig' uses this output of task ':app:mergeDebugShaders' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.3.3/userguide/validation_problems.html#implicit_dependency for more details about this problem.

> Task :app:compileDebugJavaWithJavac

> Task :app:compileDebugJavaWithJavac FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.     

See https://docs.gradle.org/7.3.3/userguide/command_line_interface.html#sec:command_line_warnings

Execution optimizations have been disabled for 1 invalid unit(s) of work during this build to ensure correctness.
Please consult deprecation warnings for more details.
248 actionable tasks: 5 executed, 243 up-to-date
D:\Workspace\Heilo\Cinnamon\android\app\src\main\java\com\cinnamon\newarchitecture\MainApplicationReactNativeHost.java:22: error: cannot find 
symbol
import com.helloworld.BuildConfig;
                     ^
  symbol:   class BuildConfig
  location: package com.helloworld
D:\Workspace\Heilo\Cinnamon\android\app\src\main\java\com\cinnamon\MainActivity.java:38: error: cannot find symbol
      reactRootView.setIsFabric(BuildConfig.IS_NEW_ARCHITECTURE_ENABLED);
                                ^
  symbol:   variable BuildConfig
  location: class MainActivityDelegate
D:\Workspace\Heilo\Cinnamon\android\app\src\main\java\com\cinnamon\MainApplication.java:22: error: cannot find symbol
          return BuildConfig.DEBUG;
                 ^
  symbol: variable BuildConfig
D:\Workspace\Heilo\Cinnamon\android\app\src\main\java\com\cinnamon\MainApplication.java:45: error: cannot find symbol
    if (BuildConfig.IS_NEW_ARCHITECTURE_ENABLED) {
        ^
  symbol:   variable BuildConfig
  location: class MainApplication
D:\Workspace\Heilo\Cinnamon\android\app\src\main\java\com\cinnamon\MainApplication.java:45: error: illegal parenthesized expression
    if (BuildConfig.IS_NEW_ARCHITECTURE_ENABLED) {
       ^
D:\Workspace\Heilo\Cinnamon\android\app\src\main\java\com\cinnamon\MainApplication.java:56: error: cannot find symbol
    ReactFeatureFlags.useTurboModules = BuildConfig.IS_NEW_ARCHITECTURE_ENABLED;
                                        ^
  symbol:   variable BuildConfig
  location: class MainApplication
D:\Workspace\Heilo\Cinnamon\android\app\src\main\java\com\cinnamon\MainApplication.java:70: error: cannot find symbol
    if (BuildConfig.DEBUG) {
        ^
  symbol:   variable BuildConfig
  location: class MainApplication
D:\Workspace\Heilo\Cinnamon\android\app\src\main\java\com\cinnamon\MainApplication.java:70: error: illegal parenthesized expression
    if (BuildConfig.DEBUG) {
       ^
D:\Workspace\Heilo\Cinnamon\android\app\src\main\java\com\cinnamon\newarchitecture\MainApplicationReactNativeHost.java:42: error: cannot find 
symbol
    return BuildConfig.DEBUG;
           ^
  symbol:   variable BuildConfig
  location: class MainApplicationReactNativeHost
Note: D:\Workspace\Heilo\Cinnamon\android\app\src\debug\java\com\cinnamon\ReactNativeFlipper.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
9 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 37s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081
D:\Workspace\Heilo\Cinnamon\android\app\src\main\java\com\cinnamon\newarchitecture\MainApplicationReactNativeHost.java:22: error: cannot find 
symbol
import com.helloworld.BuildConfig;
                     ^
  symbol:   class BuildConfig
  location: package com.helloworld
D:\Workspace\Heilo\Cinnamon\android\app\src\main\java\com\cinnamon\MainActivity.java:38: error: cannot find symbol
      reactRootView.setIsFabric(BuildConfig.IS_NEW_ARCHITECTURE_ENABLED);
                                ^
  symbol:   variable BuildConfig
  location: class MainActivityDelegate
D:\Workspace\Heilo\Cinnamon\android\app\src\main\java\com\cinnamon\MainApplication.java:22: error: cannot find symbol
          return BuildConfig.DEBUG;
                 ^
  symbol: variable BuildConfig
D:\Workspace\Heilo\Cinnamon\android\app\src\main\java\com\cinnamon\MainApplication.java:45: error: cannot find symbol
    if (BuildConfig.IS_NEW_ARCHITECTURE_ENABLED) {
        ^
  symbol:   variable BuildConfig
  location: class MainApplication
D:\Workspace\Heilo\Cinnamon\android\app\src\main\java\com\cinnamon\MainApplication.java:45: error: illegal parenthesized expression
    if (BuildConfig.IS_NEW_ARCHITECTURE_ENABLED) {
       ^
D:\Workspace\Heilo\Cinnamon\android\app\src\main\java\com\cinnamon\MainApplication.java:56: error: cannot find symbol
    ReactFeatureFlags.useTurboModules = BuildConfig.IS_NEW_ARCHITECTURE_ENABLED;
                                        ^
  symbol:   variable BuildConfig
  location: class MainApplication
D:\Workspace\Heilo\Cinnamon\android\app\src\main\java\com\cinnamon\MainApplication.java:70: error: cannot find symbol
    if (BuildConfig.DEBUG) {
        ^
  symbol:   variable BuildConfig
  location: class MainApplication
D:\Workspace\Heilo\Cinnamon\android\app\src\main\java\com\cinnamon\MainApplication.java:70: error: illegal parenthesized expression
    if (BuildConfig.DEBUG) {
       ^
D:\Workspace\Heilo\Cinnamon\android\app\src\main\java\com\cinnamon\newarchitecture\MainApplicationReactNativeHost.java:42: error: cannot find 
symbol
    return BuildConfig.DEBUG;
           ^
  symbol:   variable BuildConfig
  location: class MainApplicationReactNativeHost
Note: D:\Workspace\Heilo\Cinnamon\android\app\src\debug\java\com\cinnamon\ReactNativeFlipper.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
9 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Note: Recompile with -Xlint:deprecation for details.
9 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

    at makeError (D:\Workspace\Heilo\Cinnamon\node_modules\execa\index.js:174:9)
    at D:\Workspace\Heilo\Cinnamon\node_modules\execa\index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (D:\Workspace\Heilo\Cinnamon\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:109:5)
    at async Command.handleAction (D:\Workspace\Heilo\Cinnamon\node_modules\@react-native-community\cli\build\index.js:192:9)
info Run CLI with --verbose flag for more details.

---

##################################################

`npx ignite-cli doctor` results:
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
System
  platform           win32       
  arch               x64         
  cpu                8 cores      Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz 
  directory          Cinnamon     D:\Workspace\Heilo\Cinnamon
C:\Users\STR\AppData\Local\npm-cache\_npx\e31027f3785124a8\node_modules\gluegun\build\index.js:13
    throw up;
    ^

SyntaxError: Unexpected token p in JSON at position 1
    at JSON.parse (<anonymous>)
    at C:\Users\STR\AppData\Local\npm-cache\_npx\e31027f3785124a8\node_modules\ignite-cli\build\tools\packager.js:205:33
    at C:\Users\STR\AppData\Local\npm-cache\_npx\e31027f3785124a8\node_modules\ignite-cli\build\tools\packager.js:281:54
    at step (C:\Users\STR\AppData\Local\npm-cache\_npx\e31027f3785124a8\node_modules\ignite-cli\build\tools\packager.js:44:23)
    at Object.next (C:\Users\STR\AppData\Local\npm-cache\_npx\e31027f3785124a8\node_modules\ignite-cli\build\tools\packager.js:25:53)
    at fulfilled (C:\Users\STR\AppData\Local\npm-cache\_npx\e31027f3785124a8\node_modules\ignite-cli\build\tools\packager.js:16:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by Balhut** [comment]
I kind of resolved that problem by finding all of "com.helloworld" occurrences and then replaced them with "com.infinitered.pizzaapp". The next step was to change "HelloWorld" in Java files to "com.infinitered.pizzaapp" and go to the main index.js file, there in AppRegistry.registerComponent I had to change "PizzaApp" for "com.infinitered.pizzaapp" and it started to work for me. Probably not the best solution, but at least it works.

**Comment by mazenchami** [comment]
@Kirk-Str & @Balhut, thank you for surfacing this issue. @yulolimum and I just released a new version of Ignite (v7.13.1), that solves this issue. Please give it a try and open up a new issue if this still persists. Thanks again!
