### ISSUE TITLE
ignite cli crashes when creating a new project

### ISSUE THREAD

**Issue by NoMoreTickets** [infinitered/ignite#1975]
What's going on?

* platform: mac OS Monterey 12.3
* Node version: v16.16.0
* npm version: 8.11.0

When I try running 

```npx ignite-cli new Pizza --expo```

I get an an error with the following stack trace:

   · · · · · · · · · · · · · · · · · · 🔥 Ignite 🔥 · · · · · · · · · · · · · · · · · ·

    █ Creating Pizza using Ignite 7.14.1
    █ Powered by Infinite Red - https://infinite.red
    █ Using expo-cli@4 with npm
    █ Bundle identifier: com.pizza
    █ Path: /Users/ilanvolow/dev/dreamland/Pizza
    ────────────────────────────────────────────────

    ⠋ Igniting app
/Users/ilanvolow/.npm/_npx/e31027f3785124a8/node_modules/gluegun/build/index.js:13
    throw up;
    ^
Error: Cannot find module 'chalk'
Require stack:
- /Users/ilanvolow/.npm/_npx/b9bfc565999cbe87/node_modules/expo-cli/build/log.js
- /Users/ilanvolow/.npm/_npx/b9bfc565999cbe87/node_modules/expo-cli/build/exp.js
- /Users/ilanvolow/.npm/_npx/b9bfc565999cbe87/node_modules/expo-cli/bin/expo.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at _chalk (/Users/ilanvolow/.npm/_npx/b9bfc565999cbe87/node_modules/expo-cli/src/log.ts:1:1)
    at Object.<anonymous> (/Users/ilanvolow/.npm/_npx/b9bfc565999cbe87/node_modules/expo-cli/src/log.ts:18:34)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)

(Use `node --trace-uncaught ...` to show where the exception was thrown)
---

Steps to reproduce

1.  npx ignite-cli new Pizza --expo 
2. Observe output

---

`npx ignite-cli doctor` results:

```
System
  platform           darwin                                            
  arch               arm64                                             
  cpu                10 cores     Apple M1 Pro                         
  directory          Pizza        /Users/ilanvolow/dev/dreamland/Pizza 
/Users/ilanvolow/.npm/_npx/e31027f3785124a8/node_modules/gluegun/build/index.js:13
    throw up;
    ^

SyntaxError: Unexpected token p in JSON at position 1
    at JSON.parse (<anonymous>)
    at /Users/ilanvolow/.npm/_npx/e31027f3785124a8/node_modules/ignite-cli/build/tools/packager.js:205:33
    at /Users/ilanvolow/.npm/_npx/e31027f3785124a8/node_modules/ignite-cli/build/tools/packager.js:281:54
    at step (/Users/ilanvolow/.npm/_npx/e31027f3785124a8/node_modules/ignite-cli/build/tools/packager.js:44:23)
    at Object.next (/Users/ilanvolow/.npm/_npx/e31027f3785124a8/node_modules/ignite-cli/build/tools/packager.js:25:53)
    at fulfilled (/Users/ilanvolow/.npm/_npx/e31027f3785124a8/node_modules/ignite-cli/build/tools/packager.js:16:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by NoMoreTickets** [comment]
Could not repeat after deleting caches and performing other troubleshooting actions.
