### ISSUE TITLE
Unable to resolve module react-hook-form

### ISSUE THREAD

**Issue by dharmin** [infinitered/ignite#1995]
What's going on?
react-hook-form giving error after importing and using it
```
Unable to resolve module react-hook-form from /home/saiko/PizzaApp/app/screens/demo/demo-screen.tsx: react-hook-form could not be found within the project or in these directories:
```
---

Steps to reproduce

1. Run `pnpm install react-hook-form`
2. Imported react-form-hook on demo-screen.tsx: `import { useForm, Controller } from "react-hook-form"`
3. Used `useForm` hook in DemoScreen function: `  const { register, setValue, handleSubmit, formState: { errors } } = useForm<FormData>()`
4. Got the following error stack
```
Error: Unable to resolve module react-hook-form from /home/saiko/disk/projects/PizzaApp/app/screens/demo/demo-screen.tsx: react-hook-form could not be found within the project or in these directories:
  node_modules
  ../../../node_modules
  16 | import { Api } from "../../services/api"
  17 | import { save } from "../../utils/storage"
> 18 | import { useForm } from "react-hook-form";
     |                          ^
  19 | export const logoIgnite = require("./logo-ignite.png")
  20 | export const heart = require("./heart.png")
  21 |
    at ModuleResolver.resolveDependency (/home/saiko/disk/projects/PizzaApp/node_modules/.pnpm/metro@0.67.0/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:158:15)
    at DependencyGraph.resolveDependency (/home/saiko/disk/projects/PizzaApp/node_modules/.pnpm/metro@0.67.0/node_modules/metro/src/node-haste/DependencyGraph.js:231:43)
    at Object.resolve (/home/saiko/disk/projects/PizzaApp/node_modules/.pnpm/metro@0.67.0/node_modules/metro/src/lib/transformHelpers.js:129:24)
    at resolve (/home/saiko/disk/projects/PizzaApp/node_modules/.pnpm/metro@0.67.0/node_modules/metro/src/DeltaBundler/traverseDependencies.js:396:33)
    at /home/saiko/disk/projects/PizzaApp/node_modules/.pnpm/metro@0.67.0/node_modules/metro/src/DeltaBundler/traverseDependencies.js:412:26
    at Array.reduce (<anonymous>)
    at resolveDependencies (/home/saiko/disk/projects/PizzaApp/node_modules/.pnpm/metro@0.67.0/node_modules/metro/src/DeltaBundler/traverseDependencies.js:411:33)
    at processModule (/home/saiko/disk/projects/PizzaApp/node_modules/.pnpm/metro@0.67.0/node_modules/metro/src/DeltaBundler/traverseDependencies.js:140:31)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async addDependency (/home/saiko/disk/projects/PizzaApp/node_modules/.pnpm/metro@0.67.0/node_modules/metro/src/DeltaBundler/traverseDependencies.js:230:18)

```

---

`npx ignite-cli doctor` results:
Getting following error

```
System
  platform           linux                                                 
  arch               x64                                                   
  cpu                8 cores      Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz 
  directory          PizzaApp     /home/saiko/disk/projects/PizzaApp       
/home/saiko/.npm/_npx/e31027f3785124a8/node_modules/gluegun/build/index.js:13
    throw up;
    ^

SyntaxError: Unexpected token p in JSON at position 1
    at JSON.parse (<anonymous>)
    at /home/saiko/.npm/_npx/e31027f3785124a8/node_modules/ignite-cli/build/tools/packager.js:205:33
    at /home/saiko/.npm/_npx/e31027f3785124a8/node_modules/ignite-cli/build/tools/packager.js:281:54
    at step (/home/saiko/.npm/_npx/e31027f3785124a8/node_modules/ignite-cli/build/tools/packager.js:44:23)
    at Object.next (/home/saiko/.npm/_npx/e31027f3785124a8/node_modules/ignite-cli/build/tools/packager.js:25:53)
    at fulfilled (/home/saiko/.npm/_npx/e31027f3785124a8/node_modules/ignite-cli/build/tools/packager.js:16:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by kenjishiromajp** [comment]
Hey, I don't know if it is the same error but I think I could solve it here by changing the `metro.config.js`. 
I',m not quite sure but I think you need to add the `mjs` as an extension to the `sourceExts`, maybe cjs is not there. I hope it works for u too!

```js
/**
 * We're using a custom metro config because we want to support symlinks
 * out of the box. This allows you to use pnpm and/or play better in a monorepo.
 *
 * You can safely delete this file and remove @rnx-kit/metro-* if you're not
 * using PNPM or monorepo or symlinks at all.
 *
 * However, it doesn't hurt to have it either.
 */
const { makeMetroConfig } = require("@rnx-kit/metro-config")
const MetroSymlinksResolver = require("@rnx-kit/metro-resolver-symlinks")
const { getDefaultConfig } = require("metro-config")

module.exports = (async () => {
  const defaultConfig = await getDefaultConfig()
  return makeMetroConfig({
    projectRoot: __dirname,
    // watchFolders: [`${__dirname}/../..`], // for monorepos
    resolver: {
      /**
       * This custom resolver is for if you're using symlinks.
       *
       * You can disable it if you're not using pnpm or a monorepo or symlinks.
       */
      resolveRequest: MetroSymlinksResolver(),
      sourceExts: [...defaultConfig.resolver.sourceExts, 'mjs', 'cjs'],
      assetExts: [...defaultConfig.resolver.assetExts, "bin"],
    },
  })
})()

```

**Comment by dharmin** [comment]
@kenjishiromajp Thanks, It worked! :+1:
