### ISSUE TITLE
Gluegun error when initialising with Expo

### ISSUE THREAD

**Issue by jvgeee** [infinitered/ignite#2028]
Trying to ignite a new project using Expo. I've tried using NPX as well as installing ignite-cli locally (7.14.2) and the same error occurs.

/Users/jvg/.nvm/versions/node/v16.17.0/lib/node_modules/ignite-cli/node_modules/gluegun/build/index.js:13
    throw up;
    ^
[09:30:55] Invalid or unexpected token
[09:30:55] /Users/jvg/.npm/_npx/b9bfc565999cbe87/node_modules/make-fetch-happen/lib/cache/entry.js:1

SyntaxError: Invalid or unexpected token
    at Object.compileFunction (node:vm:360:18)
    at wrapSafe (node:internal/modules/cjs/loader:1055:15)
    at Module._compile (node:internal/modules/cjs/loader:1090:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/jvg/.npm/_npx/b9bfc565999cbe87/node_modules/make-fetch-happen/lib/cache/index.js:2:20)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/jvg/.npm/_npx/b9bfc565999cbe87/node_modules/make-fetch-happen/lib/fetch.js:7:15)

----

`npx ignite-cli doctor` results:

System
  platform           darwin
  arch               arm64
  cpu                8 cores      Apple M1
  directory          Sites        /Users/jvg/Sites

JavaScript (and globally-installed packages)
  node                16.17.0      /Users/jvg/.nvm/versions/node/v16.17.0/bin/node
  npm                 8.15.0       /Users/jvg/.nvm/versions/node/v16.17.0/bin/npm
    corepack          0.12.1
    ignite-cli        7.14.2
    npm               8.15.0
  yarn                1.22.19      /opt/homebrew/bin/yarn
    create-next-app   10.1.3
    ios-deploy        1.11.4
  pnpm                -            not installed
  expo                -            not installed

Ignite
  ignite-cli         7.14.2       /Users/jvg/.nvm/versions/node/v16.17.0/bin/ignite
  ignite src         build        /Users/jvg/.nvm/versions/node/v16.17.0/lib/node_modules/ignite-cli/build

Android
  java               18.0.2       /usr/bin/java
  android home       -            /Users/jvg/Android/Sdk

iOS
  xcode              13.4.1
  cocoapods          1.11.3       /usr/local/bin/pod

**Comment by jvgeee** [comment]
Update: Did the following to fix it:

1. Cleaned out my global node modules with `npm ls -gp --depth=0 | awk -F/ '/node_modules/ && !/\/npm$/ {print $NF}' | xargs npm -g rm`
2. Clean out NPX cache with `npx clear-npx-cache`
3. Clean out NPM cache with `npm cache clean --force`

After doing this it started working.
