### ISSUE TITLE
[Maverick] Relative target-path throws an error

### ISSUE THREAD

**Issue by jamonholmgren** [infinitered/ignite#2141]
### Describe the bug

Specifying a relative target-path on the CLI throws an error.

```
npx ignite-cli@new new PizzaApp --bundle=com.pizzaapp --git --install-deps --packager=yarn --target-path=./PizzaApp --overwrite
```

I get this error (note the double PizzaApp in the path):

```
/Users/jh/Code/ignite-cli/node_modules/fs-jetpack/lib/copy.js:52
  const err = new Error(`Path to copy doesn't exist ${path}`);
              ^
Error: Path to copy doesn't exist /Users/jh/Code/Temp/PizzaApp/PizzaApp/yarn.lock
    at generateNoSourceError (/Users/jh/Code/ignite-cli/node_modules/fs-jetpack/lib/copy.js:52:15)
    at /Users/jh/Code/ignite-cli/node_modules/fs-jetpack/lib/copy.js:170:15 {
  code: 'ENOENT'
}
```

### Ignite version

Maverick

### Additional info

no

**Comment by jamonholmgren** [comment]
Note this also happens if you specify from home (`~`), like `~/Code/PizzaApp`.

Probably just need to run `filesystem.path` on it to normalize the path.

**Comment by joshuayoes** [comment]
Resolved by https://github.com/infinitered/ignite/pull/2154
