### ISSUE TITLE
Error: Asset not found

### ISSUE THREAD

**Issue by jamonholmgren** [infinitered/ignite#2226]
### Describe the bug

When opening on iOS using `yarn expo:ios`, I'm getting this error:

```
› Opening on iOS...
› Opening exp://192.168.1.33:19000 on iPhone 14
› Press ? │ show all commands
Error: Asset not found: /Users/jh/Code/workshop/AdvancedChat/assets/images/icon.png for platform: null
    at getAbsoluteAssetRecord (/Users/jh/Code/workshop/AdvancedChat/node_modules/metro/src/Assets.js:110:11)
    at async getAsset (/Users/jh/Code/workshop/AdvancedChat/node_modules/metro/src/Assets.js:238:18)
    at async Server._processSingleAssetRequest (/Users/jh/Code/workshop/AdvancedChat/node_modules/metro/src/Server.js:366:20)
    at async Server._processRequest (/Users/jh/Code/workshop/AdvancedChat/node_modules/metro/src/Server.js:441:7)
```

It doesn't appear to prevent the app from starting.

### Ignite version

8.0.0

### Additional info

```
System
  platform           darwin
  arch               arm64
  cpu                10 cores       Apple M1 Max
  directory          AdvancedChat   /Users/jh/Code/workshop/AdvancedChat

JavaScript (and globally-installed packages)
  node                            14.20.0      /opt/homebrew/opt/node@14/bin/node
  npm                             6.14.17      /opt/homebrew/opt/node@14/bin/npm
    eas-cli                       0.52.0
    firebase-tools                11.1.0
    ios-deploy                    1.11.4
    npm                           8.17.0
  yarn                            1.22.19      /opt/homebrew/bin/yarn
    create-react-native-library   0.20.1
  pnpm                            -            not installed
  expo                            46.0.13      managed

Ignite
  ignite-cli         8.0.0        /Users/jh/.npm/_npx/8249/bin/ignite
  ignite src         build        /Users/jh/.npm/_npx/8249/lib/node_modules/ignite-cli/build

Android
  java               11.0.14      /Users/jh/.sdkman/candidates/java/current/bin/java
  android home       -            /Users/jh/Library/Android/sdk

iOS
  xcode              14.0.1
  cocoapods          1.11.3       /opt/homebrew/bin/pod

Tools
  git                git version 2.37.0 (Apple Git-136)   /usr/bin/git
  ```

**Comment by frankcalise** [comment]
Possibly related?

https://github.com/expo/expo-cli/issues/4248
