### ISSUE TITLE
ignit-cli generator failed

### ISSUE THREAD

**Issue by AmjadOmari** [infinitered/ignite#2243]
### Describe the bug

generating components, models, navigators, or screens is not working

steps to reproduce:

1. `npx ignite-cli@next new PizzaApp --yes`
2. `cd PizzaApp`
3. `yarn install`
4. `npx ignite generate component spinner`

expect: create the component spinner
actual: command failed

```
 ERROR  Failed to compile with 4 errors                              10:49:37 AM

 error  

Entry module not found: Error: Can't resolve 'react-color' in '/Users/amjadomari/Documents/ReactNativeProjects/PizzaApp'

 error  

Entry module not found: Error: Can't resolve 'react-ideal-image' in '/Users/amjadomari/Documents/ReactNativeProjects/PizzaApp'

 error  

Entry module not found: Error: Can't resolve 'react-waypoint' in '/Users/amjadomari/Documents/ReactNativeProjects/PizzaApp'

 error  in /Users/amjadomari/.npm/_npx/0e11d984049d509d/node_modules/ignite/src/app/index.js

Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@babel/plugin-transform-react-constant-elements' imported from /Users/amjadomari/Documents/ReactNativeProjects/PizzaApp/babel-virtual-resolve-base.js
    at __node_internal_ (/Users/amjadomari/Documents/ReactNativeProjects/PizzaApp/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:2844:9)
    at __node_internal_ (/Users/amjadomari/Documents/ReactNativeProjects/PizzaApp/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:2802:11)
    at new NodeError (/Users/amjadomari/Documents/ReactNativeProjects/PizzaApp/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:2795:5)
    at packageResolve (/Users/amjadomari/Documents/ReactNativeProjects/PizzaApp/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:3451:9)
    at moduleResolve (/Users/amjadomari/Documents/ReactNativeProjects/PizzaApp/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:3485:18)
    at defaultResolve (/Users/amjadomari/Documents/ReactNativeProjects/PizzaApp/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:3524:13)
    at /Users/amjadomari/Documents/ReactNativeProjects/PizzaApp/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:3547:14
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/amjadomari/Documents/ReactNativeProjects/PizzaApp/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:63:103)
    at _next (/Users/amjadomari/Documents/ReactNativeProjects/PizzaApp/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:65:194)
    at /Users/amjadomari/Documents/ReactNativeProjects/PizzaApp/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:65:364
    at new Promise (<anonymous>)
    at /Users/amjadomari/Documents/ReactNativeProjects/PizzaApp/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:65:97
    at resolve (/Users/amjadomari/Documents/ReactNativeProjects/PizzaApp/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:3537:19)
    at /Users/amjadomari/Documents/ReactNativeProjects/PizzaApp/node_modules/@babel/core/lib/config/files/import-meta-resolve.js:38:38
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/amjadomari/Documents/ReactNativeProjects/PizzaApp/node_modules/@babel/core/lib/config/files/import-meta-resolve.js:20:103)
    at _next (/Users/amjadomari/Documents/ReactNativeProjects/PizzaApp/node_modules/@babel/core/lib/config/files/import-meta-resolve.js:22:194)

 @ multi (webpack)-inject-plugin/dist/webpack-inject-plugin.module.js /Users/amjadomari/.npm/_npx/0e11d984049d509d/node_modules/ignite/src/app/index.js
```

### Ignite version

8.2.0

### Additional info

```
System
  platform           darwin                                                                
  arch               x64                                                                   
  cpu                8 cores      Apple M1                                                 
  directory          PizzaApp     /Users/amjadomari/Documents/ReactNativeProjects/PizzaApp 

JavaScript (and globally-installed packages)
  node               14.17.5                                   /usr/local/bin/node 
  npm                8.15.0                                    /usr/local/bin/npm  
    cordova          11.0.0                                                        
    npm              8.15.0                                                        
    react-native     0.69.2                                                        
    yarn             1.22.19                                                       
  yarn               1.22.19                                   /usr/local/bin/yarn 
  pnpm               6.29.1                                    /usr/local/bin/pnpm 
                     <no pnpm global package info available>                       
  expo               46.0.13                                   managed             

Ignite
  ignite-cli         8.2.0        /Users/amjadomari/.npm/_npx/e31027f3785124a8/node_modules/.bin/ignite      
  ignite src         build        /Users/amjadomari/.npm/_npx/e31027f3785124a8/node_modules/ignite-cli/build 

Android
  java               16.0.2       /usr/bin/java 
  android home       -            undefined     

iOS
  xcode              14.0.1     
  cocoapods          1.11.3       /usr/local/bin/pod 

Tools
  git                git version 2.37.0 (Apple Git-136)   /usr/bin/git 
```

**Comment by jamonholmgren** [comment]
@AmjadOmari  Can you try without the `@next` tag? Version 8 is now released.

**Comment by AmjadOmari** [comment]
> 

I already have a built project that has a lot of changes, so how can I change it on my project?

**Comment by AmjadOmari** [comment]
I have changed the command as the following, and this is fixed the issue
from:
`npx ignite-cli generate navigator userSettings`
to:
`npx ignite-cli@next generate navigator userSettings`

**Comment by frankcalise** [comment]
Hi @AmjadOmari - yes in your original reproducible steps, step 4 indicated you used `npx ignite` and not `npx ignite-cli`. I got an error as well when doing this, however with the correct command it works!

Unlucky that ignite is a different package entirely that has nothing to do with our react native boilerplate. So double check your commands point to `ignite-cli`.

Closing this issue, please reopen if you're still experiencing trouble.
