### ISSUE TITLE
Unable to run the freshly baked boilerplate

### ISSUE THREAD

**Issue by Kirk-Str** [infinitered/ignite#2422]
###

Installed the latest version of Ignite Boiletplate with regular command `npx ignite-cli@latest new PizzaApp`

Bombarded with the following error. Tried different installs too, getting the same error everytime.

I completely wiped the gradle cache folder and re-tried, nothing changes.

```
BUILD FAILED in 24s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
Could not open settings generic class cache for settings file 'D:\Workspace\jegg\clone\hiddomx\android\settings.gradle' (C:\Users\jagger\.gradle\caches\7.5.1\scripts\9kxmfhyuq8m49iv7r9ouole7f).
> BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 63

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 24s

    at makeError (D:\Workspace\jegg\clone\hiddomx\node_modules\execa\index.js:174:9)
    at D:\Workspace\jegg\clone\hiddomx\node_modules\execa\index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (D:\Workspace\jegg\clone\hiddomx\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:109:5)
    at async Command.handleAction (D:\Workspace\jegg\clone\hiddomx\node_modules\@react-native-community\cli\build\index.js:142:9)
info Run CLI with --verbose flag for more details.
```

### Ignite version

8.6.1

### Additional info

```
PS D:\Workspace\jegg\clone\hiddomx\android> npx ignite-cli doctor
System
  platform           win32       
  arch               x64         
  cpu                8 cores      Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  directory          android      D:\Workspace\jegg\clone\hiddomx\android

JavaScript (and globally-installed packages)
  node               16.17.0      D:\Program Files\nodejs\node.EXE
  npm                8.15.0       D:\Program Files\nodejs\npm.CMD
    firebase-tools   11.25.2     
    ignite-cli       8.5.1       
    react-devtools   4.27.4      
    yarn             1.22.19     
  yarn               1.22.19      C:\Users\jegg\AppData\Roaming\npm\yarn.CMD
  pnpm               -            not installed
  expo               47.0.14      managed

Ignite
  ignite-cli         8.5.1        C:\Users\jegg\AppData\Roaming\npm\ignite.CMD
  ignite src         build        C:\Users\jegg\AppData\Roaming\npm\node_modules\ignite-cli\build

Android
  java               19.0.2       D:\Program Files\Java\jdk-19\bin\java.EXE
  android home       -            undefined

Tools
  git                git version 2.37.3.windows.1   D:\Program Files\Git\cmd\git.EXE 
```

**Comment by frankcalise** [comment]
Hi @Kirk-Str - I believe you have the wrong JDK installed, please see the Environment Setup docs from React Native: https://reactnative.dev/docs/environment-setup?os=windows&platform=android#jdk

The other option you have is to quickly try `yarn expo:start` to see if you can get up and running with Expo (but I understand that you may not want to)
