### ISSUE TITLE
Can't start new App (TypeError: Expected `count` to be a `number`, got `string`)

### ISSUE THREAD

**Issue by hazboun** [infinitered/ignite#252]
When running `ignite n myApp`, getting this error:

/usr/local/lib/node_modules/indent-string/index.js:13
		throw new TypeError(`Expected \`count\` to be a \`number\`, got \`${typeof count}\``);
		^

TypeError: Expected `count` to be a `number`, got `string`
    at module.exports (/usr/local/lib/node_modules/indent-string/index.js:13:9)
    at module.exports (/usr/local/lib/node_modules/yo/node_modules/meow/index.js:20:20)
    at Object.<anonymous> (/usr/local/lib/node_modules/yo/lib/cli.js:16:11)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:142:18)
    at node.js:939:3

- `node -v`: v5.9.1
- `npm -v`: 3.8.3
- `react-native -v` (cli): 1.0.0
- `react-native -v`: 0.29.1
- `ignite --version`: 1.3.0

**Comment by GantMan** [comment]
This was likely due to an older version of yeoman.  Please update

**Comment by GantMan** [comment]
closing due to inactivity.
