### ISSUE TITLE
ignite-cli is unable to create new app in windows

### ISSUE THREAD

**Issue by chankruze** [infinitered/ignite#2545]
### Describe the bug

Does `ignite-cli` only works in linux and mac os ? 

```
PS E:\react-native> npx ignite-cli@latest new PizzaApp13 --yes





                                               .;;,.    .clll.
                                              .clll,    ,llll.           ...
                                               .,;,.    ;lllc'.,.   .';cllllc,
     .',,.                           ...      .'',,. .:lllllllll. .;lllc:;clll,
    .llll,                    .,...;cllll:.   ,llll, .llllllc,,'  clll:'.,cllc.
    ,llll'       ......;::.  'llcclllllllll'  ,llll,   .llll.    ,lllllllll:'
    ,llll.    .;clllllclll.  'llllc,..,llll,  :llll.   'llll.    ,lllc,''..
    ;llll.   :llllc:cllllc.  ,llll.   .llll, .lllll.   ,lllc...  ,lll:...';:.
   .llllc.  ;lll;.   :lll,   ;lll;    'llll, .llllc.   ,llllcll' .:lllllllll,
   .llll,  'lll:    .clll,   :lll,    ,llll. 'llll,    'lllllcc'   ';::::;'.
   .llll,  ,lll:    .llll'  .llll,    ;llll. ,llll,     .....             .',..
   ,llll.  'llll:,,:cllll.  .lllc.    .''..  ... ....',;         ..',,:::;'..
   ,llll.   'clllllllllll.     .....        ..,::cllllc.   .',:clllc;,'.
   :llll.     ',;,'.;lllc...,;:clll;  ..',:cllllllllll:,;clllllc;,'.
   llll:        ...'cllllllllllllll::cllllllc;,',cllllllllc;'..
   llll,   ..,clllllllll::,,.,lllllllc:,'...    :lllllc,..
   c:;,.  .cllllc:;:llll.    ,ll:;,..          ;ll:,..
          :lll,.  .clll,     ..               .,..
          :lll:,,cllll,
          .cllllllllc'
           .'cllll:.



    █ Creating PizzaApp13 using Ignite 8.10.1
    █ Powered by  ∞ Infinite Red  (https://infinite.red)
    █ Package Manager: npm
    █ Bundle identifier: com.pizzaapp13
    █ Path: E:\react-native\PizzaApp13
    ────────────────────────────────────────────────────

    🖨  3D-printing a new React Native app
    🎨 Getting those last few details perfect
    🧶 Installing npm dependencies (wow these are heavy)
C:\Users\chankruze\AppData\Local\npm-cache\_npx\bec2839915ba8fc3\node_modules\gluegun\build\index.js:15
    throw up;
    ^

Error: Command failed with exit code 1: which unix2dos
'which' is not recognized as an internal or external command,
operable program or batch file.
    at makeError (C:\Users\chankruze\AppData\Local\npm-cache\_npx\bec2839915ba8fc3\node_modules\execa\lib\error.js:60:11)
    at handlePromise (C:\Users\chankruze\AppData\Local\npm-cache\_npx\bec2839915ba8fc3\node_modules\execa\index.js:118:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  shortMessage: 'Command failed with exit code 1: which unix2dos',
  command: 'which unix2dos',
  escapedCommand: 'which unix2dos',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: "'which' is not recognized as an internal or external command,\r\n" +
    'operable program or batch file.',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}

Node.js v20.9.0
PS E:\react-native>
```

### Ignite version

8.10.1

### Additional info

```
PS E:\react-native> npx ignite-cli doctor
Need to install the following packages:
ignite-cli@8.10.1
Ok to proceed? (y) y
System
  platform           win32
  arch               x64
  cpu                12 cores       Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  directory          react-native   E:\react-native

JavaScript
  node               20.9.0       D:\nodejs\node.EXE
  npm                10.1.0       D:\nodejs\npm.CMD
  yarn               -            not installed
  pnpm               -            not installed
  expo               -            not installed

Ignite
  ignite-cli         8.10.1       C:\Users\chankruze\AppData\Local\npm-cache\_npx\e31027f3785124a8\node_modules\.bin\ignite.CMD
  ignite src         build        C:\Users\chankruze\AppData\Local\npm-cache\_npx\e31027f3785124a8\node_modules\ignite-cli\build

Android
  java               19.0.2       D:\jdk-19.0.2\bin\java.EXE
  android home       -            D:\Android\Sdk

Tools
  git                git version 2.36.1.windows.1   D:\Git\cmd\git.EXE
```

**Comment by frankcalise** [comment]
Hi, can you try `npx ignite-cli@next`?

**Comment by chankruze** [comment]
This is fixed in `npx ignite-cli@next`
