### ISSUE TITLE
Demo code cannot be cleaned

### ISSUE THREAD

**Issue by onurusluca** [infinitered/ignite#2558]
### Describe the bug

```
❯ npx ignite-cli@latest new PizzaApp3

✅ What bundle identifier? · com.pizzaapp3
✅ Where do you want to start your project? · C:\CODING\LEARNING\MOBILE APPS\PizzaApp3
✅ Choose a workflow: · Expo Go
✅ Do you want to initialize a git repository? (Y/n) · Yes
✅ Remove demo code? We recommend leaving it in if it's your first time using Ignite (y/N) · Yes
✅ Which package manager do you want to use? · npm
✅ Do you want to install dependencies? (Y/n) · No

    █ Creating PizzaApp3 using Ignite 9.0.0
    █ Powered by  ∞ Infinite Red  (https://infinite.red)
    █ Package Manager: npm
    █ Bundle identifier: com.pizzaapp3
    █ Path: C:\CODING\LEARNING\MOBILE APPS\PizzaApp3
    ────────────────────────────────────────────────────
```

Happens the same with 9.0.0-alpha.9(ignite-cli@next).

No matter what I try, demo code is still there.

```
❯ npx ignite-cli@next new IgniteApp2

✅ What bundle identifier? · com.igniteapp2
✅ Where do you want to start your project? · C:\CODING\LEARNING\MOBILE APPS\IgniteApp2
✅ Choose a workflow: · Expo Go
✅ Do you want to initialize a git repository? (Y/n) · Yes
✅ Remove demo code? We recommend leaving it in if it's your first time using Ignite (y/N) · Yes
✅ Which package manager do you want to use? · npm
✅ Do you want to install dependencies? (Y/n) · Yes

    █ Creating IgniteApp2 using Ignite 9.0.0-alpha.9
    █ Powered by  ∞ Infinite Red  (https://infinite.red)
    █ Package Manager: npm
    █ Bundle identifier: com.igniteapp2
    █ Path: C:\CODING\LEARNING\MOBILE APPS\IgniteApp2
    ────────────────────────────────────────────────────

```

### Ignite version

9.0.0

### Additional info

```
 platform           win32
  arch               x64
  cpu                12 cores     AMD Ryzen 5 5600X 6-Core Processor
  directory          PizzaApp3    C:\CODING\LEARNING\MOBILE APPS\PizzaApp3

```

**Comment by frankcalise** [comment]
@onurusluca can you describe what it is your seeing, possibly with a screenshot?

The removal of the demo includes the full demo app but not all of the screens. There will still be one screen so that the app can be rendered.

I want to make sure if this is a bug or possibly a difference in expectations.

Thanks!

**Comment by onurusluca** [comment]
@frankcalise Thanks for the reply. I am getting the exact same app as the default selections. All the code is still there too.

![image](https://github.com/infinitered/ignite/assets/51825926/2d7d5db0-4479-4ec5-9306-2ac7f57143ed)

**Comment by frankcalise** [comment]
Ok I forgot that you're running on Windows, so I'll need to switch over and work through that as well.

**Comment by onurusluca** [comment]
@frankcalise Ah, sorry. Thank you!

**Comment by frankcalise** [comment]
@onurusluca Do you mind running with your new command with `--debug` and posting the output as well?

**Comment by onurusluca** [comment]
Sorry it's a bit long. It looks like it is having problems finding paths.

```
❯ npx ignite-cli@latest new PizzaApp3 --debug
 ignite command: C:\Program Files\nodejs\node.exe C:\Users\dur2d\AppData\Local\npm-cache\_npx\bec2839915ba8fc3\node_modules\ignite-cli\bin\ignite new PizzaApp3 --debug

✅ What bundle identifier? · com.pizzaapp3
✅ Where do you want to start your project? · C:\CODING\LEARNING\MOBILE APPS\PizzaApp3
✅ Choose a workflow: · Expo Go
 worflow: expo
 needs prebuild: false
✅ Do you want to initialize a git repository? (Y/n) · Yes
✅ Remove demo code? We recommend leaving it in if it's your first time using Ignite (y/N) · Yes
 availablePackagers: npm,pnpm
✅ Which package manager do you want to use? · npm
 ignitePath: C:\Users\dur2d\AppData\Local\npm-cache\_npx\bec2839915ba8fc3\node_modules\ignite-cli
 boilerplatePath: C:\Users\dur2d\AppData\Local\npm-cache\_npx\bec2839915ba8fc3\node_modules\ignite-cli\boilerplate
✅ Do you want to install dependencies? (Y/n) · Yes
 experimentalFlags:




                                               .;;,.    .clll.
                                              .clll,    ,llll.           ...
                                               .,;,.    ;lllc'.,.   .';cllllc,
     .',,.                           ...      .'',,. .:lllllllll. .;lllc:;clll,
    .llll,                    .,...;cllll:.   ,llll, .llllllc,,'  clll:'.,cllc.
    ,llll'       ......;::.  'llcclllllllll'  ,llll,   .llll.    ,lllllllll:'
    ,llll.    .;clllllclll.  'llllc,..,llll,  :llll.   'llll.    ,lllc,''..
    ;llll.   :llllc:cllllc.  ,llll.   .llll, .lllll.   ,lllc...  ,lll:...';:.
   .llllc.  ;lll;.   :lll,   ;lll;    'llll, .llllc.   ,llllcll' .:lllllllll,
   .llll,  'lll:    .clll,   :lll,    ,llll. 'llll,    'lllllcc'   ';::::;'.
   .llll,  ,lll:    .llll'  .llll,    ;llll. ,llll,     .....             .',..
   ,llll.  'llll:,,:cllll.  .lllc.    .''..  ... ....',;         ..',,:::;'..
   ,llll.   'clllllllllll.     .....        ..,::cllllc.   .',:clllc;,'.
   :llll.     ',;,'.;lllc...,;:clll;  ..',:cllllllllll:,;clllllc;,'.
   llll:        ...'cllllllllllllll::cllllllc;,',cllllllllc;'..
   llll,   ..,clllllllll::,,.,lllllllc:,'...    :lllllc,..
   c:;,.  .cllllc:;:llll.    ,ll:;,..          ;ll:,..
          :lll,.  .clll,     ..               .,..
          :lll:,,cllll,
          .cllllllllc'
           .'cllll:.



    █ Creating PizzaApp3 using Ignite 9.0.0
    █ Powered by  ∞ Infinite Red  (https://infinite.red)
    █ Package Manager: npm
    █ Bundle identifier: com.pizzaapp3
    █ Path: C:\CODING\LEARNING\MOBILE APPS\PizzaApp3
    ────────────────────────────────────────────────────

    🖨  3D-printing a new React Native app
 C:\CODING\LEARNING\MOBILE APPS\PizzaApp3\.gitignore
 C:\Users\dur2d\AppData\Local\npm-cache\_npx\bec2839915ba8fc3\node_modules\ignite-cli\boilerplate\.gitignore.template
 C:\CODING\LEARNING\MOBILE APPS
 Changing some dependencies for Expo Go compatibility...
 {"@react-native-async-storage/async-storage":"1.18.2","expo-application":"~5.3.0","expo-font":"~11.4.0","expo-localization":"~14.3.0","@shopify/flash-list":"1.4.3"}
 expected cachePath: C:\Users\dur2d\AppData\Local\Temp\ignite\6c03f35dc83f1978e826364de25b70e4\npm
 cacheExists: false
    - Getting those last few details perfect Renaming ios/HelloWorld.xcodeproj/xcshareddata/xcschemes/HelloWorld.xcscheme to PizzaApp3.xcscheme
 Renaming ios/HelloWorldTests/HelloWorldTests.m to PizzaApp3Tests.m
 Renaming ios/HelloWorld/HelloWorld-Bridging-Header.h to PizzaApp3-Bridging-Header.h
 Renaming ios/HelloWorld/HelloWorld.entitlements to PizzaApp3.entitlements
 Renaming ios/HelloWorld.xcworkspace to PizzaApp3.xcworkspace
 Renaming ios/HelloWorld to PizzaApp3
 Renaming ios/HelloWorldTests to PizzaApp3Tests
 Renaming ios/HelloWorld.xcodeproj to PizzaApp3.xcodeproj
 Renaming bundle identifier to com.pizzaapp3
 Patching app.json - HelloWorld to PizzaApp3 and variants
 Patching package.json - HelloWorld to PizzaApp3 and variants
 Patching .maestro\Login.yaml - com.helloworld to com.pizzaapp3 and variants
 Patching .maestro\FavoritePodcast.yaml - com.helloworld to com.pizzaapp3 and variants
    🎨 Getting those last few details perfect
    \ Installing npm dependencies (wow these are heavy)
> pizza-app-3@0.0.1 postinstall
> patch-package


    | Installing npm dependencies (wow these are heavy) patch-package 6.4.7

 Applying patches...


added 1736 packages, and audited 1737 packages in 2m


167 packages are looking for funding
  run `npm fund` for details


6 moderate severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.

    🧶 Installing npm dependencies (wow these are heavy)
       Configuring app.json
    -  Removing fancy demo code Ignite bin path: node C:\Users\dur2d\AppData\Local\npm-cache\_npx\bec2839915ba8fc3\node_modules\ignite-cli\bin\ignite
    \  Removing fancy demo code Error: Command failed: node C:\Users\dur2d\AppData\Local\npm-cache\_npx\bec2839915ba8fc3\node_modules\ignite-cli\bin\ignite remove-demo C:\CODING\LEARNING\MOBILE APPS\PizzaApp3
C:\Users\dur2d\AppData\Local\npm-cache\_npx\bec2839915ba8fc3\node_modules\gluegun\build\index.js:15
    throw up;
    ^

Error: Path you want to find stuff in doesn't exist C:\CODING\LEARNING\MOBILE
    at generatePathDoesntExistError (C:\Users\dur2d\AppData\Local\npm-cache\_npx\bec2839915ba8fc3\node_modules\fs-jetpack\lib\find.js:50:15)
    at Object.findSyncInit [as sync] (C:\Users\dur2d\AppData\Local\npm-cache\_npx\bec2839915ba8fc3\node_modules\fs-jetpack\lib\find.js:111:11)
    at Object.find (C:\Users\dur2d\AppData\Local\npm-cache\_npx\bec2839915ba8fc3\node_modules\fs-jetpack\lib\jetpack.js:138:19)
    at Object.find (C:\Users\dur2d\AppData\Local\npm-cache\_npx\bec2839915ba8fc3\node_modules\ignite-cli\build\tools\demo.js:147:10)
    at C:\Users\dur2d\AppData\Local\npm-cache\_npx\bec2839915ba8fc3\node_modules\ignite-cli\build\commands\remove-demo.js:114:45
    at step (C:\Users\dur2d\AppData\Local\npm-cache\_npx\bec2839915ba8fc3\node_modules\ignite-cli\build\commands\remove-demo.js:33:23)
    at Object.next (C:\Users\dur2d\AppData\Local\npm-cache\_npx\bec2839915ba8fc3\node_modules\ignite-cli\build\commands\remove-demo.js:14:53)
    at C:\Users\dur2d\AppData\Local\npm-cache\_npx\bec2839915ba8fc3\node_modules\ignite-cli\build\commands\remove-demo.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\dur2d\AppData\Local\npm-cache\_npx\bec2839915ba8fc3\node_modules\ignite-cli\build\commands\remove-demo.js:4:12) {
  code: 'ENOENT'
}

Node.js v20.9.0

   Unable to remove demo code.
    🛠️  Removing fancy demo code
 templates to change EOL: ignite\templates\component\NAME.tsx.ejs,ignite\templates\model\NAME.test.ts.ejs,ignite\templates\model\NAME.ts.ejs,ignite\templates\navigator\NAMENavigator.tsx.ejs,ignite\templates\screen\NAMEScreen.tsx.ejs
 Converting EOL for ignite\templates\component\NAME.tsx.ejs
 Converting EOL for ignite\templates\model\NAME.test.ts.ejs
 Converting EOL for ignite\templates\model\NAME.ts.ejs
 Converting EOL for ignite\templates\navigator\NAMENavigator.tsx.ejs
 Converting EOL for ignite\templates\screen\NAMEScreen.tsx.ejs
    -  Backing everything up in source control git init
    \  Backing everything up in source control git add -A
    -  Backing everything up in source control git commit -m "New Ignite 9.0.0 app
    🗄  Backing everything up in source control
 C:\CODING\LEARNING\MOBILE APPS

    ────────────────────────────────────────────────────

    Ignited PizzaApp3 in 105.16s  🚀

    For next time: here are the Ignite options you picked!
      npx ignite-cli new PizzaApp3 \
        --bundle=com.pizzaapp3 \
        --git \
        --install-deps \
        --packager=npm \
        --target-path=C:\CODING\LEARNING\MOBILE \
 APPS\PizzaApp3        --remove-demo \
        --workflow=expo \
        --no-timeout=false

    ────────────────────────────────────────────────────

    Need additional help?

    Join our Slack community at http://community.infinite.red.

    ────────────────────────────────────────────────────

    Now get cooking! 🍽
      cd C:\CODING\LEARNING\MOBILE APPS\PizzaApp3
      npm run android

```

**Comment by onurusluca** [comment]
I am thinking Windows path are different from MacOS so it's causing the problem.

Take a look at here: `Error: Path you want to find stuff in doesn't exist C:\CODING\LEARNING\MOBILE`
the whole path is supposed to be: `C:\CODING\LEARNING\MOBILE APPS\PizzaApp3`
Maybe because the path has space in it?

**Comment by frankcalise** [comment]
Yeah no space is definitely something to try and if that is the culprit we can fix from there. Thanks for the info!

**Comment by onurusluca** [comment]
@frankcalise Thanks for the PR. Btw, I tested the CLI on a route that has no spaces and it worked fine assuming the screen is how it is supposed to look? Only welcome screen right?

Before:
C:\CODING\LEARNING\MOBILE APPS\PizzaApp3

Now:
C:\CODING\PizzaApp3

```
 npx ignite-cli@latest new PizzaApp3 --debug
 ignite command: C:\Program Files\nodejs\node.exe C:\Users\dur2d\AppData\Local\npm-cache\_npx\bec2839915ba8fc3\node_modules\ignite-cli\bin\ignite new PizzaApp3 --debug

✅ What bundle identifier? · com.pizzaapp3
✅ Where do you want to start your project? · C:\CODING\PizzaApp3
✅ Choose a workflow: · Expo Go
 worflow: expo
 needs prebuild: false
✅ Do you want to initialize a git repository? (Y/n) · Yes
✅ Remove demo code? We recommend leaving it in if it's your first time using Ignite (y/N) · Yes
 availablePackagers: npm,pnpm
✅ Which package manager do you want to use? · npm
 ignitePath: C:\Users\dur2d\AppData\Local\npm-cache\_npx\bec2839915ba8fc3\node_modules\ignite-cli
 boilerplatePath: C:\Users\dur2d\AppData\Local\npm-cache\_npx\bec2839915ba8fc3\node_modules\ignite-cli\boilerplate
✅ Do you want to install dependencies? (Y/n) · Yes
 experimentalFlags:




                                               .;;,.    .clll.
                                              .clll,    ,llll.           ...
                                               .,;,.    ;lllc'.,.   .';cllllc,
     .',,.                           ...      .'',,. .:lllllllll. .;lllc:;clll,
    .llll,                    .,...;cllll:.   ,llll, .llllllc,,'  clll:'.,cllc.
    ,llll'       ......;::.  'llcclllllllll'  ,llll,   .llll.    ,lllllllll:'
    ,llll.    .;clllllclll.  'llllc,..,llll,  :llll.   'llll.    ,lllc,''..
    ;llll.   :llllc:cllllc.  ,llll.   .llll, .lllll.   ,lllc...  ,lll:...';:.
   .llllc.  ;lll;.   :lll,   ;lll;    'llll, .llllc.   ,llllcll' .:lllllllll,
   .llll,  'lll:    .clll,   :lll,    ,llll. 'llll,    'lllllcc'   ';::::;'.
   .llll,  ,lll:    .llll'  .llll,    ;llll. ,llll,     .....             .',..
   ,llll.  'llll:,,:cllll.  .lllc.    .''..  ... ....',;         ..',,:::;'..
   ,llll.   'clllllllllll.     .....        ..,::cllllc.   .',:clllc;,'.
   :llll.     ',;,'.;lllc...,;:clll;  ..',:cllllllllll:,;clllllc;,'.
   llll:        ...'cllllllllllllll::cllllllc;,',cllllllllc;'..
   llll,   ..,clllllllll::,,.,lllllllc:,'...    :lllllc,..
   c:;,.  .cllllc:;:llll.    ,ll:;,..          ;ll:,..
          :lll,.  .clll,     ..               .,..
          :lll:,,cllll,
          .cllllllllc'
           .'cllll:.



    █ Creating PizzaApp3 using Ignite 9.0.0
    █ Powered by  ∞ Infinite Red  (https://infinite.red)
    █ Package Manager: npm
    █ Bundle identifier: com.pizzaapp3
    █ Path: C:\CODING\PizzaApp3
    ────────────────────────────────────────────────────

    🖨  3D-printing a new React Native app
 C:\CODING\PizzaApp3\.gitignore
 C:\Users\dur2d\AppData\Local\npm-cache\_npx\bec2839915ba8fc3\node_modules\ignite-cli\boilerplate\.gitignore.template
 C:\CODING
 Changing some dependencies for Expo Go compatibility...
 {"@react-native-async-storage/async-storage":"1.18.2","expo-application":"~5.3.0","expo-font":"~11.4.0","expo-localization":"~14.3.0","@shopify/flash-list":"1.4.3"}
 expected cachePath: C:\Users\dur2d\AppData\Local\Temp\ignite\6c03f35dc83f1978e826364de25b70e4\npm
 cacheExists: false
    - Getting those last few details perfect Renaming ios/HelloWorld.xcodeproj/xcshareddata/xcschemes/HelloWorld.xcscheme to PizzaApp3.xcscheme
 Renaming ios/HelloWorldTests/HelloWorldTests.m to PizzaApp3Tests.m
 Renaming ios/HelloWorld/HelloWorld-Bridging-Header.h to PizzaApp3-Bridging-Header.h
 Renaming ios/HelloWorld/HelloWorld.entitlements to PizzaApp3.entitlements
 Renaming ios/HelloWorld.xcworkspace to PizzaApp3.xcworkspace
 Renaming ios/HelloWorld to PizzaApp3
 Renaming ios/HelloWorldTests to PizzaApp3Tests
 Renaming ios/HelloWorld.xcodeproj to PizzaApp3.xcodeproj
 Renaming bundle identifier to com.pizzaapp3
 Patching app.json - HelloWorld to PizzaApp3 and variants
 Patching package.json - HelloWorld to PizzaApp3 and variants
 Patching .maestro\FavoritePodcast.yaml - com.helloworld to com.pizzaapp3 and variants
 Patching .maestro\Login.yaml - com.helloworld to com.pizzaapp3 and variants
    🎨 Getting those last few details perfect
    - Installing npm dependencies (wow these are heavy)
> pizza-app-3@0.0.1 postinstall
> patch-package


    \ Installing npm dependencies (wow these are heavy) patch-package 6.4.7

 Applying patches...


added 1736 packages, and audited 1737 packages in 2m


167 packages are looking for funding
  run `npm fund` for details


6 moderate severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.

    🧶 Installing npm dependencies (wow these are heavy)
       Configuring app.json
    -  Removing fancy demo code Ignite bin path: node C:\Users\dur2d\AppData\Local\npm-cache\_npx\bec2839915ba8fc3\node_modules\ignite-cli\bin\ignite
    🛠️  Removing fancy demo code
 templates to change EOL: ignite\templates\component\NAME.tsx.ejs,ignite\templates\model\NAME.test.ts.ejs,ignite\templates\model\NAME.ts.ejs,ignite\templates\navigator\NAMENavigator.tsx.ejs,ignite\templates\screen\NAMEScreen.tsx.ejs
 Converting EOL for ignite\templates\component\NAME.tsx.ejs
 Converting EOL for ignite\templates\model\NAME.test.ts.ejs
 Converting EOL for ignite\templates\model\NAME.ts.ejs
 Converting EOL for ignite\templates\navigator\NAMENavigator.tsx.ejs
 Converting EOL for ignite\templates\screen\NAMEScreen.tsx.ejs
    -  Backing everything up in source control git init
    \  Backing everything up in source control git add -A
    /  Backing everything up in source control git commit -m "New Ignite 9.0.0 app
    🗄  Backing everything up in source control
 C:\CODING

    ────────────────────────────────────────────────────

    Ignited PizzaApp3 in 108.63s  🚀

    For next time: here are the Ignite options you picked!
      npx ignite-cli new PizzaApp3 \
        --bundle=com.pizzaapp3 \
        --git \
        --install-deps \
        --packager=npm \
        --target-path=C:\CODING\PizzaApp3 \
        --remove-demo \
        --workflow=expo \
        --no-timeout=false

    ────────────────────────────────────────────────────

    Need additional help?

    Join our Slack community at http://community.infinite.red.

    ────────────────────────────────────────────────────

    Now get cooking! 🍽
      cd C:\CODING\PizzaApp3
      npm run android
```

![image](https://github.com/infinitered/ignite/assets/51825926/8dfdca8e-f77e-4d8e-8973-d261a07f1fe4)

**Comment by frankcalise** [comment]
@onurusluca yup that's correct, the only screen we leave there if you remove the demo just so you have an initial place to land.

**Comment by frankcalise** [comment]
Thanks for reporting the issue, a good fix to have! You can leave this open, it'll close automatically when we get to review and merge the PR

**Comment by onurusluca** [comment]
Thank you! Got it.
