### ISSUE TITLE
List view generation Error

### ISSUE THREAD

**Issue by waqas19921** [infinitered/ignite#256]
i executed following list view generation command 
`ignite generate listview BlogPosts`
and following error occurred

```
Generate a new listview named BlogPosts
? What kind of listview would you like to generate? (Use arrow keys)
> Row List
  Grid List

events.js:154
      throw er; // Unhandled 'error' event
      ^

TypeError: this.env.adapter.prompt(...).then is not a function
    at ListviewGenerator.Base.prompt (C:\Users\DELL 5559\AppData\Roaming\npm\node_modules\generator-react-native-ignite\node_modules\yeoman-generator\lib\base.js:232:45)
    at ListviewGenerator.prompting (C:\Users\DELL 5559\AppData\Roaming\npm\node_modules\generator-react-native-ignite\listview\index.js:58:19)
    at Object.<anonymous> (C:\Users\DELL 5559\AppData\Roaming\npm\node_modules\generator-react-native-ignite\node_modules\yeoman-generator\lib\base.js:431:23)
    at C:\Users\DELL 5559\AppData\Roaming\npm\node_modules\generator-react-native-ignite\node_modules\run-async\index.js:26:25
    at C:\Users\DELL 5559\AppData\Roaming\npm\node_modules\generator-react-native-ignite\node_modules\run-async\index.js:25:19
    at C:\Users\DELL 5559\AppData\Roaming\npm\node_modules\generator-react-native-ignite\node_modules\yeoman-generator\lib\base.js:432:9
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)
```

**Comment by GantMan** [comment]
I just generated this and it worked for me.   Looks like you might have a bad or old install of yeowman.

what version of `yo` do you have?
`yo --version`

If you're ambitious, this will work:

```
npm -g uninstall yo
npm -g install yo
```

**Comment by GantMan** [comment]
closing due to inactivity.

**Comment by waqas19921** [comment]
thanks after updating `yo` `Listview `generation is successful
