### ISSUE TITLE
v9 (yarn): unable to run `yarn android` on windows

### ISSUE THREAD

**Issue by chankruze** [infinitered/ignite#2562]
### Describe the bug

```
PS E:\react-native> npx ignite-cli@latest new FlixPulse
Need to install the following packages:
ignite-cli@9.0.0
Ok to proceed? (y)

✅ What bundle identifier? · app.flixpulse
✅ Where do you want to start your project? · E:\react-native\FlixPulse
✅ Choose a workflow: · Expo Prebuild
✅ Do you want to initialize a git repository? (Y/n) · Yes
✅ Remove demo code? We recommend leaving it in if it's your first time using Ignite (y/N) · No
✅ Which package manager do you want to use? · yarn
✅ Do you want to install dependencies? (Y/n) · Yes
✅ ❗EXPERIMENTAL❗Would you like to enable the New Architecture? (y/N) · No




                                               .;;,.    .clll.
                                              .clll,    ,llll.           ...
                                               .,;,.    ;lllc'.,.   .';cllllc,
     .',,.                           ...      .'',,. .:lllllllll. .;lllc:;clll,
    .llll,                    .,...;cllll:.   ,llll, .llllllc,,'  clll:'.,cllc.
    ,llll'       ......;::.  'llcclllllllll'  ,llll,   .llll.    ,lllllllll:'
    ,llll.    .;clllllclll.  'llllc,..,llll,  :llll.   'llll.    ,lllc,''..
    ;llll.   :llllc:cllllc.  ,llll.   .llll, .lllll.   ,lllc...  ,lll:...';:.
   .llllc.  ;lll;.   :lll,   ;lll;    'llll, .llllc.   ,llllcll' .:lllllllll,
   .llll,  'lll:    .clll,   :lll,    ,llll. 'llll,    'lllllcc'   ';::::;'.
   .llll,  ,lll:    .llll'  .llll,    ;llll. ,llll,     .....             .',..
   ,llll.  'llll:,,:cllll.  .lllc.    .''..  ... ....',;         ..',,:::;'..
   ,llll.   'clllllllllll.     .....        ..,::cllllc.   .',:clllc;,'.
   :llll.     ',;,'.;lllc...,;:clll;  ..',:cllllllllll:,;clllllc;,'.
   llll:        ...'cllllllllllllll::cllllllc;,',cllllllllc;'..
   llll,   ..,clllllllll::,,.,lllllllc:,'...    :lllllc,..
   c:;,.  .cllllc:;:llll.    ,ll:;,..          ;ll:,..
          :lll,.  .clll,     ..               .,..
          :lll:,,cllll,
          .cllllllllc'
           .'cllll:.



    █ Creating FlixPulse using Ignite 9.0.0
    █ Powered by  ∞ Infinite Red  (https://infinite.red)
    █ Package Manager: yarn
    █ Bundle identifier: app.flixpulse
    █ Path: E:\react-native\FlixPulse
    ────────────────────────────────────────────────────

    🖨  3D-printing a new React Native app
    🎨 Getting those last few details perfect
    🧶 Installing yarn dependencies (wow these are heavy)
       Configuring app.json
    🛠️  Generating native template via Expo Prebuild
    🛠️  Removing fancy demo markup
    🗄  Backing everything up in source control
    For next time: here are the Ignite options you picked!
      npx ignite-cli new FlixPulse \
        --bundle=app.flixpulse \
        --git \
        --install-deps \
        --packager=yarn \
        --target-path=E:\react-native\FlixPulse \
        --remove-demo=false \
        --workflow=prebuild \
        --no-timeout=false

    ────────────────────────────────────────────────────

    Need additional help?

    Join our Slack community at http://community.infinite.red.

    ────────────────────────────────────────────────────

    Now get cooking! 🍽
      cd E:\react-native\FlixPulse
      yarn android


PS E:\react-native>
PS E:\react-native>
PS E:\react-native>
PS E:\react-native> cd .\FlixPulse\
PS E:\react-native\FlixPulse> yarn android
yarn run v1.22.21
$ npx expo run:android
› Building app...
Configuration on demand is an incubating feature.

> Configure project :expo

Using expo modules
  - expo-application (5.4.0)
  - expo-constants (14.4.2)
  - expo-file-system (15.4.4)
  - expo-font (11.6.0)
  - expo-keep-awake (12.3.0)
  - expo-localization (14.5.0)
  - expo-modules-core (1.5.11)
  - expo-modules-core$android-annotation (1.5.11)
  - expo-modules-core$android-annotation-processor (1.5.11)
  - expo-splash-screen (0.20.5)


> Configure project :react-native-reanimated
No AAR for react-native-reanimated found. Attempting to build from source.
Android gradle plugin: 7.4.2
Gradle: 8.0.1
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

The Kotlin Gradle plugin was loaded multiple times in different subprojects, which is not supported and may break the build.
This might happen in subprojects that apply the Kotlin plugins with the Gradle 'plugins { ... }' DSL if they specify explicit versions, even if the versions are equal.
Please add the Kotlin plugin to the common parent project or the root project, then remove the versions in the subprojects.
If the parent project does not need the plugin, add 'apply false' to the plugin line.
See: https://docs.gradle.org/current/userguide/plugins.html#sec:subprojects_plugins_dsl
The Kotlin plugin was loaded in the following projects: ':shopify_flash-list', ':expo-modules-core', ':react-native-gesture-handler', ':react-native-safe-area-context', ...

> Task :app:processDebugMainManifest
E:\react-native\FlixPulse\android\app\src\debug\AndroidManifest.xml:6:5-162 Warning:
        application@android:usesCleartextTraffic was tagged at AndroidManifest.xml:6 to replace other declarations but no other declaration present
E:\react-native\FlixPulse\android\app\src\debug\AndroidManifest.xml:21:9-30:20 Warning:
        provider#expo.modules.filesystem.FileSystemFileProvider@android:authorities was tagged at AndroidManifest.xml:21 to replace other declarations but no other declaration present

> Task :expo-modules-core:compileDebugKotlin FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':expo-modules-core:compileDebugKotlin'.
> Could not resolve all files for configuration ':expo-modules-core:debugCompileClasspath'.
   > Failed to transform expo-modules-core$android-annotation.jar (project :expo-modules-core$android-annotation) to match attributes {artifactType=android-classes-jar, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.jvm.environment=standard-jvm, org.gradle.jvm.version=11, org.gradle.libraryelements=jar, org.gradle.usage=java-api, org.jetbrains.kotlin.platform.type=jvm}.
      > Execution failed for JetifyTransform: E:\react-native\FlixPulse\node_modules\expo-modules-core\android-annotation\build\libs\expo-modules-core$android-annotation-1.1.1.jar.
         > Failed to transform 'E:\react-native\FlixPulse\node_modules\expo-modules-core\android-annotation\build\libs\expo-modules-core$android-annotation-1.1.1.jar' using Jetifier. Reason: IllegalArgumentException, message: Unsupported class file major version 63. (Run with --stacktrace for more details.)
           Suggestions:
            - Check out existing issues at https://issuetracker.google.com/issues?q=componentid:460323&s=modified_time:desc, it's possible that this issue has already been filed there.
            - If this issue has not been filed, please report it at https://issuetracker.google.com/issues/new?component=460323 (run with --stacktrace and provide a stack trace if possible).

> Run with --stacktrace option to get the stack trace.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 2s
151 actionable tasks: 34 executed, 117 from cache
Error: E:\react-native\FlixPulse\android\gradlew.bat exited with non-zero code: 1
Error: E:\react-native\FlixPulse\android\gradlew.bat exited with non-zero code: 1
    at ChildProcess.completionListener (E:\react-native\FlixPulse\node_modules\@expo\cli\node_modules\@expo\spawn-async\build\spawnAsync.js:52:23)
    at Object.onceWrapper (node:events:629:26)
    at ChildProcess.emit (node:events:514:28)
    at cp.emit (E:\react-native\FlixPulse\node_modules\@expo\cli\node_modules\cross-spawn\lib\enoent.js:34:29)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)
    ...
    at Object.spawnAsync [as default] (E:\react-native\FlixPulse\node_modules\@expo\cli\node_modules\@expo\spawn-async\build\spawnAsync.js:17:21)
    at spawnGradleAsync (E:\react-native\FlixPulse\node_modules\@expo\cli\build\src\start\platforms\android\gradle.js:72:46)
    at Object.assembleAsync (E:\react-native\FlixPulse\node_modules\@expo\cli\build\src\start\platforms\android\gradle.js:52:18)
    at runAndroidAsync (E:\react-native\FlixPulse\node_modules\@expo\cli\build\src\run\android\runAndroidAsync.js:36:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Ignite version

9.0.0

### Additional info

```
PS E:\react-native\FlixPulse> npx ignite-cli doctor
System
  platform           win32
  arch               x64
  cpu                12 cores     Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  directory          FlixPulse    E:\react-native\FlixPulse

JavaScript (and globally-installed packages)
  node               20.9.0       D:\nodejs\node.EXE
  npm                10.1.0       D:\nodejs\npm.CMD
    yarn             1.22.21
  yarn               1.22.21      C:\Users\chankruze\AppData\Roaming\npm\yarn.CMD
  pnpm               -            not installed
  bun                -            not installed
  expo               49.0.18      managed

Ignite
  ignite-cli         9.0.0        C:\Users\chankruze\AppData\Local\npm-cache\_npx\e31027f3785124a8\node_modules\.bin\ignite.CMD
  ignite src         build        C:\Users\chankruze\AppData\Local\npm-cache\_npx\e31027f3785124a8\node_modules\ignite-cli\build

Android
  java               19.0.2       D:\jdk-19.0.2\bin\java.EXE
  android home       -            D:\Android\Sdk

Tools
  git                git version 2.36.1.windows.1   D:\Git\cmd\git.EXE
  ```

**Comment by chankruze** [comment]
Now I'm trying to go with `Expo Go` and `npm`. Let's see...

**Comment by frankcalise** [comment]
You have the incorrect JDK set up it looks like, try following the environment setup docs here: https://reactnative.dev/docs/environment-setup?os=windows&platform=android

**Comment by chankruze** [comment]
Yes, `jdk-11` resolves this issue.
