### ISSUE TITLE
Screen and Splash Generator not working

### ISSUE THREAD

**Issue by narayanpromax** [infinitered/ignite#2599]
### Describe the bug

`npx ignite generate splash-screen "#1b1648"`
and
`npx ignite generate screen Languages`

gives below error

`(node:7051) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
clean-webpack-plugin: /Users/narayan/Dev/customer-cross-platform/_ignite is outside of the project root. Skipping...
node:events:493
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, scandir '/Users/narayan/Dev/customer-cross-platform/docs'
    at Object.readdirSync (node:fs:1516:26)
    at exports.readdir (/Users/narayan/.npm/_npx/0e11d984049d509d/node_modules/@mrmlnc/readdir-enhanced/lib/sync/fs.js:18:20)
    at Object.safeCall [as safe] (/Users/narayan/.npm/_npx/0e11d984049d509d/node_modules/@mrmlnc/readdir-enhanced/lib/call.js:24:8)
    at DirectoryReader.readNextDirectory (/Users/narayan/.npm/_npx/0e11d984049d509d/node_modules/@mrmlnc/readdir-enhanced/lib/directory-reader.js:78:10)
    at DirectoryReader.stream._read (/Users/narayan/.npm/_npx/0e11d984049d509d/node_modules/@mrmlnc/readdir-enhanced/lib/directory-reader.js:57:18)
    at Readable.read (node:internal/streams/readable:715:12)
    at readdirSync (/Users/narayan/.npm/_npx/0e11d984049d509d/node_modules/@mrmlnc/readdir-enhanced/lib/sync/index.js:27:21)
    at Function.readdirSyncStat (/Users/narayan/.npm/_npx/0e11d984049d509d/node_modules/@mrmlnc/readdir-enhanced/lib/index.js:34:10)
    at ReaderSync.dynamicApi (/Users/narayan/.npm/_npx/0e11d984049d509d/node_modules/fast-glob/out/providers/reader-sync.js:64:24)
    at ReaderSync.api (/Users/narayan/.npm/_npx/0e11d984049d509d/node_modules/fast-glob/out/providers/reader-sync.js:56:25)
Emitted 'error' event on Readable instance at:
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'scandir',
  path: '/Users/narayan/Dev/customer-cross-platform/docs'
}`

### Ignite version

9.3.0

### Additional info

System
  platform           darwin                                                               
  arch               arm64                                                                
  cpu                8 cores                   Apple M2                                   
  directory          customer-cross-platform   /Users/narayan/Dev/customer-cross-platform 

JavaScript (and globally-installed packages)
  node               21.1.0       /usr/local/bin/node 
  npm                10.2.1       /usr/local/bin/npm  
    corepack         0.22.0                           
    json-server      0.17.4                           
    npm              10.2.1                           
    yarn             1.22.19                          
  yarn               1.22.19      /usr/local/bin/yarn 
  pnpm               -            not installed       
  bun                -            not installed       
  expo               49.0.21      managed             

Ignite
  ignite-cli         9.3.0        /Users/narayan/.npm/_npx/e31027f3785124a8/node_modules/.bin/ignite      
  ignite src         build        /Users/narayan/.npm/_npx/e31027f3785124a8/node_modules/ignite-cli/build 

Android
  java               -            not installed 
  android home       -            undefined     
/Users/narayan/.npm/_npx/e31027f3785124a8/node_modules/gluegun/build/index.js:15
    throw up;
    ^

Error: Command failed: xcodebuild -version
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

    at ChildProcess.exithandler (node:child_process:422:12)
    at ChildProcess.emit (node:events:515:28)
    at maybeClose (node:internal/child_process:1105:16)
    at Socket.<anonymous> (node:internal/child_process:457:11)
    at Socket.emit (node:events:515:28)
    at Pipe.<anonymous> (node:net:337:12) {
  code: 1,
  killed: false,
  signal: null,
  cmd: 'xcodebuild -version',
  stdout: '',
  stderr: "xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance\n"
}

Node.js v21.1.0

**Comment by ElonVolo** [comment]
I've been having the same problem with the generators

**Comment by Dax911** [comment]
I found this error on my cousins machine yesterday it was resolved by explicitly using `ignite-cli` command instead of just `ignite`

**Comment by frankcalise** [comment]
Dax is correct here, the project although titled "Ignite" is not ignite on npm but `ignite-cli`
