### ISSUE TITLE
Fresh install errors with `sh: patch-package: command not found`

### ISSUE THREAD

**Issue by mrcelo** [infinitered/ignite#2681]
### Describe the bug

Starting a new project with latest ignite-cli@9.6.3 is resulting in all sorts of errors, using Node version 20.11.1

npx ignite-cli@latest new PizzaApp --yes

```



                                               .;;,.    .clll.
                                              .clll,    ,llll.           ...
                                               .,;,.    ;lllc'.,.   .';cllllc,
     .',,.                           ...      .'',,. .:lllllllll. .;lllc:;clll,
    .llll,                    .,...;cllll:.   ,llll, .llllllc,,'  clll:'.,cllc.
    ,llll'       ......;::.  'llcclllllllll'  ,llll,   .llll.    ,lllllllll:'
    ,llll.    .;clllllclll.  'llllc,..,llll,  :llll.   'llll.    ,lllc,''..
    ;llll.   :llllc:cllllc.  ,llll.   .llll, .lllll.   ,lllc...  ,lll:...';:.
   .llllc.  ;lll;.   :lll,   ;lll;    'llll, .llllc.   ,llllcll' .:lllllllll,
   .llll,  'lll:    .clll,   :lll,    ,llll. 'llll,    'lllllcc'   ';::::;'.
   .llll,  ,lll:    .llll'  .llll,    ;llll. ,llll,     .....             .',..
   ,llll.  'llll:,,:cllll.  .lllc.    .''..  ... ....',;         ..',,:::;'..
   ,llll.   'clllllllllll.     .....        ..,::cllllc.   .',:clllc;,'.
   :llll.     ',;,'.;lllc...,;:clll;  ..',:cllllllllll:,;clllllc;,'.
   llll:        ...'cllllllllllllll::cllllllc;,',cllllllllc;'..
   llll,   ..,clllllllll::,,.,lllllllc:,'...    :lllllc,..
   c:;,.  .cllllc:;:llll.    ,ll:;,..          ;ll:,..
          :lll,.  .clll,     ..               .,..
          :lll:,,cllll,
          .cllllllllc'
           .'cllll:.



    █ Creating PizzaApp using Ignite 9.6.3
    █ Powered by  ∞ Infinite Red  (https://infinite.red)
    █ Package Manager: npm
    █ Bundle identifier: com.pizzaapp
    █ Path: /Users/user/Developer/samplereactnative/PizzaApp
    ────────────────────────────────────────────────────

    🖨  3D-printing a new React Native app
    🎨 Getting those last few details perfect
    ❌ Installing npm dependencies (wow these are heavy)

The following error occurred:

    npm WARN deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
npm WARN deprecated @babel/plugin-proposal-optional-catch-binding@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-optional-catch-binding instead.
npm WARN deprecated @babel/plugin-proposal-numeric-separator@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-numeric-separator instead.
npm WARN deprecated @babel/plugin-proposal-class-properties@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-class-properties instead.
npm WARN deprecated @babel/plugin-proposal-nullish-coalescing-operator@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-nullish-coalescing-operator instead.
npm WARN deprecated @babel/plugin-proposal-logical-assignment-operators@7.20.7: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-logical-assignment-operators instead.
npm WARN deprecated @babel/plugin-proposal-async-generator-functions@7.20.7: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-async-generator-functions instead.
npm WARN deprecated @babel/plugin-proposal-optional-chaining@7.21.0: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-optional-chaining instead.
npm WARN deprecated @babel/plugin-proposal-object-rest-spread@7.20.7: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-object-rest-spread instead.
sh: patch-package: command not found
npm ERR! code 127
npm ERR! path /Users/user/Developer/samplereactnative/PizzaApp
npm ERR! command failed
npm ERR! command sh -c patch-package

npm ERR! A complete log of this run can be found in: /Users/user/.npm/_logs/2024-05-07T01_29_04_295Z-debug-0.log


    Consider opening an issue with the following information at:
    https://github.com/infinitered/ignite/issues/new?template=bug_report.yml&labels=bug

    ⠸  Gathering system and project details   Unable to gather system and project details.

```

Running `npm run android` in the new project returns this error:

```
npm run android

> pizza-app@0.0.1 android
> npx expo start --android

Starting project at /Users/user/Developer/samplereactnative/PizzaApp
Error: Error reading Expo config at /Users/user/Developer/samplereactnative/PizzaApp/app.config.ts:

Cannot find module 'ts-node/register'
Require stack:
- /Users/user/Developer/samplereactnative/PizzaApp/app.config.ts
- /Users/user/Developer/samplereactnative/PizzaApp/node_modules/@expo/config/build/evalConfig.js
- /Users/user/Developer/samplereactnative/PizzaApp/node_modules/@expo/config/build/getConfig.js
- /Users/user/Developer/samplereactnative/PizzaApp/node_modules/@expo/config/build/Config.js
- /Users/user/Developer/samplereactnative/PizzaApp/node_modules/@expo/config/build/index.js
- /Users/user/Developer/samplereactnative/PizzaApp/node_modules/@expo/cli/build/src/utils/analytics/getDevClientProperties.js
- /Users/user/Developer/samplereactnative/PizzaApp/node_modules/@expo/cli/build/src/start/resolveOptions.js
- /Users/user/Developer/samplereactnative/PizzaApp/node_modules/@expo/cli/build/src/start/index.js
- /Users/user/Developer/samplereactnative/PizzaApp/node_modules/@expo/cli/build/bin/cli
- /Users/user/Developer/samplereactnative/PizzaApp/node_modules/expo/bin/cli
Error: Error reading Expo config at /Users/user/Developer/samplereactnative/PizzaApp/app.config.ts:

Cannot find module 'ts-node/register'
Require stack:
- /Users/user/Developer/samplereactnative/PizzaApp/app.config.ts
- /Users/user/Developer/samplereactnative/PizzaApp/node_modules/@expo/config/build/evalConfig.js
- /Users/user/Developer/samplereactnative/PizzaApp/node_modules/@expo/config/build/getConfig.js
- /Users/user/Developer/samplereactnative/PizzaApp/node_modules/@expo/config/build/Config.js
- /Users/user/Developer/samplereactnative/PizzaApp/node_modules/@expo/config/build/index.js
- /Users/user/Developer/samplereactnative/PizzaApp/node_modules/@expo/cli/build/src/utils/analytics/getDevClientProperties.js
- /Users/user/Developer/samplereactnative/PizzaApp/node_modules/@expo/cli/build/src/start/resolveOptions.js
- /Users/user/Developer/samplereactnative/PizzaApp/node_modules/@expo/cli/build/src/start/index.js
- /Users/user/Developer/samplereactnative/PizzaApp/node_modules/@expo/cli/build/bin/cli
- /Users/user/Developer/samplereactnative/PizzaApp/node_modules/expo/bin/cli
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/Users/user/Developer/samplereactnative/PizzaApp/app.config.ts:7:1)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at requireFromString (/Users/user/Developer/samplereactnative/PizzaApp/node_modules/require-from-string/index.js:28:4)
    at evalConfig (/Users/user/Developer/samplereactnative/PizzaApp/node_modules/@expo/config/build/evalConfig.js:68:47)
    at readConfigFile (/Users/user/Developer/samplereactnative/PizzaApp/node_modules/@expo/config/build/getConfig.js:45:41)
    at getDynamicConfig (/Users/user/Developer/samplereactnative/PizzaApp/node_modules/@expo/config/build/getConfig.js:54:18)
    ``` 

### Ignite version

9.6.3

### Additional info

System
  platform           darwin
  arch               arm64
  cpu                8 cores             Apple M2
  directory          samplereactnative   /Users//Developer//samplereactnative

JavaScript (and globally-installed packages)
  node               20.11.1                                   /Users//.nvm/versions/node/v20.11.1/bin/node
  npm                10.2.4                                    /Users//.nvm/versions/node/v20.11.1/bin/npm
    corepack         0.23.0
    npm              10.2.4
  yarn               -                                         not installed
  pnpm               9.1.0                                     /opt/homebrew/bin/pnpm
                     <no pnpm global package info available>
  bun                -                                         not installed
  expo               -                                         not installed

Ignite
  ignite-cli         9.6.3        /Users//.npm/_npx/e31027f3785124a8/node_modules/.bin/ignite
  ignite src         build        /Users//.npm/_npx/e31027f3785124a8/node_modules/ignite-cli/build

Android
  java               17.0.11      /usr/bin/java
  android home       -            /Users//Library/Android/sdk
/Users/user/.npm/_npx/e31027f3785124a8/node_modules/gluegun/build/index.js:15
    throw up;
    ^

Error: Command failed: xcodebuild -version
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

    at ChildProcess.exithandler (node:child_process:422:12)
    at ChildProcess.emit (node:events:518:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5) {
  code: 1,
  killed: false,
  signal: null,
  cmd: 'xcodebuild -version',
  stdout: '',
  stderr: "xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance\n"
}

Node.js v20.11.1

(Since I'm not using iOS/Xcode for this RN project, I assume the xcodebuild error can be ignored)

**Comment by bihongbin3027** [comment]
@mrcelo Hello, I have also encountered the same problem.

**Comment by bihongbin3027** [comment]
![image](https://github.com/user-attachments/assets/697d2149-dcb9-480c-b414-80e2a4609ab9)
