### ISSUE TITLE
TurboModuleRegistry Error: DevMenu Could Not Be Found in Native Binary

### ISSUE THREAD

**Issue by imtalwindersingh** [infinitered/ignite#2798]
I encountered an error after creating a fresh project using `ignite-cli` and running it on an iOS simulator. The app failed to start due to a missing TurboModule called `DevMenu`. Below is the exact error message:

```
Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'DevMenu' could not be found. Verify that a module by this name is registered in the native binary.Bridgeless mode: false. TurboModule interop: false. Modules loaded: {"NativeModules":["PlatformConstants","LogBox","Timing","AppState","SourceCode","BlobModule","WebSocketModule","SettingsManager","DevSettings","RedBox","Networking","Appearance","DevLoadingView","UIManager","DeviceInfo","ImageLoader","LinkingManager","RNGestureHandlerModule","I18nManager","AsyncLocalStorage"],"TurboModules":[],"NotFound":["NativePerformanceCxx","NativePerformanceObserverCxx","BugReporting","HeadlessJsTaskSupport","SoundManager","IntentAndroid","PlatformLocalStorage","RNC_AsyncSQLiteDBStorage","RNCAsyncStorage","AsyncSQLiteDBStorage","DevMenu"]}, js engine: hermes 
```

## **Steps to Reproduce:**

1. Clone a fresh project using Ignite CLI:
   ```bash
   npx ignite-cli@latest new Pizza --yes
   ```
2. Navigate into the project directory:
   ```bash
   cd Pizza
   ```
3. Install dependencies and run the project on iOS:
   ```bash
   yarn ios
   ```
4. Observe the error in the console.

## **Expected Behavior:**
The app should load without any errors

## **Actual Behavior:**
The app throws an error related to `TurboModuleRegistry` and fails to load. It seems the `DevMenu` is not registered correctly.

## **Environment:**
- **Boilerplate Repo Version:** Fresh clone using `ignite-cli`
- **Node Version:** `v20.17.0`
- **Package Manager:** Yarn
- **iOS Device Used:** iPhone SE Simulator
- **Development Mode:** Expo Go / Development Build
- **React Native Version:** `0.74.2`
- **Expo SDK Version:** `51.0.8`

## **Package.json Details:**
```json
{
  "expo": "~51.0.8",
  "react-native": "0.74.2",
  "mobx": "6.10.2",
  "expo-application": "~5.9.1",
  "expo-font": "~12.0.5",
  "expo-linking": "~6.3.1",
  "expo-localization": "~15.0.3",
  "expo-splash-screen": "~0.27.4",
  "react-navigation/native": "^6.0.2"
}
```

### Ignite version

9.10.1

### Additional info

Got this error when I ran `npx ignite-cli doctor `
```
System
  platform           darwin                                                    
  arch               arm64                                                     
  cpu                8 cores      Apple M2                                     
  directory          Project Directory                                         

/node_modules/gluegun/build/index.js:15
    throw up;
    ^

Error: Command failed: pnpm --version
/nvm/versions/node/v18.20.4/lib/node_modules/corepack/dist/lib/corepack.cjs:23509
              throw new UsageError(`This project is configured to use ${result.spec.name} because ${result.target} has a "packageManager" field`);
                    ^

UsageError: This project is configured to use yarn because project-directory/package.json has a "packageManager" field
    at Engine.findProjectSpec (/nvm/versions/node/v18.20.4/lib/node_modules/corepack/dist/lib/corepack.cjs:23509:21)
    at async Engine.executePackageManagerRequest (/nvm/versions/node/v18.20.4/lib/node_modules/corepack/dist/lib/corepack.cjs:23539:24)
    at async Object.runMain (/nvm/versions/node/v18.20.4/lib/node_modules/corepack/dist/lib/corepack.cjs:24232:5) {
  clipanion: { type: 'usage' }
}

Node.js v20.17.0

    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at ChildProcess.exithandler (node:child_process:422:12)
    at ChildProcess.emit (node:events:519:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5) {
  code: 1,
  killed: false,
  signal: null,
  cmd: 'pnpm --version',
  stdout: '',
  stderr: '/nvm/versions/node/v18.20.4/lib/node_modules/corepack/dist/lib/corepack.cjs:23509\n' +
    '              throw new UsageError(`This project is configured to use ${result.spec.name} because ${result.target} has a "packageManager" field`);\n' +
    '                    ^\n' +
    '\n' +
    'UsageError: This project is configured to use yarn because project-directory/package.json has a "packageManager" field\n' +
    '    at Engine.findProjectSpec (/nvm/versions/node/v18.20.4/lib/node_modules/corepack/dist/lib/corepack.cjs:23509:21)\n' +
    '    at async Engine.executePackageManagerRequest (/nvm/versions/node/v18.20.4/lib/node_modules/corepack/dist/lib/corepack.cjs:23539:24)\n' +
    '    at async Object.runMain (/nvm/versions/node/v18.20.4/lib/node_modules/corepack/dist/lib/corepack.cjs:24232:5) {\n' +
    "  clipanion: { type: 'usage' }\n" +
    '}\n' +
    '\n' +
    'Node.js v20.17.0\n'
}

Node.js v20.17.0
```

Here are log from `npx expo-doctor`:

```npx expo-doctor
Warning: Root-level "expo" object found. Ignoring extra keys in Expo config: "name", "displayName", "ignite"
Learn more: https://expo.fyi/root-expo-object
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check if the project meets version requirements for submission to app stores
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check for issues with metro config
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK
✖ Check that packages match versions required by installed Expo SDK

Detailed check results:

Warning: Root-level "expo" object found. Ignoring extra keys in Expo config: "name", "displayName", "ignite"
Learn more: https://expo.fyi/root-expo-object
The following packages should be updated for best compatibility with the installed expo version:
  @react-native-async-storage/async-storage@1.21.0 - expected version: 1.23.1
  @shopify/flash-list@1.6.3 - expected version: 1.6.4
  react-native@0.74.2 - expected version: 0.74.5
  react-native-safe-area-context@4.10.1 - expected version: 4.10.5
Your project may not work correctly until you install the expected versions of the packages.
Found outdated dependencies
Advice: Use 'npx expo install --check' to review and upgrade your dependencies.

One or more checks failed, indicating possible issues with the project```

**Comment by hoangcuong22** [comment]
same issue

**Comment by thatportugueseguy** [comment]
same

**Comment by thatportugueseguy** [comment]
I had a look at the error and saw [this message](https://github.com/react-native-webview/react-native-webview/issues/3506#issuecomment-2257103286) on another issue regarding TurboModuleRegistry error and tried deleting the ios build and the pods folder and reinstall. 

I got this warning:

```
[!] Can't merge pod_target_xcconfig for pod targets: ["expo-dev-menu", "Main", "ReactNativeCompatibles", "SafeAreaView", "Vendored"]. Singular build setting DEFINES_MODULE has different values.

[!] Can't merge pod_target_xcconfig for pod targets: ["expo-dev-menu", "Main", "ReactNativeCompatibles", "SafeAreaView", "Vendored"]. Singular build setting DEFINES_MODULE has different values.
```

it seems there's some issue with the project setup with expo. I have tried to run a bare expo installation and didn't run into issues with the `DevMenu`. 


I'm not sure how to debug further, and running the app now completely breaks with a million lines of errors in red 😅 
```
The following build commands failed:
        CompileC /Users/ze/Library/Developer/Xcode/DerivedData/AuthRecipe-conoeyyppczoikguggrllxrcuhvk/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/react-native-mmkv.build/Objects-normal/arm64/NativeMmkvModule.o /Users/ze/Projects/private/AuthRecipe/node_modules/react-native-mmkv/cpp/NativeMmkvModule.cpp normal arm64 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'react-native-mmkv' from project 'Pods')
        Building workspace AuthRecipe with scheme AuthRecipe and configuration Debug
(2 failures)
Build logs written to /Users/ze/Projects/private/AuthRecipe/.expo/xcodebuild.log
error: script "ios" exited with code 1
```

**Comment by ehteshamwarraich** [comment]
They need to update the expo-go workflow for this.
Meanwhile, you can use the dev client.

`yarn expo prebuild -p ios`
`cd ios && pod install`
`yarn ios`

**Comment by frankcalise** [comment]
Previous discussion around the same issue in https://github.com/infinitered/ignite/issues/2678

Couple of things you can do here:
1. Remove the offending Reactotron custom command [here](https://github.com/infinitered/ignite/blob/master/boilerplate/app/devtools/ReactotronConfig.ts#L50-L58)
2. Utilize Expo CNG
3. Go with `npx ignite-cli@next` (which will use CNG) which should be released this week

But this will not be fixed here as it's related to Expo Go
