### ISSUE TITLE
Issue: Compatibility Problem with react-native-mmkv 3.x.x and Ignite Boilerplate

### ISSUE THREAD

**Issue by AnasGhareib** [infinitered/ignite#2860]
### Describe the bug

When starting a new app using the Ignite CLI with the following configuration:

```
npx ignite-cli new PizzaApp \
        --bundle=com.pizzaapp \
        --git \
        --install-deps \
        --packager=bun \
        --target-path=/home/aghthar/backyard/PizzaApp \
        --remove-demo=false \
        --experimental=expo-router,new-arch \
        --workflow=cng \
        --no-timeout=false \
        --state=mst
````
I encountered the following error when running the app:

```
Error: Failed to create a new MMKV instance: react-native-mmkv 3.x.x requires TurboModules, but the new architecture is not enabled!
* Downgrade to react-native-mmkv 2.x.x if you want to stay on the old architecture.
* Enable the new architecture in your app to use react-native-mmkv 3.x.x. (See https://github.com/reactwg/react-native-new-architecture/blob/main/docs/enable-apps.md), js engine: hermes [Component Stack]
 WARN  fontFamily "spaceGroteskBold" is not a system font and has not been loaded through expo-font. [Component Stack]
 WARN  fontFamily "spaceGroteskMedium" is not a system font and has not been loaded through expo-font. [Component Stack]
 WARN  fontFamily "spaceGroteskRegular" is not a system font and has not been loaded through expo-font. [Component Stack]
```

### Ignite version

10.0.5

### Additional info

```
❯ bunx ignite-cli doctor
/home/aghthar/.bun/install/global/node_modules/gluegun/build/index.js:15
    throw up;
    ^

Error: 
Something went wrong installing the "sharp" module

Cannot find module '../build/Release/sharp-linux-x64.node'
Require stack:
- /home/aghthar/.bun/install/global/node_modules/sharp/lib/sharp.js
- /home/aghthar/.bun/install/global/node_modules/sharp/lib/constructor.js
- /home/aghthar/.bun/install/global/node_modules/sharp/lib/index.js
- /home/aghthar/.bun/install/global/node_modules/ignite-cli/build/tools/generators.js
- /home/aghthar/.bun/install/global/node_modules/ignite-cli/build/commands/help.js
- /home/aghthar/.bun/install/global/node_modules/ignite-cli/build/cli.js
- /home/aghthar/.bun/install/global/node_modules/ignite-cli/bin/ignite

Possible solutions:
- Install with verbose logging and look for errors: "npm install --ignore-scripts=false --foreground-scripts --verbose sharp"
- Install for the current linux-x64 runtime: "npm install --platform=linux --arch=x64 sharp"
- Consult the installation documentation: https://sharp.pixelplumbing.com/install
    at Object.<anonymous> (/home/aghthar/.bun/install/global/node_modules/sharp/lib/sharp.js:37:9)
    at Module._compile (node:internal/modules/cjs/loader:1546:14)
    at Object..js (node:internal/modules/cjs/loader:1689:10)
    at Module.load (node:internal/modules/cjs/loader:1318:32)
    at Function._load (node:internal/modules/cjs/loader:1128:12)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
    at Module.require (node:internal/modules/cjs/loader:1340:12)
    at require (node:internal/modules/helpers:141:16)
    at Object.<anonymous> (/home/aghthar/.bun/install/global/node_modules/sharp/lib/constructor.js:11:1)

Node.js v22.11.0

```

**Comment by frankcalise** [comment]
Thanks for the report @AnasGhareib - it should support this correctly but it seems, bugged. It'll work in the next version. For now, just make sure you drop the version down to 2.x as a workaround.
