### ISSUE TITLE
Use `10.1.0`Init a ignite app, run build:ios:sim,get `Failed to create the native directories` error.

### ISSUE THREAD

**Issue by Hao-yiwen** [infinitered/ignite#2866]
### Describe the bug

```bash
[RUN_EXPO_DOCTOR] Running 15 checks on your project...
[RUN_EXPO_DOCTOR] ✔ Check package.json for common issues
[RUN_EXPO_DOCTOR] ✔ Check Expo config for common issues
[RUN_EXPO_DOCTOR] ✔ Check native tooling versions
[RUN_EXPO_DOCTOR] ✔ Check if the project meets version requirements for submission to app stores
[RUN_EXPO_DOCTOR] ✔ Check for common project setup issues
[RUN_EXPO_DOCTOR] ✔ Check dependencies for packages that should not be installed directly
[RUN_EXPO_DOCTOR] ✔ Check for app config fields that may not be synced in a non-CNG project
[RUN_EXPO_DOCTOR] ✔ Check for issues with Metro config
[RUN_EXPO_DOCTOR] ✔ Check npm/ yarn versions
[RUN_EXPO_DOCTOR] ✖ Validate packages against React Native Directory package metadata
[RUN_EXPO_DOCTOR] ✔ Check Expo config (app.json/ app.config.js) schema
[RUN_EXPO_DOCTOR] ✔ Check for legacy global CLI installed locally
[RUN_EXPO_DOCTOR] ✔ Check that native modules do not use incompatible support packages
[RUN_EXPO_DOCTOR] ✔ Check that native modules use compatible support package versions for installed Expo SDK
[RUN_EXPO_DOCTOR] ✔ Check that packages match versions required by installed Expo SDK
[RUN_EXPO_DOCTOR] Detailed check results:
[RUN_EXPO_DOCTOR] 
[RUN_EXPO_DOCTOR] Advice: 
[RUN_EXPO_DOCTOR] - Update React Native Directory to include metadata for unknown packages. Alternatively, set expo.doctor.reactNativeDirectoryCheck.listUnknownPackages in package.json to false to skip warnings about packages with no metadata, if the warning is not relevant.
[RUN_EXPO_DOCTOR] The following issues were found when validating your dependencies against React Native Directory:
[RUN_EXPO_DOCTOR] No metadata available: @expo-google-fonts/space-grotesk, @expo/metro-runtime, date-fns, i18next, intl-pluralrules, mobx, mobx-react-lite, mobx-state-tree
[RUN_EXPO_DOCTOR] One or more checks failed, indicating possible issues with the project.
[RUN_EXPO_DOCTOR] Command "expo doctor" failed.
Error: npx -y expo-doctor exited with non-zero code: 1
    at ChildProcess.completionListener (/Users/yw.hao/.npm/_npx/203b5a3d3de594cf/node_modules/@expo/spawn-async/src/spawnAsync.ts:67:13)
    at Object.onceWrapper (node:events:634:26)
    at ChildProcess.emit (node:events:519:28)
    at ChildProcess.emit (node:domain:488:12)
    at maybeClose (node:internal/child_process:1105:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:305:5)
    ...
    at spawnAsync (/Users/yw.hao/.npm/_npx/203b5a3d3de594cf/node_modules/@expo/spawn-async/src/spawnAsync.ts:28:21)
    at spawn (/Users/yw.hao/.npm/_npx/203b5a3d3de594cf/node_modules/@expo/turtle-spawn/src/index.ts:25:29)
    at runExpoDoctor (/Users/yw.hao/.npm/_npx/203b5a3d3de594cf/node_modules/@expo/build-tools/src/common/setup.ts:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/yw.hao/.npm/_npx/203b5a3d3de594cf/node_modules/@expo/build-tools/src/common/setup.ts:95:28
    at async BuildContext.runBuildPhase (/Users/yw.hao/.npm/_npx/203b5a3d3de594cf/node_modules/@expo/build-tools/src/context.ts:190:22)
    at async setupAsync (/Users/yw.hao/.npm/_npx/203b5a3d3de594cf/node_modules/@expo/build-tools/src/common/setup.ts:93:5)
    at async buildAsync (/Users/yw.hao/.npm/_npx/203b5a3d3de594cf/node_modules/@expo/build-tools/src/builders/ios.ts:49:3)
    at async runBuilderWithHooksAsync (/Users/yw.hao/.npm/_npx/203b5a3d3de594cf/node_modules/@expo/build-tools/src/builders/common.ts:15:7)
    at async Object.iosBuilder (/Users/yw.hao/.npm/_npx/203b5a3d3de594cf/node_modules/@expo/build-tools/src/builders/ios.ts:38:12)
[PREBUILD] $ /private/var/folders/nm/b9nz80jj217df20r749_k4l80000gr/T/eas-build-local-nodejs/64836afb-b60b-44fd-a7ab-507ace3d574e/build/node_modules/.bin/expo prebuild --no-install --platform ios
[PREBUILD] Warning: Root-level "expo" object found. Ignoring extra keys in Expo config: "name", "displayName", "ignite"
[PREBUILD] Learn more: https://expo.fyi/root-expo-object
[PREBUILD] - Creating native directory (./ios)
[PREBUILD] fetch failed
[PREBUILD] - Creating native directory (./ios)
[PREBUILD] ✖ Failed to create the native directory
[PREBUILD] You may want to delete the ./ios and/or ./android directories before trying again.
[PREBUILD] Running "yarn install" in /var/folders/nm/b9nz80jj217df20r749_k4l80000gr/T/eas-build-local-nodejs/64836afb-b60b-44fd-a7ab-507ace3d574e/build directory
[PREBUILD] [1/5] Validating package.json...
[PREBUILD] [2/5] Resolving packages...
[PREBUILD] success Already up-to-date.
[PREBUILD] $ patch-package
[PREBUILD] patch-package 8.0.0
[PREBUILD] Applying patches...
[PREBUILD] No patch files found
[INSTALL_PODS] 
Error: spawn pod ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:286:19)
    at onErrorNT (node:internal/child_process:484:16)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)

Build failed
Unknown error. See logs of the Install pods build phase for more information.
npx -y eas-cli-local-build-plugin@1.0.144 eyJqb2IiOnsidHlwZSI6Im1hbmFnZWQiLCJwbGF0Zm9ybSI6ImlvcyIsInByb2plY3RBcmNoaXZlIjp7InR5cGUiOiJQQVRIIiwicGF0aCI6Ii92YXIvZm9sZGVycy9ubS9iOW56ODBqajIxN2RmMjByNzQ5X2s0bDgwMDAwZ3IvVC9lYXMtY2xpLW5vZGVqcy82N2I3NGY0ZC1iMzMxLTQwM2YtYTg1Zi03NzVjY2FkNjdjMDkudGFyLmd6In0sInByb2plY3RSb290RGlyZWN0b3J5IjoiLiIsImJ1aWxkZXJFbnZpcm9ubWVudCI6e30sImNhY2hlIjp7ImRpc2FibGVkIjpmYWxzZSwicGF0aHMiOltdLCJjbGVhciI6ZmFsc2V9LCJzZWNyZXRzIjp7ImJ1aWxkQ3JlZGVudGlhbHMiOnt9fSwidXBkYXRlcyI6e30sInNpbXVsYXRvciI6dHJ1ZSwic2NoZW1lIjoiaWduaXRlYXBwIiwiYnVpbGRDb25maWd1cmF0aW9uIjoiRGVidWciLCJ1c2VybmFtZSI6Imhhb3lpd2VuIiwiZXhwZXJpbWVudGFsIjp7fSwibW9kZSI6ImJ1aWxkIiwidHJpZ2dlcmVkQnkiOiJFQVNfQ0xJIiwiYXBwSWQiOiJiMDgzZTc3ZS1jZDE0LTQyZDctOGRmYy0yNDY5YzU3NzA4OTMiLCJpbml0aWF0aW5nVXNlcklkIjoiODhmZmVhYzMtNjFlNi00OWZmLTgxZjMtMGE4YmQ1Y2U4MzY4In0sIm1ldGFkYXRhIjp7InRyYWNraW5nQ29udGV4dCI6eyJ0cmFja2luZ19pZCI6IjM0YWM4MjY3LTVjZTYtNDUwZC1hNDhlLWM4MTFlY2Q1MTVlNSIsInBsYXRmb3JtIjoiaW9zIiwic2RrX3ZlcnNpb24iOiI1Mi4wLjAiLCJhY2NvdW50X2lkIjoiMDI2ZmRiODYtNjUyZi00ZWVjLTk2NmEtZWJjYzI3MjMwMDJkIiwicHJvamVjdF9pZCI6ImIwODNlNzdlLWNkMTQtNDJkNy04ZGZjLTI0NjljNTc3MDg5MyIsInByb2plY3RfdHlwZSI6Im1hbmFnZWQiLCJkZXZfY2xpZW50IjpmYWxzZSwibm9fd2FpdCI6ZmFsc2UsInJ1bl9mcm9tX2NpIjpmYWxzZSwibG9jYWwiOnRydWV9LCJhcHBCdWlsZFZlcnNpb24iOiIxIiwiYXBwVmVyc2lvbiI6IjEuMC4wIiwiY2xpVmVyc2lvbiI6IjEzLjMuMCIsIndvcmtmbG93IjoibWFuYWdlZCIsImNyZWRlbnRpYWxzU291cmNlIjoicmVtb3RlIiwic2RrVmVyc2lvbiI6IjUyLjAuMCIsImZpbmdlcnByaW50SGFzaCI6ImUwMWMzZjEzNmM3ODk3ZGI2MTM4NGY5OWY0OGRiYjZiZDdkODQzNDEiLCJmaW5nZXJwcmludFNvdXJjZSI6eyJ0eXBlIjoiUEFUSCIsInBhdGgiOiIvdmFyL2ZvbGRlcnMvbm0vYjluejgwamoyMTdkZjIwcjc0OV9rNGw4MDAwMGdyL1QvZWFzLWNsaS1ub2RlanMvYWExYTVkOTEtNzE3OS00MjY4LWJhNTUtNDBkOTFmZDczY2YwLXJ1bnRpbWUtZmluZ2VycHJpbnQuanNvbiIsImlzRGVidWdGaW5nZXJwcmludCI6ZmFsc2V9LCJyZWFjdE5hdGl2ZVZlcnNpb24iOiIwLjc2LjUiLCJkaXN0cmlidXRpb24iOiJpbnRlcm5hbCIsImFwcE5hbWUiOiJpZ25pdGUtYXBwIiwiYXBwSWRlbnRpZmllciI6ImNvbS5pZ25pdGVhcHAiLCJidWlsZFByb2ZpbGUiOiJkZXZlbG9wbWVudCIsImdpdENvbW1pdEhhc2giOiI2YWYxNGVlNjhiNmM1NzViODE4YjE0ZmYzZGNiZmQxMTQ3MTY4NWRmIiwiZ2l0Q29tbWl0TWVzc2FnZSI6Ik5ldyBJZ25pdGUgMTAuMS4wIGFwcCIsImlzR2l0V29ya2luZ1RyZWVEaXJ0eSI6dHJ1ZSwidXNlcm5hbWUiOiJoYW95aXdlbiIsInJ1bldpdGhOb1dhaXRGbGFnIjpmYWxzZSwicnVuRnJvbUNJIjpmYWxzZSwiZGV2ZWxvcG1lbnRDbGllbnQiOnRydWUsInJlcXVpcmVkUGFja2FnZU1hbmFnZXIiOiJ5YXJuIiwic2ltdWxhdG9yIjp0cnVlfX0= exited with non-zero code: 1
    Error: build command failed.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Ignite version

10.1.0

### Additional info

```
> ignite doctor

System
  platform           darwin                                             
  arch               arm64                                              
  cpu                8 cores      Apple M2                              
  directory          ignite-app   /Users/yw.hao/Documents/rn/ignite-app 

JavaScript (and globally-installed packages)
  node                                     20.14.0                                   /Users/yw.hao/.nvm/versions/node/v20.14.0/bin/node 
  npm                                      10.6.0                                    /Users/yw.hao/.nvm/versions/node/v20.14.0/bin/npm  
    @ctrip/crn-build                       2.5.26                                                                                       
    @ctrip/crn-cli                         2.7.78                                                                                       
    @ctrip/crn-pack-v70                    0.0.20                                                                                       
    @ctrip/crn-pack-v72                    0.0.44                                                                                       
    @ctrip/miniTools                       1.0.294                                                                                      
    @ctrip/xtaro-cli                       2.0.10                                                                                       
    @expo/metro-config                     -                                                                                            
    @expo/ngrok                            4.1.3                                                                                        
    @react-native-community/cli            14.0.0                                                                                       
    @tarojs/cli                            4.0.5                                                                                        
    buck-worker-tool                       -                                                                                            
    corepack                               0.28.1                                                                                       
    detox-cli                              20.0.0                                                                                       
    eas-cli                                13.3.0                                                                                       
    metro-babel-register                   -                                                                                            
    metro-babel-transformer                -                                                                                            
    metro-cache-key                        -                                                                                            
    metro-cache                            -                                                                                            
    metro-config                           -                                                                                            
    metro-core                             -                                                                                            
    metro-file-map                         -                                                                                            
    metro-inspector-proxy                  -                                                                                            
    metro-memory-fs                        -                                                                                            
    metro-minify-terser                    -                                                                                            
    metro-minify-uglify                    -                                                                                            
    metro-react-native-babel-preset        -                                                                                            
    metro-react-native-babel-transformer   -                                                                                            
    metro-react-native-interop-tools       -                                                                                            
    metro-resolver                         -                                                                                            
    metro-runtime                          -                                                                                            
    metro-source-map                       -                                                                                            
    metro-symbolicate                      -                                                                                            
    metro-transform-plugins                -                                                                                            
    metro-transform-worker                 -                                                                                            
    metro                                  -                                                                                            
    npm                                    10.6.0                                                                                       
    ob1                                    -                                                                                            
    pnpm                                   9.6.0                                                                                        
    react-native                           0.74.5                                                                                       
    typescript                             5.5.4                                                                                        
    yalc                                   1.0.0-pre.53                                                                                 
    yarn                                   1.22.22                                                                                      
  yarn                                     1.22.22                                   /Users/yw.hao/.nvm/versions/node/v20.14.0/bin/yarn 
    create-expo-app                        3.0.0                                                                                        
  pnpm                                     9.6.0                                     /Users/yw.hao/.nvm/versions/node/v20.14.0/bin/pnpm 
                                           <no pnpm global package info available>                                                      
  bun                                      -                                         not installed                                      
  expo                                     52.0.18                                   managed                                            

Ignite
  ignite-cli         10.1.0       /Users/yw.hao/.npm/_npx/e31027f3785124a8/node_modules/.bin/ignite      
  ignite src         build        /Users/yw.hao/.npm/_npx/e31027f3785124a8/node_modules/ignite-cli/build 

Android
  java               17.0.9       /usr/bin/java 
  android home       -            undefined     

iOS
  xcode              16.0       
  cocoapods          1.14.3       /Users/yw.hao/.rbenv/shims/pod 

Tools
  git                git version 2.39.5 (Apple Git-154)   /usr/bin/git
```

**Comment by Hao-yiwen** [comment]
```
ignite-app git:(main) ✗ npx expo prebuild --clean 

> ignite-app@0.0.1 npx
> expo prebuild --clean

! Git branch has uncommited file changes
› It's recommended to commit all changes before proceeding in case you want to revert generated changes.

✔ Continue with uncommited changes? … yes

✔ Cleared android, ios code
Warning: Root-level "expo" object found. Ignoring extra keys in Expo config: "name", "displayName", "ignite"
Learn more: https://expo.fyi/root-expo-object
fetch failed
✖ Failed to create the native directories
You may want to delete the ./ios and/or ./android directories before trying again.
```

**Comment by frankcalise** [comment]
@Hao-yiwen can you re-run that command with EXPO_DEBUG=1 please

`EXPO_DEBUG=1 npx expo prebuild --clean`

**Comment by frankcalise** [comment]
Closing issue from no response, please re-open if you're still experiencing trouble.
