### ISSUE TITLE
Failure setting up new project

### ISSUE THREAD

**Issue by fbunn** [infinitered/ignite#377]
ignite new <MyProject> fails after new install.
Please help!

[Freds-MacBook-Pro:ReactNative fredbunn$ ignite doctor

```
Computer
  Platform: darwin

Ignite
  Version: 1.7.1
  Path: /usr/local/bin/ignite

Node
  Version: v5.4.1
  Path: /usr/local/bin/node

NPM
  Version: 3.5.3
  Path: /usr/local/bin/npm

Yeoman
  Version: 1.8.5

React Native CLI
  Version: 1.0.0

App
  React Native Version: ¯\_(ツ)_/¯
```

[Freds-MacBook-Pro:ReactNative fredbunn$ ignite new MyTest3
🔥 Setting MyTest3 on FIRE! 🔥
-----------------------------------------------
  (                  )   (                   
  )\ )   (        ( /(   )\ )    *   )       
 (()/(   )\ )     )\()) (()/(  ` )  /(   (   
  /(_)) (()/(    ((_)\   /(_))  ( )(_))  )\  
 (_))    /(_))_   _((_) (_))   (_(_())  ((_) 
 |_ _|  (_)) __| | \| | |_ _|  |_   _|  | __|
  | |     | (_ | | .` |  | |     | |    | _| 
 |___|     \___| |_|\_| |___|    |_|    |___|
-----------------------------------------------

An unfair headstart for your React Native apps.
https://infinite.red/ignite

-----------------------------------------------
Igniting MyTest3

✔︎ Found react-native
✔︎ Found git
✔︎ Getting ready for guests
✔︎ Running React Native setup (~ 2 minutes-ish)
✔︎ Downloading latest Ignite files from https://github.com/infinitered/ignite.git
✔︎ Using ignite release 1.7.1
⠋ Using ignite release 1.7.1
events.js:141
      throw er; // Unhandled 'error' event
      ^
AssertionError: Trying to copy from a source that does not exist: /usr/local/lib/node_modules/generator-react-native-ignite/app/templates/ignite-base/README.md.template
    at EditionInterface.exports._copySingle (/usr/local/lib/node_modules/generator-react-native-ignite/node_modules/mem-fs-editor/lib/actions/copy.js:45:3)
    at EditionInterface.exports.copy (/usr/local/lib/node_modules/generator-react-native-ignite/node_modules/mem-fs-editor/lib/actions/copy.js:23:17)
    at EditionInterface.module.exports [as copyTpl] (/usr/local/lib/node_modules/generator-react-native-ignite/node_modules/mem-fs-editor/lib/actions/copy-tpl.js:10:8)
    at AppGenerator._cpFile (/usr/local/lib/node_modules/generator-react-native-ignite/app/index.js:332:15)
    at AppGenerator._cpTemplate (/usr/local/lib/node_modules/generator-react-native-ignite/app/index.js:342:12)
    at AppGenerator.copyExistingStuff (/usr/local/lib/node_modules/generator-react-native-ignite/app/index.js:366:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-react-native-ignite/node_modules/yeoman-generator/lib/base.js:431:23)
    at /usr/local/lib/node_modules/generator-react-native-ignite/node_modules/run-async/index.js:26:25
    at /usr/local/lib/node_modules/generator-react-native-ignite/node_modules/run-async/index.js:25:19
    at /usr/local/lib/node_modules/generator-react-native-ignite/node_modules/yeoman-generator/lib/base.js:432:9
Freds-MacBook-Pro:ReactNative fredbunn$

**Comment by GantMan** [comment]
It looks to me that the pull from github must have failed.  Can you try again?

**Comment by fbunn** [comment]
Yes. I found the problem. Apparently XCode8 trashed GIT. I had to re-install the command line tools, accept the license agreement via command line, then reboot. DANG, that sucked.

NICE PACKAGE!
I did run across one warning, which I'll file next. It's "Warning: flattenChildren(...): two children with the same key, `1:$Full Button`
