### ISSUE TITLE
can not fire !!!!

### ISSUE THREAD

**Issue by yoohan-dex** [infinitered/ignite#562]
### Hiya! So you think it's broken or missing a feature eh?

Welllllll, it just might be.  Do me a favor and check the following.

- [ ] Issue does not already exist
- Identify exactly what aspect your issue is about
  - [x] ignite base application
  - [ ] ignite the cli
  - [ ] ignite generated code

Also, for the quickest assistance please run `ignite doctor` and paste in
everything (including the lines with 3 backticks).

```
  // ...

   create test/fastlane/Fastfile
   create test/fastlane/Matchfile
⠋ Copying Ignite goodies
➟ Package manager:	[ ]︎ npm  |  [✔︎]︎ yarn
𝗫 Installing Ignite dependencies (~ 1 minute-ish)
𝗫 Linking external libs
⠋ Linking external libsfs.js:557
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'test/android/app/src/main/AndroidManifest.xml'
    at Object.fs.openSync (fs.js:557:18)
    at Object.fs.readFileSync (fs.js:467:33)
    at Object.insertInFile (/usr/local/lib/node_modules/generator-react-native-ignite/utilities.js:68:27)
    at performInserts (/usr/local/lib/node_modules/generator-react-native-ignite/app/index.js:124:13)
    at AppGenerator._updateAndroid (/usr/local/lib/node_modules/generator-react-native-ignite/app/index.js:446:7)
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/generator-react-native-ignite/app/index.js:540:18)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:885:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
yoos-Mac-mini:workspace yoohoo$ 

```

and the doctor message:
```
Computer
  Platform: darwin

Ignite
  Version: 1.12.0
  Path: /usr/local/bin/ignite

Node
  Version: v7.3.0
  Path: /usr/local/bin/node

NPM
  Version: 3.10.10
  Path: /usr/local/bin/npm

Yeoman
  Version: 1.8.5

React Native CLI
  Version: 2.0.1

App
  React Native Version: ¯\_(ツ)_/¯
```

**Comment by GantMan** [comment]
Looks to me like android did not get generated.  So I'm guessing you can't do `react-native init` at all is that correct?

What error do you get with `react-native init test`

**Comment by yoohan-dex** [comment]
I can pass react-native-cli , both iOS and Android is normal. Only one thing just I still don't know how to use genymotion it will tell me can't patch bundle .


Now I reinstall and then post more details

Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by yoohan-dex** [comment]
First new I will meet this problem..

```
Igniting app

✔︎ Finding react-native
✔︎ Finding android
✔︎ Finding git
⠋ Finding gitshell.js: internal error
Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/generator-react-native-ignite/app/templates'
    at Object.fs.mkdirSync (fs.js:854:18)
    at /usr/local/lib/node_modules/generator-react-native-ignite/node_modules/shelljs/src/mkdir.js:65:10
    at Array.forEach (native)
    at Object._mkdir (/usr/local/lib/node_modules/generator-react-native-ignite/node_modules/shelljs/src/mkdir.js:48:8)
    at Object.mkdir (/usr/local/lib/node_modules/generator-react-native-ignite/node_modules/shelljs/src/common.js:240:23)
    at emptyFolder (/usr/local/lib/node_modules/generator-react-native-ignite/app/index.js:62:21)
    at AppGenerator.cleanBeforeRunning (/usr/local/lib/node_modules/generator-react-native-ignite/app/index.js:287:7)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-react-native-ignite/node_modules/yeoman-generator/lib/base.js:431:23)
    at /usr/local/lib/node_modules/generator-react-native-ignite/node_modules/run-async/index.js:25:25
    at /usr/local/lib/node_modules/generator-react-native-ignite/node_modules/run-async/index.js:24:19
```

and then I ` chmod -R 777 ` to avoid this problem

then meet the issue problem I just posted . T. T sad

**Comment by yoohan-dex** [comment]
@GantMan

**Comment by gaboelnuevo** [comment]
I have the [same problem](#issuecomment-269102014)

**Comment by derekgreenberg** [comment]
@yoohan-dex and @gaboelnuevo - check out this: https://github.com/nodeschool/discussions/issues/305 and see if following suggestions in that thread help to solve the problem.

**Comment by gaboelnuevo** [comment]
The issue was about permitions on create template folder. I created it and add permition manually and it works.

**Comment by nirabpudasaini** [comment]
Had the same issue, i had react cli and failed install of ignite using sudo install. 

Worked after i removed files that my user did not have access to rm -r /usr/lib/node_modules/

**Comment by jmuchaxo** [comment]
I have been stuck around this for a while and what worked for me was:
sudo rm -r -f /usr/lib/node_modules/generator-react-native-ignite/app/templates
sudo chmod 777 /usr/lib/node_modules/generator-react-native-ignite/app
ignite new myAppName

**Comment by skellock** [comment]
Depending on how `node.js` was setup on your machine, things can get hairy.

In Ignite 1 we write temporary files under the global node_modules path.  Combine this with a less-than-ideal `node.js` setup, and stuff like this happens.

In Ignite 2 the only file writing we do is to the directory your project is going.

Better days ahead!
