### ISSUE TITLE
Silent error in ignite generate needs to show error

### ISSUE THREAD

**Issue by jamonholmgren** [infinitered/ignite#606]
When there's a JS error in a generator, it currently dies silently. We need to show the error that occurred.

@skellock @GantMan

**Comment by skellock** [comment]
Here's the error when there's a problem:

```
❯ ignite g redux Steve
-----------------------------------------------
  (                  )   (
  )\ )   (        ( /(   )\ )    *   )
 (()/(   )\ )     )\()) (()/(  ` )  /(   (
  /(_)) (()/(    ((_)\   /(_))  ( )(_))  )\
 (_))    /(_))_   _((_) (_))   (_(_())  ((_)
 |_ _|  (_)) __| | \| | |_ _|  |_   _|  | __|
  | |     | (_ | | .` |  | |     | |    | _|
 |___|     \___| |_|\_| |___|    |_|    |___|
-----------------------------------------------

An unfair headstart for your React Native apps.
https://infinite.red/ignite

-----------------------------------------------

vvv -----[ DEBUG ]----- vvv
ReferenceError: boom is not defined
    at Object.module.exports [as run] (/Users/steve/src/sandbox/ignite/Foo3/node_modules/ignite-basic-generators/commands/redux.js:17:3)
    at Runtime.run (/Users/steve/src/ir/ignite/packages/ignite/node_modules/gluegun/src/domain/runtime.js:141:46)
    at Command.module.exports [as run] (/Users/steve/src/ir/ignite/packages/ignite/src/plugins/default/commands/generate.js:132:19)
    at Runtime.run (/Users/steve/src/ir/ignite/packages/ignite/node_modules/gluegun/src/domain/runtime.js:141:46)
    at run (/Users/steve/src/ir/ignite/packages/ignite/src/cli/cli.js:46:33)
    at Object.<anonymous> (/Users/steve/src/ir/ignite/packages/ignite/bin/ignite:9:31)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
^^^ -----[ DEBUG ]----- ^^^

```

Feel free to open this ticket again if you think this can be improved somehow.
