### ISSUE TITLE
error while igniting a new app (Cannot find module '../validation')

### ISSUE THREAD

**Issue by marclundgren** [infinitered/ignite#75]
hi!

I'm looking forward to using ignite, but I was unable to create a new app out-of-the-box.

## build command and error output

```
➜ ignite new MyApplication
🔥 Setting MyApplication on FIRE! 🔥
module.js:341
    throw err;
    ^

Error: Cannot find module '../validation'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/marc/.nvm/versions/node/v5.10.0/lib/node_modules/generator-react-native-ignite/app/index.js:13:19)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
```

## Node ENV

```
➜   node -v
v5.10.0
➜   npm -v
3.8.3
```

**Comment by GantMan** [comment]
Update to latest `generator-react-native-ignite` version `0.1.1` for the fix.

Sorry about that, npm can be sneaky.
