### ISSUE TITLE
ignite new PizzaApp broken from documentation

### ISSUE THREAD

**Issue by pavankat** [infinitered/ignite#884]
What's going on?

```
$ ignite new PizzaApp
/usr/local/lib/node_modules/ignite-cli/src/cli/check.js:2
const { nodeVersion, isNewEnough, hasAsyncAwait } = require('gluegun/sniff')
      ^

SyntaxError: Unexpected token {
```

---
Steps to reproduce

```
npm install -g ignite-cli
ignite new PizzaApp
```
---
`ignite doctor` results:

```
$ ignite doctor
/usr/local/lib/node_modules/ignite-cli/src/cli/check.js:2
const { nodeVersion, isNewEnough, hasAsyncAwait } = require('gluegun/sniff')
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/ignite-cli/bin/ignite:6:1)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
```

**Comment by skellock** [comment]
I reckon you're running Node 4?  Type `node -v`.

**Comment by robinvk6** [comment]
I have the same issue. I am running node version 5.7.1

**Comment by skellock** [comment]
You'll need Node 7.6.  That's when they released the new `await`/`async` features.

**Comment by pavankat** [comment]
yeah I have v5.10.1

upgrading now to see if this fixes it :)

**Comment by skellock** [comment]
You may need to `npm i -g ignite-cli` right after you install the new tools.
