### ISSUE TITLE
Error when trying to push to new repository on GitHub

### ISSUE THREAD

**Issue by anujshah108** [infinitered/ignite#911]
Hey guys thanks for the awesome boilerplate. 

Working on a project right now and created a new repository on my GitHub. I tried to set the origin URL to that repository and push up but I am getting a bunch of errors on the command line. 

```

> husky - npm run -s precommit

module.js:472
    throw err;
    ^

Error: Cannot find module '../App/I18n/languages/english.json'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/anuj/Desktop/instArt/Tests/Setup.js:3:1)
    at Module._compile (module.js:571:32)
    at loader (/Users/anuj/Desktop/instArt/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/anuj/Desktop/instArt/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Array.forEach (native)
    at Object.<anonymous> (/Users/anuj/Desktop/instArt/node_modules/ava/lib/test-worker.js:16:22)
    at Module._compile (module.js:571:32)
module.js:472
    throw err;
    ^

Error: Cannot find module '../App/I18n/languages/english.json'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/anuj/Desktop/instArt/Tests/Setup.js:3:1)
    at Module._compile (module.js:571:32)
    at loader (/Users/anuj/Desktop/instArt/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/anuj/Desktop/instArt/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Array.forEach (native)
    at Object.<anonymous> (/Users/anuj/Desktop/instArt/node_modules/ava/lib/test-worker.js:16:22)
    at Module._compile (module.js:571:32)

  11 exceptions

  ✖ Tests/Components/AlertMessageTest.js exited with a non-zero exit code: 1

  ✖ Tests/Components/DrawerButtonTest.js exited with a non-zero exit code: 1

  ✖ Tests/Components/FullButtonTest.js exited with a non-zero exit code: 1

  ✖ Tests/Components/RoundedButtonTest.js exited with a non-zero exit code: 1

  ✖ Tests/Redux/GithubReduxTest.js exited with a non-zero exit code: 1

  ✖ Tests/Redux/LoginReduxTest.js exited with a non-zero exit code: 1

  ✖ Tests/Sagas/GithubSagaTest.js exited with a non-zero exit code: 1

  ✖ Tests/Sagas/LoginSagaTest.js exited with a non-zero exit code: 1

  ✖ Tests/Sagas/OpenScreenSagaTest.js exited with a non-zero exit code: 1

  ✖ Tests/Sagas/StartupSagaTest.js exited with a non-zero exit code: 1

  ✖ Tests/Services/FixtureAPITest.js exited with a non-zero exit code: 1


> husky - pre-commit hook failed (add --no-verify to bypass)
> husky - to debug, use 'npm run precommit'
```

I am not using l18n so not sure why thats coming up.

Is there something I am missing?

Appreciate any help!

Thanks again!

**Comment by valinaga** [comment]
I had the same issue. I removed the precommit from scripts in package.json. I know it's not ideal, but it's annoying to not being able to commit.

**Comment by GantMan** [comment]
looks like it might be an issue with `husky`.

Yeah, the precommit does some checks to make sure you're lint free.   Can you verify?

**Comment by valinaga** [comment]
yes, the precommit has `npm run lint` in it.

**Comment by GantMan** [comment]
yup.   @valinaga - hit me on chat maybe we can ascertain the source and fix for everyone.

**Comment by ruddell** [comment]
I think the problem here is that [boilerplate/Tests/Setup.js](https://github.com/infinitered/ignite-ir-boilerplate-2016/blob/master/boilerplate/Tests/Setup.js) depends on options the user chooses - it currently expects react-native-vector-icons, react-native-animatable, and react-native-i18n.

I solved this in a new boilerplate by moving the prompts to before generation and passing the prompt results as props.  Then I changed [Tests/Setup.js to an ejs file](https://github.com/ruddell/ignite-jhipster/commit/53ea9e221d4016a6a9b3269a2e3126c216ac454a#diff-0b2a2b968e1a454cd2edb9ae05a346f9) for templating.

**Comment by skellock** [comment]
Ya, this is right @ruddell .  When we removed `i18n` and friends from the boilerplate into plugins, we didn't remove it all.  This will get fixed up.

I added `--skip-git` as an option when running `ignite new` however if you don't choose those options in the wizard (or select `--min`), it's a problem.

**Comment by anujshah108** [comment]
I have removed the precommit and prepush scripts for now and it is letting me push (I know not ideal).

**Comment by jamonholmgren** [comment]
We should definitely fix this. I've run into it myself.

**Comment by skellock** [comment]
Thers is a PR in with this fix from @ruddell 💪
