### ISSUE TITLE
No bundle URL present - @providesModule collision - react-native-router-flux

### ISSUE THREAD

**Issue by jamonholmgren** [infinitered/ignite#983]
So I tried spinning up an Ignite app and got this:

```
Last login: Thu Apr 20 09:24:24 on ttys004
/Users/jh/Code/ReactNative/apps/Xbow/node_modules/react-native/packager/launchPackager.command ; exit;
➜  ~  /Users/jh/Code/ReactNative/apps/Xbow/node_modules/react-native/packager/launchPackager.command ; exit;
~/Code/ReactNative/apps/Xbow/node_modules/react-native/packager ~
Scanning 827 folders for symlinks in /Users/jh/Code/ReactNative/apps/Xbow/node_modules (5ms)
 ┌────────────────────────────────────────────────────────────────────────────┐ 
 │  Running packager on port 8081.                                            │ 
 │                                                                            │ 
 │  Keep this packager running while developing on any JS projects. Feel      │ 
 │  free to close this tab and run your own packager instance if you          │ 
 │  prefer.                                                                   │ 
 │                                                                            │ 
 │  https://github.com/facebook/react-native                                  │ 
 │                                                                            │ 
 └────────────────────────────────────────────────────────────────────────────┘ 
Looking for JS files in
   /Users/jh/Code/ReactNative/apps/Xbow 

Loading dependency graph...
React packager ready.

jest-haste-map: @providesModule naming collision:
  Duplicate module name: react-native
  Paths: /Users/jh/Code/ReactNative/apps/Xbow/node_modules/react-native/package.json collides with /Users/jh/Code/ReactNative/apps/Xbow/node_modules/react-native-router-flux/node_modules/react-native/package.json

This warning is caused by a @providesModule declaration with the same name across two different files.
Failed to build DependencyGraph: @providesModule naming collision:
  Duplicate module name: react-native-vector-icons
  Paths: /Users/jh/Code/ReactNative/apps/Xbow/node_modules/react-native/local-cli/core/__fixtures__/files/package.json collides with /Users/jh/Code/ReactNative/apps/Xbow/node_modules/react-native-router-flux/node_modules/react-native/local-cli/core/__fixtures__/files/package.json

This error is caused by a @providesModule declaration with the same name across two different files.
Error: @providesModule naming collision:
  Duplicate module name: react-native-vector-icons
  Paths: /Users/jh/Code/ReactNative/apps/Xbow/node_modules/react-native/local-cli/core/__fixtures__/files/package.json collides with /Users/jh/Code/ReactNative/apps/Xbow/node_modules/react-native-router-flux/node_modules/react-native/local-cli/core/__fixtures__/files/package.json

This error is caused by a @providesModule declaration with the same name across two different files.
    at HasteMap._updateHasteMap (/Users/jh/Code/ReactNative/apps/Xbow/node_modules/react-native/packager/src/node-haste/DependencyGraph/HasteMap.js:158:13)
    at p.getName.then.name (/Users/jh/Code/ReactNative/apps/Xbow/node_modules/react-native/packager/src/node-haste/DependencyGraph/HasteMap.js:133:31)
~
Process terminated. Press <enter> to close the window
```

This is what I've tried so far:

• Reset simulator, made sure Xcode was up to date, rm node_modules and `yarn`
• Ignited with no options, ignited with max options
• Used ignite from master, used ignite from npm

@skellock let me know it's a breaking change introduced by `react-native-router-flux`. I'm going to switch over to [ignite-ir-next](https://github.com/infinitered/ignite-ir-next) since that's using react-navigation.

**Comment by skellock** [comment]
`ignite-ir-next` is fine.  going to pin the rnrf in our boilerplate.  standby.  testing.

**Comment by jamonholmgren** [comment]
![image](https://cloud.githubusercontent.com/assets/1479215/25243092/b211a9a6-25b0-11e7-863a-97c3c27d8927.png)

This is how I fixed it. I'll update the boilerplate to lock versions so this doesn't happen anymore.

**Comment by jamonholmgren** [comment]
Thanks to @skellock for the help!

**Comment by skellock** [comment]
Sweet.  Thx for the quick fix.  Can you `npm publish` out a new version too with the fix (you might be already I haven't checked and am too lazy to stop typing this and look)?
